### ISSUE TITLE
How to catch duplicate fixture name

### ISSUE THREAD

**Issue by simPod** [nelmio/alice#1012]
Here it was mentioned that when two fixtures are named the same, it gets overridden https://github.com/nelmio/alice/issues/765#issuecomment-313915307

I'd like to throw an exception when duplicate fixture names are declared. Any idea how?

The core line is this https://github.com/nelmio/alice/blob/802b1653de05579598de5fdbd0df1189bfde8234/src/FixtureBag.php#L36 but there's no way how to effectively override FixtureBag implementation.

**Comment by theofidry** [comment]
It's a kind of key feature of alice to be honest, hence why it is not done by default at least.

There is two possibilities here: either add a flag to `FixtureBag` to throw on it which could be made configurable or inject a logger to log it. I think the former would be better as logging tends to make everything slow

**Comment by simPod** [comment]
Thank you for response, I resolved it by overriding `SimpleDenormalizer` that now checks for duplicates and throws. If it's the key feature that suits most people, I don't see a point in somehow modifying it. Changing the behaviour is somehow "doable" so it's fine.
Thanks!
