### ISSUE TITLE
Template and random value

### ISSUE THREAD

**Issue by Grafikart** [nelmio/alice#1015]
I'm encoutering a strange bug with template and faker provider

Here is a sample

template.yaml
```yaml
App\Domain\Live\Live:
  live (template):
    # other fields
    created_at: <dateTimeBetween("first day of this year", "first day of this year")>
```

fixtures.yaml
```yaml
include:
  - templates.yaml

App\Domain\Live\Live:
  live{1..10} (extends live):
```

Then in my loader.php

```php
<?php
require 'vendor/autoload.php';
$loader = new Nelmio\Alice\Loader\NativeLoader();
$objectSet = $loader->loadFile('fixtures/lives.yaml');
dd($objectSet);
```

All my objects have the same created_at :(
Is there a way to use a template and still have random data for every field ?

**Comment by Grafikart** [comment]
False alert this is a problem with the library that rely on alice, not alice directly

**Comment by koekaverna** [comment]
Hello, there is any news on this topic?
