### ISSUE TITLE
Requirement on sebastian/comparator:^3.1 blocks phpunit:^9.0

### ISSUE THREAD

**Issue by icanhazstring** [nelmio/alice#1017]
The root requirement of `sebastian/comparator:^3.0` blocks the usage of `phpunit/phpunit:^9.0` as it requires `sebastian/exporter:^4.0`.

The dependency tree of `sebastia/comparator:^3.0` requires `sebastian/exporter:^3.1`.
But using `sebastian/comparator:^4.0` means dropping support for `php:^7.1` and `php:^7.2`

With semver this will not require a new major version of alice itself.
But this update should be considered in the next release.

**Comment by theofidry** [comment]
Yes it's something that can be done in a minor version, I guess we might as well just push to PHP 7.4 directly

**Comment by icanhazstring** [comment]
@theofidry I would not recommend dropping still supported version right away.
The EOL of 7.3 is still a long way. So give ppl some time to migrate.

**Comment by gabfr** [comment]
Also I think we'll have a conflict with `phpunit/phpunit:^7.0`.

Upgrading PHPUnit to at least 8 would be the ideal way. I'll try to work on a PR to do that. What do you guys think?

**Comment by icanhazstring** [comment]
Since `phpunit/phpunit:^7.0` has no further support (only 8 and 9 are supported right now)
we should go up to a minimum of 8 and removing support of everything below php7.3.

Maybe even require `phpunit/phpunit:^8.5 || ^9.0`

So yeah I am totally fine with it @gabfr 👍

**Comment by VincentClair** [comment]
Upgrading recently to Phpunit 9 drop the nelmio/alice from 3.5.8 to 3.4.1.  
Is this related ? Thanks for your help.

**Comment by stof** [comment]
isn't it possible to require `^3.1 || ^4.0` ? Then we don't need to drop old versions of PHP yet (they won't be running PHPUnit 9 anyway). AFAIK, there is no other BC break.

**Comment by stof** [comment]
@VincentClair yes it is related.

**Comment by icanhazstring** [comment]
@stof I see no reason to keep php 7.1 or even 7.2.
But sure - using `^3.1 || ^4.0` would be easiest way.
