### ISSUE TITLE
How to instantiate objects based on type hints ?

### ISSUE THREAD

**Issue by TristanPouliquen** [nelmio/alice#1028]
Hello,

I have different parameters in my fixtures that need to be instantiated with objects:
```php
use Money\Currency;
use AssoConnect\PHPDate\AbsoluteDate
class Entity
{
    private $currency;

    public function setCurrency(Currency $currency): self

    private $startDate;

    public function setStartDate(AbsoluteDate $startDate): self
```

I've seen that if type-hinted with the \DateTime class, you can put a fake generated datetime as a string and that Alice automaticallly converts it to a DateTime object (https://github.com/nelmio/alice/issues/169#issuecomment-69010837).

Is it possible to configure alice to do it with other classes also? And if so, where could I configure it?

Both Currency & AbsoluteDate are constructed by a simple string as a normal \DateTime object.

**Comment by theofidry** [comment]
I think what you are looking for is [here](https://github.com/nelmio/alice/issues/251). However I'm still not 100% on the API and so far no one has step up to try to provide an implementation.

The current alternative is to create your objects aside and inject them:

```yaml
Money\Currency:
    currency_1:
         # ...

Acme\Entity:
    entity_1:
        currency: '@currency_1'
```

**Comment by TristanPouliquen** [comment]
Thank you for your answer @theofidry. It indeed adds some complexity, I'll follow the other issue just in case but I'll pass via creating fixtures as you mentioned for now.
