### ISSUE TITLE
Function parameters are always parsed as string even when they are booleans or null

### ISSUE THREAD

**Issue by ste93cry** [nelmio/alice#1029]
The function arguments since version `3.x` are always being parsed as `string` instead of the right type, e.g.:

```
App\Entity\MyEntity:
    my_entity:
        __construct:
            - '<randomNumber(5, true)>'
```

I would expect `true` to be parsed as `boolean`, but it's not. The same goes for `null`. This breaks all functions with typehinted parameters. It used to work, so to me looks like a regression but I'm not sure about when it has been introduced

**Comment by theofidry** [comment]
Hm indeed, this completely changed to attempt to have a more deterministic and reliable engine for evaluating expressions.

Maybe some improvements could be done the way the parameters are passed to functions, but to be honest I feel it's going to be adding a lot of complexity for something for which there is a much simpler, robust and easy to use solution: #998

**Comment by ste93cry** [comment]
>it's going to be adding a lot of complexity for something for which there is a much simpler, robust and easy to use solution

I could agree, if that solution was something already available, but looking at the referenced issue it seems to me that we are far away from a real usable feature so imho it's worth considering to fix the bug of the current architecture, also because at the moment any typehinted function is gonna break and I still ask myself how this bug was not reported before. I did some experimenting by creating a custom lexer and token parser for both `boolean` and `null` values and it seems to work with minimal changes. Parsing numbers may be more complex though, but deciding to not support special notations like hex and other stuffs like that may simplify things a lot. WDYT?

**Comment by theofidry** [comment]
If you want to provide a PR for it sure 👍
