### ISSUE TITLE
Use container for instanciation

### ISSUE THREAD

**Issue by h4cc** [nelmio/alice#104]
Maybe this idea could be something for 2.0.

Instead of handling the instantiation of new Object in `Load\Base::createInstance()`, the whole process of handling and referencing instances could be done with a Dependency Injection Container.
The creating and referencing would just be configured in a ContainerBuilder. At the end of the fixture load, all public instances would be fetched like this `$container->get('user1')`.
Using a container could also help solve issues like forward references #59.

What do you think?

**Comment by theofidry** [comment]
Closing as it's a fairly old issue and unlikely to happen as Alice shouldn't be bound to a DIC. Plus for Symfony app [HautelookAliceBundle](https://github.com/hautelook/AliceBundle) should already handle most of the use cases.
