### ISSUE TITLE
Dependency `fzaninotto/faker` is deprecated

### ISSUE THREAD

**Issue by Kocal** [nelmio/alice#1058]
Hi :wave: ,

The `fzaninotto/faker` package has been deprecated, see https://github.com/fzaninotto/Faker and https://marmelab.com/blog/2020/10/21/sunsetting-faker.html.

I think it would be nice to replace it by [`fakerphp/faker`](https://github.com/FakerPHP/Faker) .

I don't have so much time right now but I can work on this when possible. :+1:

**Comment by theofidry** [comment]
That would be welcomed!
