### ISSUE TITLE
Compatibility with PHP 8.0

### ISSUE THREAD

**Issue by mdi22** [nelmio/alice#1066]
Please add compatibility to PHP 8.

Probably it is enough to add PHP 8.0 in composer.json:
"php": "^7.3|^8.0",

**Comment by theofidry** [comment]
Hi,

Whilst this is probably the only changed required, I'm not too keen to allow more versions if they are untested. If you wish for this to happen faster you can also help out, I believe there is #1064 and otherwise you can always for the repository and add this constraint on the fork meanwhile.

**Comment by Yozhef** [comment]
@theofidry  I think it can already be closed
