### ISSUE TITLE
Update and append based on primary key

### ISSUE THREAD

**Issue by marijnotte** [nelmio/alice#108]
Load the fixtures and update existing records based on a primary key would be a great feature. This would allow to use the fixtures for deployments without the need to clean the database manually first (we now have clean and load the data that has been changed and is loaded with fixtures manually).

**Comment by theofidry** [comment]
As @tshelburne it's out of the scope of Alice and the persistence layer will be completely removed from v3.

If you want to re-use an ID key, this should be a generated ID, not a database auto-increment.
