### ISSUE TITLE
Faker is being discontinued.

### ISSUE THREAD

**Issue by jlagneau** [nelmio/alice#1083]
The project is being archived on github and will not be updated anymore. Perhaps another library could be considered as a replacement.

https://github.com/fzaninotto/Faker
Author's blog about the reason it's discontinued: https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

**Comment by jawira** [comment]
I just checked project's _composer.json_ and it seems that they already found a replacement: https://github.com/FakerPHP/Faker :)

**Comment by jlagneau** [comment]
Oh snap, I'm pretty sure I checked but my searching-fu keep failing me recently. Thanks for the heads up.
