### ISSUE TITLE
How use Custom Instantiator?

### ISSUE THREAD

**Issue by albertoammar** [nelmio/alice#1088]
Could someone give me a practical example of using **Custom Instantiator**?

I'm currently using it like this:
```php
     $loader = new \Nelmio\Alice\Loader\NativeLoader();
      $objectSet = $loader->loadFile('ss.yml');
      $object = $objectSet->getObjects();
```

I see this [tutorial](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#custom-instantiator),  but I don't know how to add a chained instantiator or overwrite the existing one.

**Comment by theofidry** [comment]
@albertoammar this highly depends on how you are using Alice. If you are using it via Symfony you need to look up how the instantiators are registered and register your own one in a similar fashion. If you are using it without any framework I believe you need to override a method of `NativeLoader`

**Comment by albertoammar** [comment]
I'm using laravel, could you give me an example of how to override this method?

**Comment by theofidry** [comment]
Assuming you are using `NativeLoader`, you need to override [this method](https://github.com/nelmio/alice/blob/master/src/Loader/NativeLoader.php#L583). E.g. you extend the class and declare this method in the child class.
