### ISSUE TITLE
doctrine hydrator for current state export to yml fixture

### ISSUE THREAD

**Issue by Markcial** [nelmio/alice#112]
Would be nice to have a doctrine hydrator that exports the current state represented by a dql sentence to a yml configuration file.

**Comment by andrewtch** [comment]
Are there any plans to implement more generic way and create fixture dumper as sf 1.4 had?

**Comment by Seldaek** [comment]
No plans no but probably would be nice I agree.

**Comment by Markcial** [comment]
I  started a project on the 1.0 branch, i will look for some spare time to check if it can be easily ported to the new code and do a PR with it

**Comment by andrewtch** [comment]
Well, I've started a full dumper on  my fork.

@Seldaek , some questions still are there:

* for hydrator dumper, what do we dump inside collections (many to many, one to many etc)? empty collections and null values?
* same question applies to database dumper - do we dump all entities known by EntityManager? Or just a subset, like ```$dumper->dump($entityManager, array('User', 'Group')```?
* for a full database dumper, do we / can we add some limits (like only users with id less than 10 etc)

For starters, only OrmDumper will be implemented.

**Comment by andrewtch** [comment]
Btw, what's wrong with https://github.com/Spea/fixture-dumper ?

**Comment by Seldaek** [comment]
@andrewtch 

- not sure I got the hydrator dumper question
- for dumping I guess there should be a way to filter if possible.. This could probably live as a third party package though doctrine-alice-dumper or something. With a CLI command and all?
- same as above I suppose

Regarding Spea/fixture-dumper, I guess dumping to alice's format makes tweaking things easier than if you dump to doctrine fixtures format, but for sure it's an option depending on the use case.

**Comment by andrewtch** [comment]
Sorry for a late response )

When I dump fixtures from hydrator, to we dump and walk through 1:M - 1:1 relations?
As for a third party package... possibly, but it would require including additional components, the best way imho is to live in a core (as an array - php dumper and the convertor to the yml).

**Comment by theofidry** [comment]
As it's an old issue and far from being a focus for the next versions, I'm closing this one. If someones is still interested in this feature or something akin, please open a new issue for it.
