### ISSUE TITLE
Problem with oneToMany and entities that should't be persisted directly but only using cascade behaviour?

### ISSUE THREAD

**Issue by gremo** [nelmio/alice#1131]
I have a `Cart` entity which holds a collection of `CartItem` entities (Symfony/Doctrine way).

Upon adding an item to `Cart`, **if the item can be merged (1)** with an existing item, the item to be added is "ignored", in the sense that it's not added to the collection, and `setCart` is not called (Doctrine would not persist the item):

```php
// Cart addItem function 
public function addItem(CartItem $item): self
{
    if (!$this->items->contains($item)) {
        foreach ($this->items as $existingItem) {
            if ($existingItem->merge($item)) { // (1) Check item can be merged with the incoming
                return $this; // (2) We return, item is not added to the collection
            }
        }

        $this->items->add($item);
        $item->setCart($this);
    }

    return $this;
}
```

**What's the problem?** With fixtures, I have the problem that the `CartItem` would be persisted even if not added to the collection **(2)**:

```yaml
App\Entity\Cart:
    cart1:
      items: '@item{1..9}'

App\Entity\CartItem:
  item{1..9}:
    quantity: <numberBetween(1, 10)>
    product: '@product*'
```

**What the problem could bee?** It seems that `persist()` is called for each `CartItem` entity, causing my problem (`Cart` property is `null`, so the `persist` fail for the database foreign key check).

**Question is**: is there a way to say "just persist the cart with nested entities, without persisting every item in it"?

**Additional context!** The merge **(1)** is actually pretty simple:

```php
// CartItem merge function
public function merge(CartItem $item): bool
{
    // Merge if same product instance or same product identifier
    if (
        !$this->product || 
        !$item->getProduct() ||
        $this->product !== $item->getProduct() || 
        $this->product->getId() !== $item->getProduct()->getId()
    ) {
        return false;
    }

    return true;
}
```

**Comment by theofidry** [comment]
>Question is: is there a way to say "just persist the cart with nested entities, without persisting every item in it"?

To me it looks like whenever you want to persist a cart its items must be persisted first. I don't recall the details but I think there is a persist loader or something along those lines which is a service taking care of persisting & flushing those objects.

You can actually override the service to persist & flush as you desire instead.

**Comment by gremo** [comment]
Generally speaking yes but, in this case, where `addItem` should trigger custom logic (i.e compute total amount, apply a merge strategy, ignore some items) is needed. So items should be persisted only persisting the cart, and let Doctrine cascade behavior do the rest. Other scenario does not require this.

If you can confirm that there isn’t an option for disabiling the items persist behavior or create items “inline” inside the cart fixture itself… then i’ll digg into the code, thanks.

**Comment by alexislefebvre** [comment]
I think that could add a `addItems(…)` in `Cart` and provide a custom provider that return cart items: https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md

They should be merged and not persisted.

**Comment by theofidry** [comment]
I think @alexislefebvre answers it pretty well. Also this library only takes care of _generating_ the data. How it is persisted is handled by https://github.com/theofidry/AliceDataFixtures and I think can be completely customized (if you do require to access data generated by persisting an entity, within the fixture file, then you are in pickle though, but I think it is a modelling issue).
