### ISSUE TITLE
doctrine arraycollection support

### ISSUE THREAD

**Issue by Markcial** [nelmio/alice#114]
I have a code base which arraycollection is largely used, the specific call of arraycollection for replacement of the native array would be nice, maybe like the already used syntax for faker library `<ArrayCollection(array)>`

**Comment by tshelburne** [comment]
@Seldaek Are we considering adding `ArrayCollection` back into the library, or can we close this per the last comment?

**Comment by Seldaek** [comment]
I guess let's close, it's possible to write a custom provider if needed.
