### ISSUE TITLE
Add support sebastian/comparator ^6.0

### ISSUE THREAD

**Issue by nl404** [nelmio/alice#1163]
I've encountered an issue while trying to update my project to the new version of phpunit 11.0. However, the current version of nelmio/alice (3.13.3) restricts the use of sebastian/comparator version 6.0.0, which is required for compatibility with phpunit 11.0.

I understand that your package requires compatibility with sebastian/comparator versions from 3.0 to 5.0. Is it possible to consider updating nelmio/alice to support newer versions of sebastian/comparator, including version 6.0.0?

```
nelmio/alice is locked to version 3.13.3 and an update of this package was not requested.
nelmio/alice 3.13.3 requires sebastian/comparator ^3.0 || ^4.0 || ^5.0 -> found sebastian/comparator[3.0.0, ..., 3.0.5, 4.0.0, ..., 4.0.8, 5.0.0, 5.0.1] but it conflicts with your temporary update constraint (sebastian/comparator:6.0.0).
```

**Comment by theofidry** [comment]
IIRC the usage of the diff is fairly limited so it should be easy to add support for sebastian/comparator v6. PRs are welcomed, I am not sure when I would be able to check it out otherwise.
