### ISSUE TITLE
SymfonyBundle

### ISSUE THREAD

**Issue by lyrixx** [nelmio/alice#1175]
Hello, somethings is unclear to me.

In the readme, we can read:

![image](https://github.com/nelmio/alice/assets/408368/26799461-a51d-4e50-887e-6e4081c3b6ec)

https://github.com/nelmio/alice?tab=readme-ov-file#symfony

But in this code base, there is https://github.com/nelmio/alice/blob/main/src/Bridge/Symfony/NelmioAliceBundle.php

---

So which one are we supposed to use?

**Comment by theofidry** [comment]
There is 3 packages which provide different things, the breakdown can be found in https://github.com/theofidry/AliceBundle?tab=readme-ov-file#when-to-use-this-bundle. So which one you actually need depends on your usage. Could be that for you NelmioAlice or FidryAliceDataFixtures is entirely sufficient

**Comment by lyrixx** [comment]
thanks
