### ISSUE TITLE
Rename `Nelmio\Alice\ORM\Doctrine` namespace

### ISSUE THREAD

**Issue by cystbear** [nelmio/alice#118]
As far as MongoDB fixtures can be runned on stock Alice without any changes of code (I have used this numerous times, and it looks like PHPCR fixtures can be applied as well) there is confusing namespace `Nelmio\Alice\ORM\Doctrine`. `ORM` part of namespace redundant there.

I have even prepared PR #117, without any BC breaks, but to be consistent there is need to do patching bundle(s) that lies on top of Alice, [this](https://github.com/hautelook/AliceBundle/blob/master/Alice/Loader.php#L70) for example

Or let's just rename `Nelmio\Alice\ORM\Doctrine` to something more common, like `Nelmio\Alice\Persister\Doctrine` take a look #119

**Comment by theofidry** [comment]
So, has been dealt with right?

**Comment by cystbear** [comment]
yup.
@theofidry Take a look #121
