### ISSUE TITLE
Nondeterministic optional method calls

### ISSUE THREAD

**Issue by brainlock** [nelmio/alice#1230]
Hi,

I stumbled upon nondeterministic behavior in the way optional method calls are generated:

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

class Foo {
    public function __construct(
        public string $a = "",
        public int $b = 0,
        public int $c = 0,
        public int $d = 0,
    ) {}

    public function setC(int $c): void {
        $this->c = $c;
    }

    public function setD(int $d): void {
        $this->d = $d;
    }
}

$loader = new Nelmio\Alice\Loader\NativeLoader();
$objectSet = $loader->loadData([
    Foo::class => [
        'foo' => [
            'a' => '<word()>',
            'b' => '<numberBetween(0, 100)>',
            '__calls' => [
                ['setC' => [ 42 ]],
                ['setD (50%?)' => [ 42 ]],
            ],
        ],
    ],
]);

print_r($objectSet->getObjects());
```

If we invoke the script a few times, we see that $a, $b and $c have stable pseudorandom values, while $d
flip-flops between 0 and 42.

```
% for i in $(seq 1 5); do php repro.php; done
Array
(
    [foo] => Foo Object
        (
            [a] => consequatur
            [b] => 25
            [c] => 42
            [d] => 42
        )

)
Array
(
    [foo] => Foo Object
        (
            [a] => consequatur
            [b] => 25
            [c] => 42
            [d] => 42
        )

)
Array
(
    [foo] => Foo Object
        (
            [a] => consequatur
            [b] => 25
            [c] => 42
            [d] => 0
        )

)
Array
(
    [foo] => Foo Object
        (
            [a] => consequatur
            [b] => 25
            [c] => 42
            [d] => 0
        )

)
Array
(
    [foo] => Foo Object
        (
            [a] => consequatur
            [b] => 25
            [c] => 42
            [d] => 42
        )

)
```

The immediate cause for this is that OptionalMethodCallProcessor was changed from using mt_rand to random_int here in this commit: https://github.com/nelmio/alice/commit/a7e15b08a64d4f6fb64b4c3b58bd6a710f71050e#diff-08609f7290422a7652a1827996b95b93293221086ef456fa539bf0770c4b117bR68

Arguably though it shouldn't have been using mt_rand() directly in the first place, but rather use the FakerGenerator instance like all other value generators in Alice. (Then Faker uses mt_rand internally, which is why it happened to work before the switch to random_int, but that's another story)

I could make a PR to pass the FakerGenerator through to OptionalMethodCallProcessor, if you think that's OK. Or do you see a better way to fix this? I am not sure it could be released without bumping versions though, what is your policy regarding that? (I can easily run this from a fork, so absolutely no pressure for a release).

I'd also like to write a test for this, but I don't quite see how I could make sure that a new instance of Faker is used (with the seed re-initialized).

Thanks for your work on Alice!

**Comment by theofidry** [comment]
Hi thanks for the report!

>I could make a PR to pass the FakerGenerator through to OptionalMethodCallProcessor, if you think that's OK. Or do you see a better way to fix this? I am not sure it could be released without bumping versions though, what is your policy regarding that? (I can easily run this from a fork, so absolutely no pressure for a release).

Since `OptionalMethodCallProcessor` is final it can be made whilst preserving backward compatibility by making it optional

>I'd also like to write a test for this, but I don't quite see how I could make sure that a new instance of Faker is used (with the seed re-initialized).

Apart from using processes, which is a bit awkward in itself but feasible at least, I don't really see a way to do so. I'm not sure how faker preserves the seed though.

A PR would be greatly appreciated!

**Comment by brainlock** [comment]
I could reproduce it in a test by using a new NativeLoader each time. A sequence length of 10 is enough to fail reliably (with my fix reverted): https://github.com/nelmio/alice/pull/1231/files#diff-a748edb88adec447e86a7845cac8f10199f6bc0bee40bb7c428831c01032697dR1579-R1605
