### ISSUE TITLE
Seeding mt_rand breaks UUID generation for PHPCR

### ISSUE THREAD

**Issue by jonnnnyw** [nelmio/alice#124]
This is not really an issue, more something to watch out for. I have put this here incase anyone is having a similar issue. It took me a while to figure out what was going on so it might be helpful for someone.

By default when generating fixtures the Base loader seeds mt_rand with 1.

```php
/**
 * @see \Nelmio\Alice\Loader\Base
 */
 
public function __construct($locale = 'en_US', array $providers = array(), $seed = 1)
{
    ...

    if (is_numeric($seed)) {
        mt_srand($seed);
    }
}
```

This causes an issue with PHPCR as it uses mt_rand to generate unique ID's for documents. Seeding mt_rand can lead to duplicate ID's being generated for unrelated document nodes.

The scenario where I ran into this problem was when I created test fixtures in the document repository before a test and then tried to test the creation of new documents through an API. The new documents created would often have the same UUID as documents that already existed in the repository, leading to an integrity constraint exception.

Passing null into the constructor of the loader did fix this issue however that lead to the ODM cache getting extremely large due to the number of nodes created by inconsistent test data which eventually slowed the tests right down.

A work around for this is to use the default seed value when generating fixtures and then reseed mt_rand before running any tests that create new nodes. It's not ideal but it seems to work.

**Comment by theofidry** [comment]
After taking a look at this, there is not much we can do on our side: it's either PHPCR that must use a different strategy to generate the IDs or Faker, nothing can be done at alice lever to fix that. For that reason, I'll be closing this 2yo issue and if someone still have an issue with it they should be able to find it still :)
