### ISSUE TITLE
Silent failure on non-existent file path

### ISSUE THREAD

**Issue by seggen-ibuildings** [nelmio/alice#134]
If I call Fixtures::load() using a non-existent file path, nothing happens. I don't get an error, but I would like to have one. Could you fix this?

**Comment by cmfcmf** [comment]
It is handled here: https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Fixtures.php#L76.

**Comment by theofidry** [comment]
Closing as it's been solved since at least ff44de0384c6f8d7232f8f5302a3ac5cbba509a0
