### ISSUE TITLE
variables question

### ISSUE THREAD

**Issue by smarques** [nelmio/alice#148]
Hi, I have a situation like this

```
user{1..100}:
  slug (unique): <firstName()>.<lastName()>
  email (unique): @self->slug<lastName()>@triboom.com
```

I would like to use the same value I generated for slug as the first part of an email address
I tried
```
@self->slug
$slug
<@self->slug>
<$slug>
```

but it does not get replaced.

Any hints?
Thank you 
sergio

**Comment by tshelburne** [comment]
@smarques Is this fixed for you and we can go ahead and close?

**Comment by smarques** [comment]
yes, sorry... closing, thank you very much
