### ISSUE TITLE
[property assignment] should the assignment check whether ancestor has the  property?

### ISSUE THREAD

**Issue by soapsign** [nelmio/alice#156]
current it there not setter function for a class property, the ultimate step is through property_exists($instance, $key) and injection.
But what if the class extends some parents class and the property is set to be private, this checking alone would not be able to set the property.
So i suggest we should check property_exists against class's parents for the final step.

**Comment by ianfp** [comment]
+1 for supporting references in constructors -- I'm having the same problem.

(P.S. Are "+1" comments bad GitHub etiquette?)

**Comment by theofidry** [comment]
References in the constructor should work or at least a test has been added for that in 4c9fe135d5d5f665a58df246544c9410ffdac372 so it's guaranteed to be supported in since `1.5.0`.
