### ISSUE TITLE
Possibility to add a sequence of items in a range and not randomly

### ISSUE THREAD

**Issue by Markcial** [nelmio/alice#165]
The Alice fixtures library currently supports to add a random set of items by reference with this syntax : 
`5x @item*` a nice feature could be to add a fixed sequence of items for fixed and defined fixtures that are not tested by random, for example if i want to testst the items from 1 to 5 i statically created i have no choice but to type them one by one `@item1, @item2, @itemn...` with a simple sequence syntax like `@item{1..n}` that could be achieved easilly.

**Comment by bendavies** [comment]
+1

**Comment by sdepablos** [comment]
Ping
