### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#172]
My `User` entity may have multiple phones which is a separate entity (ManyToOne relationship). I generate my data as following:

``` yaml
Nelmio\Entity\User:
    user_{1..100}:
        ...
        phones: <numberBetween(0, 3)>x @phone_*

Nelmio\Entity\Phone:
    phone_{1..100}:
        number: <phoneNumber()>
        comment: 30%? <sentence()>
```

The problem is that at some points, I have the a `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry`. How may I solve this?

**Comment by Seldaek** [comment]
`phones (unique): <numberBetween(0, 3)>x @phone_*` should ensure no duplicates are created. I am not sure if this works with arrays though.

**Comment by theofidry** [comment]
When I try this I've got the following error:

```
[RuntimeException]                                                                                     
  Couldn't generate random unique value for Nelmio\Entity\User  
  : phones in 128 tries.
```

I tried by decreasing the number of entity (ex: `1..5` for `User` and `1..15` for `Phone`), but it gives the same error.

**Comment by Seldaek** [comment]
And with only one phone per user?

**Comment by theofidry** [comment]
You mean `phones (unique): 1x @phone_*`? Same error.

**Comment by Seldaek** [comment]
Ok then I guess we don't support arrays yet :)

**Comment by theofidry** [comment]
It would be great if it could be added!

**Comment by kgilden** [comment]
Also ran into this problem today. Arrays do seem to be supported, but slightly differently than expected. Currently the entire array is hashed and checked whether a similar array has already been generated. One would probably expect each individual item within the array to be unique. So changing [this part of the code](https://github.com/nelmio/alice/blob/0ea7273e759f3f2e894375fd6e9c069f4a2db892/src/Nelmio/Alice/Instances/Populator/Populator.php#L111..L122) might do the trick.

**Comment by theofidry** [comment]
After some consideration, it would still be a change of behaviour. This change has landed in 3.x, but I would rather be in favour of deprecating this behaviour in 2.x rather than changing it like that.
