### ISSUE TITLE
Entity factory

### ISSUE THREAD

**Issue by dagio** [nelmio/alice#174]
Hello

To instantiate an entity right now we can:
 - use the __constructor
 - use a static method (Ex: MyEntity::create() )

We use anemic models which means we have only:
 - properties
 - getters and setters

To create new instance of those models we use factories. Those factories just have a "create" methods and their responsibilities are only to create entities with the default values.

It would be nice to able to pass the factory class in the YAML config such as : 
__construct: { \Acme\Component\News\Factory\News::create: [] }

**Comment by theofidry** [comment]
Although being an old issue, that is something that is planned for v3. Follow up in #388.
