### ISSUE TITLE
Doctrine translatable

### ISSUE THREAD

**Issue by vittore** [nelmio/alice#178]
Is there a way to load doctrine translatable entities' fixtures?
I use https://github.com/KnpLabs/DoctrineBehaviors#translatable

For example:

```
    $category = new Category;
    $category->translate('fr')->setName('Chaussures');
    $category->translate('en')->setName('Shoes');
    $em->persist($category);

    // In order to persist new translations, call mergeNewTranslations method, before flush
    $category->mergeNewTranslations();
    $em->flush();
```

Thanks in advance.
v.

**Comment by Seldaek** [comment]
I don't think there is no.. Maybe you could create the CategoryTranslation entities as fixtures and persist that though.

**Comment by nicolas-bastien** [comment]
Hi, we have the same question using CMF 

https://github.com/nelmio/alice/issues/160

@vittore did you find a clean solution ?

**Comment by vittore** [comment]
No news, I'm sorry.

v.


2015-04-14 15:17 GMT+02:00 Nicolas Bastien <notifications@github.com>:

> Hi, we have the same question using CMF
>
> #160 <https://github.com/nelmio/alice/issues/160>
>
> @vittore <https://github.com/vittore> did you find a clean solution ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nelmio/alice/issues/178#issuecomment-92822712>.
>



-- 
http://www.zen.pn.it

**Comment by theofidry** [comment]
An acceptable workaround has been show in #160.

In v2, the only thing alice seems to be lacking on this side is the ability to call multiple times the same method with different arguments.

**Comment by theofidry** [comment]
Closing this in favour of https://github.com/nelmio/alice/issues/293.
