### ISSUE TITLE
Unable to use <current()> for object when its method is called

### ISSUE THREAD

**Issue by PLEEROCK** [nelmio/alice#179]
```yaml
\Question:
    question_{1..50}:
        author: @user*
\Comment:
    comment_{1..50}:
        user: @question-<current()>->author
```

Seems like there is no way to make comment's author the same as question's author - it gives me an error that it expects a User, but null is given

**Comment by Seldaek** [comment]
`@question-<current()>->author` is wrong, it should be `@question_<current()>->author` with underscore, and then maybe it'll work but frankly I am not sure anymore if this is supported or not :)

**Comment by FoxxMD** [comment]
I'm running into the same issue
