### ISSUE TITLE
Using JSON in Yaml fixtures

### ISSUE THREAD

**Issue by thul** [nelmio/alice#183]
Some of the entities im trying to write fixtures for contain json data. 
The data looks like this in the fixture:
```json 
'{"label_alignment":"block","max_length":50,"field_length":"60","default_value":""}' 
```
But once i run the fixtures, the ", { and } will be escaped with a \ making it invalid json
I tried putting a Processor in between, but the Pre persist and Post persist data is both unescaped.

This is the entity entry for the data

    /**
     * @ORM\Column(
     *     type="json_array"
     * )
     * @Type("array")
     * @Groups({"list", "detail"})
     */

Is it something i am doing wrong? or is it something the entities are doing wrong? or is Alice doing something wrong? I am clueless. Any help will be nice.

**Comment by dlondero** [comment]
I believe you should just define an array (or yaml object) and let 
doctrine serialize it to json..

i.e.

field {label_alignment: block, max_length: 50, field_length: 60, 
default_value: ""}

**Comment by Seldaek** [comment]
I believe you should just define an array (or yaml object) and let 
doctrine serialize it to json..

i.e.

```yaml
    field: {label_alignment: block, max_length: 50, field_length: 60, 
default_value: ""}
```

**Comment by thul** [comment]
That seemed to have solved it, in combination with me removing an 'array to string' conversion error in the entity. Arrays given to the setConfig() were casted to a string for some reason

**Comment by Eliasyoussef47** [comment]
I was able to solve this using a custom faker provider ([as mentioned here](https://github.com/nelmio/alice/issues/935#issuecomment-397587318)).

JsonProvider.php
```php
class JsonProvider
{
    /**
     * Decodes a JSON string.
     * This function must be used in order to use a JSON object (string) as a column value. Without this method, the 
     * JSON string would be escaped. The value that will be assigned to the column will be a correct JSON string.
     * @see https://github.com/nelmio/alice/issues/935#issuecomment-397587318
     * @example <json_decode('{"jeff":"IDK","slim":"shady","age":5}')>
     *
     * @throws JsonException
     */
    public function json_decode(string $json, bool $assoc = false, int $depth = 512, int $options = 0)
    {
        return json_decode($json, $assoc, $depth, JSON_THROW_ON_ERROR | $options);
    }
}
```

fixtures.yaml
```yaml
Fully\Qualified\Name\MyClass:
  my_class_7:
    id: 1
    value: <json_decode('{"jeff":"IDK","slim":"shady","age":5}')>

```

Notice that I made json_decode throw an exception when something goes wrong. I did this to prevent any unexpected behaviour and to stop the fixtures early and report the problem.
