### ISSUE TITLE
[Doctrine\ORM\ORMInvalidArgumentException]   EntityManager#persist() expects parameter 1 to be an entity object, NULL given.

### ISSUE THREAD

**Issue by mrsax** [nelmio/alice#184]
After creating the fixtures I kept on getting these errors no matter what I did to my entities' relations 

(making them nullable= true etc...)

After a while I realised I was using Gedmo\Mapping\Annotation\Blameable

Solution :  for every entity you havo to add a user for the createdBy and updatedBy property.

eg
xx\ArticleBundle\Entity\ArticleType:
    ArticleType1:
        name: Case Study
        createdBy: @User1
        updatedBy: @User1

Problem Solved

I hope this helped you if you were getting the same error, 

thanks for letting me know

**Comment by Seldaek** [comment]
Closing I guess since you resolved, but it's good to have here for future reference.

**Comment by mrsax** [comment]
That was my aim

just as a reference to help people with the same issue :)

thanks for the good work 


Mathieu


	
Mathieu Dierckx

Webdeveloper

mathieu@pau.be <mailto:jens@pau.be>
Tel.: 0495 92 06 70
http://www.pau.be <http://www.pau.be/>
Pàu BVBA | Albrecht Dürerstraat 33A | B 2060 Antwerpen
Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Als dit bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden. Prêt à utiliser staat door de elektronische verzending van dit bericht niet in voor de juiste en volledige overbrenging van de inhoud, noch voor tijdige ontvangst daarvan. Voor informatie over Prêt à utiliser raadpleegt u http://www.pau.be <http://www.pau.be/>.
