### ISSUE TITLE
Making Faker\Generator's accessable from outside.

### ISSUE THREAD

**Issue by h4cc** [nelmio/alice#186]
Currently, the Faker Generators are enclosed inside the loaders:
https://github.com/nelmio/alice/blob/1.x/src/Nelmio/Alice/Loader/Base.php#L461

Accessing the Generators from the outside would be useful to be abled to create more Faker Provider that extend `Faker\Provider\Base`, because that needs a generator to build up on: https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Base.php#L24

Simple Example:
```php
class ExtendedAddressProvider extends Faker\Provider\Address {
    protected static $cityFormatsCool = array(
        '{{firstName}}{{citySuffix}} is cool',
    );
    public function cityWithCoolNames()
    {
        $format = static::randomElement(static::$cityFormats);

        return $this->generator->parse($format);
    }
}
```
Such a provider will need a Generator in its constructor, but these are not accessable outside the loaders till now.
Maybe this could be a change for 2.0?

**Comment by gnat42** [comment]
This would be very helpful indeed

**Comment by Seldaek** [comment]
Sounds good to me, not sure how this code looks in the current master/2.0-dev, but if you see a way to make an improvement there please send a PR :)

**Comment by theofidry** [comment]
+1 would be great!

**Comment by h4cc** [comment]
@theofidry No plan here yet ...

**Comment by theofidry** [comment]
@h4cc  erf a pity :( I would be great not to have to override the load method just for [this line](https://github.com/theofidry/Incipio/blob/dev/src/ApiBundle/DataFixtures/ORM/DataLoader.php#L42).

**Comment by theofidry** [comment]
Kind of old post so I have lost a little bit sight of what needs to be changed, but if we make the [Nelmio\Alice\Loader\Base::getGenerator()](https://github.com/nelmio/alice/blob/1.x/src/Nelmio/Alice/Loader/Base.php#L461) `public` instead of `private` would solve the problem?

**Comment by theofidry** [comment]
Any opinion on this @Seldaek? I can provide a PR to solve this issue but I would like to have your opinion first.

**Comment by Seldaek** [comment]
Sounds ok to me but would be good to have @tshelburne's opinion as he's more aware of the 2.0 design.

**Comment by theofidry** [comment]
As in real life it is fairly rare to have to access to a faker instance (most of providers have static methods) and considering it's a fairly old issue and nobody really wants to dig into this again, I'll be closing this one. If it is still a problem and are willing to look into it, feel free to open a new issue for it.
