### ISSUE TITLE
Make objects of stdClass

### ISSUE THREAD

**Issue by dmitryvakulenko** [nelmio/alice#187]
Hello!
This is great library but I need to make objects of stdClass having custom set of properties. This feature is very useful to make tests for Soap services.

I added this feature by code bellow. You may use it if you'll decide to add this feature to main line of development.

```
class Property implements MethodInterface
{
    /**
     * {@inheritDoc}
     */
    public function canSet(Fixture $fixture, $object, $property, $value)
    {
        return property_exists($object, $property) || $object instanceof \stdClass;
    }

    /**
     * {@inheritDoc}
     */
    public function set(Fixture $fixture, $object, $property, $value)
    {
        if ($object instanceof \stdClass) {
            $object->{$property} = $value;

            return;
        }

        $refl = new \ReflectionProperty($object, $property);
        $refl->setAccessible(true);
        $refl->setValue($object, $value);
    }
}
```

**Comment by tshelburne** [comment]
@dmitryvakulenko I'm curious, what do your fixture files look like?

**Comment by theofidry** [comment]
Technically you can already do it:

```yaml
\stdClass:
    std: ~
```

Will generate an `\stdClass` instance as expected. Although right now you wouldn't be able to assign any value to it.
