### ISSUE TITLE
Using with Gedmo's Translatable behaviour

### ISSUE THREAD

**Issue by aderuwe** [nelmio/alice#192]
Hi,

Not sure if this is the right place but I couldn't find any resource anywhere.

I'm trying to insert fixtures for several locale's using Gedmo's translatable. In order to do that, setLocale() has to be called on the entity, and then persisted.

Essentially, I'd have to repeat my fixture over several setLocale() calls.

Any clues?

**Comment by aderuwe** [comment]
This is actually easily handled by a Processor - closing.

**Comment by afilina** [comment]
@aderuwe Can you share that processor please?
