### ISSUE TITLE
Processor with FOSUserBundle

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#199]
Could I have information on what the [example of processor](https://github.com/nelmio/alice#processors) given really does? Is it really necessary because I forgot to use it and it seemed to work so just asking to clear things up.

**Comment by theofidry** [comment]
I've just tested again to make sure: I succeeded to load my user fixtures and then login, with a standard FOSUser install. So my question is really more to try to understand this part because I guess it wasn't put here without any reason.

**Comment by jenkoian** [comment]
I added this section to the README, it was a while ago so excuse the memory jogging but I think it was down to passwords didn't get encoded otherwise, nor did the canonical fields get set. More info here: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/ef7ca325929ff102fff521653a2e3b88c7a40361/Resources/doc/user_manager.md#updating-a-user-object

**Comment by theofidry** [comment]
Ok it does make sense. But then I still fail to understand why it does work in my case cf. https://github.com/theofidry/Incipio/tree/dev. I do not use any processor and set the password via the `plainpassword` property. When I check into my database the password is properly encrypted.

Maybe it's the `fos_user.use_listener` property which is set to true by default (I've just seen that thanks yo your link). I will check that later.

**Comment by theofidry** [comment]
Indeed it is that. So could it be possible to add a word about that in the processor section (since the example is for the FOSUserBundle) so that there is not any confusion?

**Comment by jenkoian** [comment]
Yeah, maybe a link to the fos user docs or something? It's just an example of a processor in action, so perhaps not worthing being too specific, but anything to help people out I guess :)
