### ISSUE TITLE
Multiple reference fixture range @user{1..10}

### ISSUE THREAD

**Issue by iBasit** [nelmio/alice#203]
group{1..10}:
        members: @user{1..10}

this example is giving problem 

Entity with Id @business_{1..2} and Class Eggs\CoreBundle\Entity\Business not found

It is putting as it is. If i change it to @business_* or @business_1, this works fine, but above range is giving me problem.

**Comment by iBasit** [comment]
business_{1..10}:
          email (unique):   <email()>


I'm trying to build 3 plans for all 10 business's. so each business will have 3 plans. 
plan_{1..3}:
          business: @business_{1..10}
          name:         <word()> Plan

**Comment by fschaeffer** [comment]
How about using 
```yaml```
plan_{1..3}:
    business: 10x @business_*
    name: word() Plan
```

**Comment by theofidry** [comment]
:+1: for this feature, could be quite useful :)

**Comment by kolinko-ant** [comment]
I face the same problem. @iBasit did you solve it with nelmio alice or it can't do such things now?

**Comment by theofidry** [comment]
Not sure since when but this feature has been merged now, cf. [multiple references doc](https://github.com/nelmio/alice/blob/2.x/doc/relations-handling.md#multiple-references).
