### ISSUE TITLE
Need some advice for create custom provider

### ISSUE THREAD

**Issue by paquitodev** [nelmio/alice#205]
I have an entity where a field should be constructed as:

    qlv_ followed by the result of this regex [a-zA-Z0-9]{18}

How I can achieve that?

**Comment by tshelburne** [comment]
The field name? I suppose you could register a custom ` namespace Nelmio\Alice\Instances\Populator\Methods\MethodInterface` that would run on the condition the property name matches `qlv_`, and then generate the regex part in the `set` method. Does that make sense?

**Comment by paquitodev** [comment]
@tshelburne I will close this issue and let this question for SO, take a look to this http://stackoverflow.com/questions/30115354/using-custom-faker-data-providers-without-standard-doctrine-fixtures-in-nelmio-a I am trying to do the same

**Comment by paquitodev** [comment]
@tshelburne did you see the post at SO? I need some help on that since I am stucked on it, thx in advance
