### ISSUE TITLE
How to deal with fixtures when have ManyToMany relations

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#206]
I have this column in a `Email.php` entity:

	   /**
	     * @ORM\ManyToMany(targetEntity="Media", inversedBy="mediaXrefMail", cascade={"persist", "remove"})
	     * @ORM\JoinTable(name="emails_media_xref",
	     *      joinColumns={@ORM\JoinColumn(name="emails_id", referencedColumnName="id")},
	     *      inverseJoinColumns={@ORM\JoinColumn(name="media_id", referencedColumnName="id")}
	     * )
	     */
	    protected $emailsMediaXref;

How do I deal with fixtures on this case? It's possible?

**Comment by Seldaek** [comment]
Should be possible if you create a bunch of `Media` objects and then reference them into this property like `emailsMediaXref: 3x @media*` you would get 3 media objects linked on every email.

**Comment by paquitodev** [comment]
Thanks @Seldaek. Could you give me some advice in how to handle the fixture when relationship is on both sides? Take a look to `Brand` and `TargetBrand` entities below:

	class Brand
	{
	    ...

	    /**
	     * @ORM\OneToMany(targetEntity="TargetBrand" , mappedBy="brand")
	     */
	    protected $targetBrand;

	    protected $targets;

	    public function __construct()
	    {
	        $this->targets = new ArrayCollection();
	        $this->targetBrand = new ArrayCollection();
	    }

	    public function getTargets()
	    {
	        $targets = new ArrayCollection();
	        foreach ($this->targetBrand as $target) {
	            $targets[] = $target->getTarget();
	        }

	        return $targets;
	    }

	    public function setTargets($targets)
	    {
	        foreach ($targets as $target) {
	            $targetBrand = new TargetBrand();
	            $targetBrand->setBrand($this);
	            $targetBrand->setTarget($target);
	            $this->addTargetBrand($targetBrand);
	        }
	    }

	    public function addTargetBrand($targetBrand)
	    {
	        $this->targetBrand[] = $targetBrand;
	    }

	    public function removeTargetBrand($targetBrand)
	    {
	        return $this->targetBrand->removeElement($targetBrand);
	    }
	}

	class TargetBrand
	{

	    /**
	     * @var int
	     *
	     * @ORM\Column(type="integer")
	     */
	    protected $priority;

	    /**
	     * @var Target
	     *
	     * @ORM\ManyToOne(targetEntity="Target", inversedBy="targetBrand")
	     * @ORM\JoinColumn(name="targets_id", referencedColumnName="id")
	     * */
	    protected $target;

	    /**
	     * @var Brand
	     *
	     * @ORM\ManyToOne(targetEntity="Brand", inversedBy="targetBrand")
	     * @ORM\JoinColumn(name="brands_id", referencedColumnName="id")
	     * */
	    protected $brand;

	    ....
	    
	    /**
	     * Set target.
	     *
	     * @param \PDI\PDOneBundle\Entity\Target $target
	     *
	     * @return TargetBrand
	     */
	    public function setTarget(Target $targets = null)
	    {
	        $this->target = $targets;

	        return $this;
	    }

	    /**
	     * Get target.
	     *
	     * @return \PDI\PDOneBundle\Entity\Target
	     */
	    public function getTarget()
	    {
	        return $this->target;
	    }

	    /**
	     * Set brand.
	     *
	     * @param \PDI\PDOneBundle\Entity\Brand $brand
	     *
	     * @return TargetBrand
	     */
	    public function setBrand(Brand $brand)
	    {
	        $this->brand = $brand;

	        return $this;
	    }

	    /**
	     * Get brand.
	     *
	     * @return \PDI\PDOneBundle\Entity\Brand
	     */
	    public function getBrand()
	    {
	        return $this->brand;
	    }
	}

If you wish to split this in two fixtures `Brand.yml` and `TargetBrand.yml` how would you deal with this?

**Comment by mariusz-kraj** [comment]
+1

**Comment by theofidry** [comment]
@paquitodev I would go with two fixtures files. If you start putting several entities in a file due to their relations, you'll end up with very big fixtures files very fast.

**Comment by theofidry** [comment]
Closing as this question has been answered. Just keep in mind that there is https://github.com/nelmio/alice/issues/257 which will be fixed in v3 but not before and in the meantime there is [HautelookAliceBundle](https://github.com/hautelook/AliceBundle) for mitigating this issue in Symfony (I'm not aware of any other library doing that).
