### ISSUE TITLE
Entity expects instance of X object but got array, what is wrong in fixture definition?

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#208]
I need to set 1000 territory per target and I am doing as docs said:

> Another, which is more interesting, is to define a reference with a
> wildcard, and also tell Alice how  many object you want:
> 

    Nelmio\Entity\User:
      # ...
    
    Nelmio\Entity\Group:
         group1:
             name: Admins
             owner: @user1
             members: 5x @user*

> In this case it will pick 5 fixture objects which have a name matching user*.

So my fixtures looks like this:

    \PDI\PDOneBundle\Entity\Territory:
      #100 Territory maps 1:1 against Representative
      territory{1..100}:
        name: <word()>
        description: <text()>
        district: <randomDigitNotNull()>
        inactive: <boolean(35)>
        createdAt: <dateTimeThisYear()>
        updatedAt: <dateTimeThisYear()>

    \PDI\PDOneBundle\Entity\Brand:
      # 3 Brand per Company
      brand{1..3}:
        name: <name()>
        generic_name: <name()>
        logo_url: <imageUrl(128,128)>
        description: <paragraph()>
        isi_required: <boolean(35)>
        isi_text: <realText()>
        isi_pdf_url: <url()>
        pi_required: <boolean(35)>
        pi_text: <realText()>
        pi_pdf_url: <url()>
        inactive: <boolean(35)>
        company: 3x @company*
        createdAt: <dateTimeThisYear()>
        updatedAt: <dateTimeThisYear()>
 
But when I run the set I got this error:
  

>  [Symfony\Component\Debug\Exception\ContextErrorException]   Catchable
> Fatal Error: Argument 1 passed to
> PDI\PDOneBundle\Entity\Target::setTerritory() must be an instance of
> PDI\PDOneBundle\Entity\Territory, array given, called in
> /var/www/html/magnific/reptooln_admin/vendo  
> r/nelmio/alice/src/Nelmio/Alice/Loader/Base.php on line 506 and
> defined

What is wrong in my fixtures definition?

**Comment by theofidry** [comment]
sadly you are missing an important part: `PDI\PDOneBundle\Entity\Target::setTerritory()` looks like the error occur on `Target` but I don't see any target in your fixtures.

**Comment by reypm** [comment]
loooollll almost one year from this answer hahahaha nvm I am not working on this anymore I will close this issue but anyway thanks for your reply :D

**Comment by theofidry** [comment]
Yeah need to do some cleanup ;)
