### ISSUE TITLE
How work with Doctrine\ORM\Mapping\Embedded Objects

### ISSUE THREAD

**Issue by rafreis** [nelmio/alice#209]
So I have a time worked with Doctrine\ORM\Mapping\Embedded Objects on doctrine, It's is great until now...

I'm trying to persist with alice some data on database from entities that uses some properties being Embedded Objects.

I want to know if alice support it? and if now how many time is necessary to be implemented?

**Comment by rafreis** [comment]
Just treat as a value object

**Comment by basz** [comment]
would you care you provide an example? I can't get this to work...

```
HF\Model\Embeddable\Address:
  Address{1..10}:
    street: streetName()
    city: city()
    postcode: postcode()
    country: country()

HF\Model\Entity\Authentication\User:
  user{alice, bob, jean, fred}:
    username: <current()>
    email: <current()>@example.org
    createdAt: <datetime()>
    address: @Address*
```
```
Doctrine\ORM\ORMInvalidArgumentException: The given entity of type 'HF\Model\Embeddable\Address' (HF\Model\Embeddable\Address@0000000036160d1e0000000059a32356) has no identity/no id values set. It cannot be added to the identity map.
```

**Comment by rafreis** [comment]
```
HF\Model\Entity\Authentication\User (object):
  user{alice, bob, jean, fred}:
    username: <current()>
    email: <current()>@example.org
    createdAt: <datetime()>
    address: @Address*
```

**Comment by lunetics** [comment]
Use the local flag:

HF\Model\Entity\Authentication\User (local):
  user{alice, bob, jean, fred}:
    username: <current()>
    email: <current()>@example.org
    createdAt: <datetime()>
    address: @Address*

**Comment by theofidry** [comment]
For those falling in this case again (hope not), here's the doc entry: [Reuse Generated data using objects value](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#reuse-generated-data-using-objects-value)

**Comment by blaues0cke** [comment]
@theofidry The "Reuse generated data using objects value" part is gone in the master branch. This link is working: https://github.com/nelmio/alice/blob/2.x/doc/customizing-data-generation.md

**Comment by eradionov** [comment]
seems nothing works for embeddable object
` No suitable flag parser found to handle the element "local".` error occurs
Has anyone solved issue for embeddable objects?
