### ISSUE TITLE
Bidirectional relationships not being persisted in the owning side

### ISSUE THREAD

**Issue by miguelrs** [nelmio/alice#210]
Giving a try to Alice to create fixtures for my Symfony2 project, and looks really good, but I'm having a problem, maybe a stupid one.

In my app I have Communities, which can have Users. I have these Doctrine ORM mappings:

    # Community.orm.yml
    MyApp\Bundle\MyBundle\Entity\Community:
      # ...
      oneToMany:
        users:
          targetEntity: MyApp\Bundle\MyBundle\Entity\User
          mappedBy: community

    # User.orm.yml
    MyApp\Bundle\MyBundle\Entity\User:
      # ...
      manyToOne:
        community:
          targetEntity: MyApp\Bundle\MyBundle\Entity\Community
            inversedBy: users
            joinColumn:
              name: community_id
              referencedColumnName: id

Now I'm trying to create fixtures for those entities, so I wrote this:

    MyApp\Bundle\MyBundle\Entity\User:
      user_{1..100}:
        username (unique): <username()>

    MyApp\Bundle\MyBundle\Entity\Community:
      community_{1..10}:
        name (unique): <communityName()>
        users: 6x @user_*

When I load the fixtures, it doesn't throw any error and it populates the DB, but the column `community_id` in `User` table is empty...  

If I do it the other way around (i.e., I load the communities and then I set the community on the users) it works fine, but I'd like to do it like this, because it feels more "natural" to me. And in fact if I do the equivalent approach (i.e., creating users first) when creating my objects manually without Alice and persisting them at the end, it works fine (as explained in [here][2]).

So the question is: is this possible with Alice?

Note: I tried using the normal `Fixtures::load` method and also the approach using the `Loader` and `Persister`. Also I tried to put fixtures in one and in two files, but nothing worked...

  [2]: http://stackoverflow.com/a/20033877/1813625

**Comment by Toasterson** [comment]
Same Problem here.
I'm using alice 1.7.2.

**Comment by theofidry** [comment]
I guess that's because when setting the `Community#users`, it calls the adder/setter and won't check for the other entity, so if you don't attach the `User` to `Community` in your `Community:addUser()`, it will not work.

**Comment by Toasterson** [comment]
Is this requirement mentioned in the Docs?
If it isn't I suggest adding it. Making the Relation in addEntity is only one suggested path in Symfony. Most docs I've read suggest the addition via setParentEntity Which in turn either calls addEntity or Automagically set the Parent based on DB Relations.

**Comment by theofidry** [comment]
It is not because it's not specific to this bundle neither to Symfony, if you have:

```php
class User
{
    private $community;

    public function setCommunity(Community $community)
    {
        $this->community = $community;
    }
}

class Community
{
    private $users;

    public function addUser(User $user)
    {
        $this->users[] = $user;
    }

    public function removeUser(User $user)
    {
        $this->users->removeElement($user);
    }
}

$community->addUser($user);
$manager->persist($community);
$manager->persist($user);
```

Then `$community` will have the `$user` instance attached but not the other way. So you either do:

```php
$community->addUser($user);
$user->setCommunity($community);
$manager->persist($community);
$manager->persist($user);
```

If you want to do it in one go you have to add some logic:

```
class Community
{
    private $users;

    public function addUser(User $user)
    {
        $this->users[] = $user;
        $user->setCommunity($this); 
    }

    public function removeUser(User $user)
    {
        $this->users->removeElement($user);
        $user->setCommunity(null);
    }
}
```

That's the gist of it.

**Comment by theofidry** [comment]
Closing as as explained, this is out of the scope of alice.
