### ISSUE TITLE
Get different references for a set of fixtures

### ISSUE THREAD

**Issue by miguelrs** [nelmio/alice#212]
Let's say I have this fixture for `Community` entities:

    MyApp\Bundle\MyBundle\Entity\Community:

        community{1..10}:
            name (unique): <communityName()>

And also I have this fixtures for `User` entities:

    MyApp\Bundle\MyBundle\Entity\Entity:

        baseUser (template):
            userName (unique): <username()>

        newbieUser{1..5} (extends baseUser):
            experience: <numberBetween(1, 999)
            community: @communtiy*

        expertUser{1..5} (extends baseUser):
            experience: <numberBetween(1000, 99999)
            community: @communtiy*

        moderator{1..5} (extends baseUser):
            experience: <numberBetween(100000, 999999)
            community: @communtiy*

The point is that I want Communities to have 0 or 1 moderators, 0 or 1 expert users and 0 or 1 newbie users, and with that code, many moderators/experts/newbies may be assigned to the same community.

If I use `community (unique):` it will try to find a different community for every user, so as I have 15 users and 10 communities, it will end up throwing an error, because it cannot find any more communities...

I know I can manually create all users 1 by 1 and assign it to the correct communities, but that's not so handy... I'm also thinking that maybe I can create a provider like `<uniqueCommunityForUserType()>` that somehow gives you a unique community for each user type, but that, if it's feasible, is a bit of a pain as well...

**Comment by tshelburne** [comment]
Personally, I handle these kinds of really specific (almost domain-like) cases outside of the loader script, as a kind of "follow-up" task once I've created my basic entities. It works well in my system, but I understand it feels less "clean". 

If you don't want to approach it in that way, I think a provider is probably a good bet. Anytime there's specific conditional logic needed, I reach in that direction.

**Comment by miguelrs** [comment]
Thanks for your comment @tshelburne. As for creating those entities separately, I don't like it too much, I'd rather define each user fixture individually anyway...

As for the provider approach, actually I've been giving it a try, but I can't figure out how to do it...
Let's say I create the provider function `communityWithoutUserType($userType)` to give me a random community that has not the given user type yet, so I make sure communities have at most 1 user of a given type...
From that function I need to get the communities that has been created so far, which is ok, but I also need to know which users have been already assigned to those communities, which is what I don't know how to do... because at that moment, users have not been persisted!
So the only option I see is to create a kind of in-memory array of communities with users and populate it within that function, so I can check what has been created so far every time I call that function... but that's really ugly... 

Can you suggest anything? Thanks in advance ;)

**Comment by miguelrs** [comment]
Thanks for your comment @tshelburne. As for creating those entities separately, I don't like it too much, I'd rather define each user fixture individually anyway...

As for the provider approach, actually I've been giving it a try, but I can't figure out how to do it...
Let's say I create the provider function communityWithoutUserType($userType) to give me a random community that has not the given user type yet, so I make sure communities have at most 1 user of a given type...
From that function I need to get the communities that has been created so far, which is ok, but I also need to know which users have been already assigned to those communities, which is what I don't know how to do... because at that moment, users have not been persisted!
So the only option I see is to create a kind of in-memory array of communities with users and populate it within that function, so I can check what has been created so far every time I call that function... but that's really ugly...

Can you suggest anything? Thanks in advance ;)

**Comment by miguelrs** [comment]
I ended up creating this provider function, which returns a random `Community` that does not contain the given `UserType`, by using the references contained in the `$loader` object so far:

    public function communityWithoutUserType(UserType $userType)
    {
        $communities = new ArrayCollection();
        foreach ($this->loader->getReferences() as $ref => $entity) {
            
            // Populate the array of communities
            // Note: communities will always appear earlier in the array of references, because they were loaded first, otherwise we'd need 2 independent loops
            if ($entity instanceof Community) {
                $communities->add($entity);
            }

            // Once array of existing communities is populated, remove those that contain the given UserType
            if ($entity instanceof UserEntity && $entity->getUserType() == $userType) {
                $communities->removeElement($entity->getCommunity());
            }
        }

        // Eventually return a random item in the array, which contains only those communities without the given user type
        return $communities->get(array_rand($communities->toArray()));
    }
