### ISSUE TITLE
No setters, no party...

### ISSUE THREAD

**Issue by miguelrs** [nelmio/alice#214]
Trying Alice in a project where I'm exploring a Domain Driven Design approach, where I want to remove all setters from my Entities, and have constructor arguments instead.
The issue I have is that, although Alice can actually handle constructor arguments, with this approach you lose most of the interesting stuff - variables, inheritance, uniqueness, etc...

I was thinking of an approach where I could define the fixtures in yaml as if the entities had setters, and then create my own `Instantiator` classes, where I could get the properties from the `Fixture` and call the constructor with the arguments... But after some tries, I cannot make it working...

So the question is, am I right that without setters you lose most the stuff? 
And do you think that my approach of custom instantiators may work? Or any other approach where I can define the fixtures "with setters" and then create my objects through constructors?

**Comment by staabm** [comment]
do you say that you are using public properties instead of setters and this doesnt work? Or how do you fill your objects (from your regular app point of view)?
Or do you pass "everything" by __construct() and work with immutable objects in your model?

**Comment by miguelrs** [comment]
@staabm Sorry if that was unclear. I mean I have only private properties in my entities, and I pass all the data I need into the constructor and work with immutable entities.

**Comment by miguelrs** [comment]
Actually, after spending quite a while trying things, I realised that the solution was much easier...
Just by adding the option `__construct: false` to the fixture, the constructor won't be called, and a reflection class approach will be taken to create the instances, which seems to be working now so far...

**Comment by theofidry** [comment]
Hi please refrain from commenting issues 7 years old. If you have issues/questions open a new one. If the discussion is relevant you can always link to the old issue.
