### ISSUE TITLE
Error when using a field with a keyword for it's name

### ISSUE THREAD

**Issue by arianmaykon** [nelmio/alice#217]
When mapping a fixture like the below:
```
My\Namespace\People:
    people1:
        name: Foo bar
        order: 56
```

the following error is shown
```
An exception occurred while executing 'INSERT INTO peoples (name, order) VALUES (?, ?)' with params ["Foo bar", 56]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order) VALUES ('Foo bar', ' at line 1 (Doctrine\DBAL\Exception\SyntaxErrorException)
```

(i took some error example from my code and adapted it to post here)

Anyway, i`m not sure if is the Nelmio\Alice or if its the Doctrine that is not quoting the fields. In this example, order is a reserverd keyword (MySQL).

**Comment by theofidry** [comment]
I see nothing wrong on alice side: the fixture is properly generated with the right values. The issue clearly comes from Doctrine in this case.

**Comment by henry-geronimo** [comment]
Maybe too late, but it was simply because order is a reserved keywords in SQL , you have to rename your column name in annotation like this.

`
    /**
     * @var int
     *
     * @ORM\Column(name="`order`", type="integer")
     */
    private $order;
`
