### ISSUE TITLE
Make object reference exact number of objects

### ISSUE THREAD

**Issue by umpirsky** [nelmio/alice#219]
Here is an example:

```yml
Nelmio\Entity\Group:
    group{1..5}:
        name: group <current()>

Nelmio\Entity\User:
    user{1..50}:
    group: @group*
    name: user <current()>
```

In this case each group will have ~10 users. 

I would like to make it be exact 10.

So I tried:

```yml
Nelmio\Entity\Group:
    group{1..5}:
        name: group <current()>
        users: 10x @user*

Nelmio\Entity\User:
    user{1..50}:
    name: user <current()>
```

And it works, but the problem with this approach is that some users are left without group (group is null).

Is there any way around this?

**Comment by cmfcmf** [comment]
I think something like this should work:
```yml
Nelmio\Entity\Group:
    group{1..5}:
        name: group <current()>

Nelmio\Entity\User:
    user{0..49}:
    group: <identity(current() / 10 + 1)>
    name: user <current()>
```
I haven't tested it, but you might need a cast to int inside the identity call.

**Comment by umpirsky** [comment]
@cmfcmf It throws:

```
[Symfony\Component\Debug\Exception\ContextErrorException]  
Warning: current() expects exactly 1 parameter, 0 given
```

Thanks.

**Comment by Seldaek** [comment]
IIRC You need the `<>` around current() In the identity call as well
otherwise it just sees it as PHP.

**Comment by umpirsky** [comment]
@Seldaek Parse error in that case:

```
Parse error: syntax error, unexpected '<' in vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php(653) : eval()'d code on line 1
```

Thanks.

**Comment by Seldaek** [comment]
@umpirsky are you using 2.0?

**Comment by umpirsky** [comment]
@Seldaek No, using hautelook/alice-bundle with nelmio/alice v1.7.

**Comment by Seldaek** [comment]
Ah ha.. Ok sorry I'm a bit rusty here didn't use alice in a while, but this will work in 2.0 at least, not sure about 1.* `@<(round($fake('current') / 10 + 1))>`.

If it fails with 1.* I would ping the bundle author about maybe adding alice 2 support, the base interface didn't change so much so it should be easy enough.

**Comment by umpirsky** [comment]
@Seldaek It fails with 1.7. Already pinged bundle author. Will post feedback when I test it with 2.0.

Thanks a lot!

**Comment by theofidry** [comment]
Closing this issue as it's an old one and has been fixed in v2.
