### ISSUE TITLE
Differentiate Processor and ProcessorInterface

### ISSUE THREAD

**Issue by MichaelMackus** [nelmio/alice#222]
I found it quite confusing that there is a base Processor class (with no interface) and also a ProcessorInterface that has (seemingly) no relation to the main Processor.

Maybe we should clarify this difference with naming, and perhaps introduce an interface for the main Processor?

**Comment by theofidry** [comment]
+1

**Comment by theofidry** [comment]
This will be changed for sure in v3. Meanwhile an interface or simply some php doc would be welcome.
