### ISSUE TITLE
Persisting relations

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#230]
When used with Doctrine and the version 2.0, I get the following error:

```
Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'AppBundle\Entity\Product#brand' that was not configured to cascade persist operations for entity...
```

I've simply have an entity which has a reference to the other one. The relation is bidirectional. Is `Fixtures::load()` supposed to handle this case natively?

**Comment by bigfoot90** [comment]
@theofidry
You have to use the cascade persist
 http://doctrine-orm.readthedocs.org/en/latest/reference/working-with-associations.html#transitive-persistence-cascade-operations.

**Comment by theofidry** [comment]
Yeah but it comes from a unit test which was passing with the previous version of this library. The mapping definitely not changed, hence my question.

**Comment by reasn** [comment]
can confirm this error.

**Comment by theofidry** [comment]
Sadly I can't remember where I had this issue... Unless someone still has the problem and manages to reproduce it, I'm going to close this one.

**Comment by placid2000** [comment]
Hi, this might not really be relevant but I just want to share the information.
 
I'm getting the error 

> "A new entity was found through the relationship 'AppBundle\Entity\User#language' that was not configured to cascade persist operations"

 by loading two fixture files
`$loader = $container->get('fidry_alice_data_fixtures.doctrine.persister_loader');` 
` $loader->load([$fixturesDir . 'first.yml', $fixturesDir . 'second.yml']);` 

And having the Language Entity defined one time in first.yml and one time in second.yml

**Comment by theofidry** [comment]
@placid2000 I think https://github.com/theofidry/AliceDataFixtures/pull/52 would solve the issue. But open the issue on FidryAliceDataFixtures rather please :) This issue was about alice 2.x
