### ISSUE TITLE
Make (Faker) string parsing and processing available to the user

### ISSUE THREAD

**Issue by sveneisenschmidt** [nelmio/alice#233]
Hello,

the idea is a really simple one but could lead to Faker support through Alice in third party libraries based on the internal string parser of Alice.

Initial idea: Make Alice’s Faker invocation based on strings public, through a static method or a new class.

Now:
https://github.com/sveneisenschmidt/alice-faker-standalone-example
```php
use \Nelmio\Alice\Instances\Processor\Processable;
use \Nelmio\Alice\Instances\Processor\Methods\Faker;

$processable = new Processable('<numberBetween(1, 99)>');
$method = new Faker($providers = []);
$result  = $method->process($processable, $variables = []);

print sprintf('Result: %s %s', $result , PHP_EOL);
// Result: 23
```

Goal:
https://twitter.com/seldaek/status/620533611125698560
```php

$result = Nelmio\Alice\Faker::process("<numberBetween(1, 99)>");
print sprintf('Result: %s %s', $result , PHP_EOL);
// Result: 87
```

The development could be easily done for version 1.x and 2.x.

I would favor a new class, maybe in a separate Util namespace, instead of adding a static method to the Faker class. I have no idea about the current development of Alice so maybe there will be support for more fake data provider that need a different syntax?

What do you think?

Cheers
Sven

**Comment by Seldaek** [comment]
I think this can go in 2.x-only, and yes it probably should be a standalone util class, I just didn't have much room in that tweet ;)

The question is should there be any easy way to pass in custom providers as well, or variables, etc. I think we need to define a good simple high level API that allows most use cases and then if people want more they can always do it themselves with the lower level API.

**Comment by sveneisenschmidt** [comment]
Thank you for the reply. Okay, 2.x is fine. :)

Draft without variables:

```php
$processor = Nelmio\Alice\Util\Processor\FakerFactory::create($providers = []);
$result = $processor->process("<numberBetween(1, 99)>");
```

Would there be a need for variables and how would variables look in that context. Do you have an example?

**Comment by Seldaek** [comment]
Maybe pass optional variables array in process()

It might let you inject values that are usable inside the faker call as 
$foo, but not sure how easy it is to achieve this so if it's not 
workable whatever I guess.

**Comment by sveneisenschmidt** [comment]
So we would pass it through directly to the original process call.
https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Instances/Processor/Methods/Faker.php#L114

```php
$variables = ['key' => 'value'];
$processor = Nelmio\Alice\Util\Processor\FakerFactory::create($providers = []);
$result = $processor->process("<numberBetween(1, 99)>", $variables);
```

I am still not sure if it would be a good practice to create a new Processable every time we call process. Although this is how the original example from me works.

We have to think of a second class that is returned by FakerFactory that holds the actual Faker instance with all registered providers and implements the process method and like I said would transform the string input to a new Processable that can be passed to the native process method.

**Comment by theofidry** [comment]
This is now possible by using the Expression Language Parser (`NativeLoader:: getBuiltInExpressionLanguageParser()` or the `nelmio_alice.fixture_builder.expression_language.parser` service).
