### ISSUE TITLE
Create 1.7.3 version for Base::populateObject() __call test

### ISSUE THREAD

**Issue by steevanb** [nelmio/alice#235]
Hi,

In `Nelmio\Alice\Loader\Base::populateObject()`, a new test for `__call` method is added in 1.7@dev version. But in last 1.7 version (1.7.2), this add doesn't exists.

So, could you create a 1.7.3, with this ?
Cause in production environment, i don't want to have `@dev`, but a fixed version (like 1.7.*).

Thanks !

**Comment by theofidry** [comment]
Closing this issue as it's a very old one and v2 has been out for over a year now as well.
