### ISSUE TITLE
Unstable release 

### ISSUE THREAD

**Issue by hbakhtiyor** [nelmio/alice#237]
latest release version comes with [this bug](https://github.com/nelmio/alice/pull/220) and since don't have any releases.

**Comment by tshelburne** [comment]
@Seldaek Good for a patch release?

**Comment by Seldaek** [comment]
Anytime, feel free :) I'd just be happy if the changelog is kept up to date with whatever changes go in a given release, but otherwise do it as often as you'd like really.

**Comment by theofidry** [comment]
Any update?

**Comment by oldskool** [comment]
I would also appreciate a new release for exactly this bugfix. :smile:

**Comment by Seldaek** [comment]
Tagged 2.1

**Comment by theofidry** [comment]
Thaaaanks :dancer:
