### ISSUE TITLE
Add ability to make multiple properties a composite unique

### ISSUE THREAD

**Issue by mikehaas763** [nelmio/alice#24]
Right now, I have a table with a composite primary key. When I load my fixtures I get: "Couldn't generate random unique value for Entity\FormulaColor: color in 128 tries."

The reason I have a join table as an Entity is because the many-to-many relationship also houses a 3rd piece of information. A percentage.

In any case, a composite PK would be nice to have.

EDIT

I was thinking something along this kind of syntax:

Entity\Car
    brand (composite): Ford
    model (composite): Taurus
    year (composite): 1999

**Comment by briancappello** [comment]
+1 for this feature

**Comment by Max101** [comment]
:+1: This would be nice!

**Comment by abguy** [comment]
I need it too.

**Comment by theofidry** [comment]
+1

**Comment by thundo** [comment]
Any update on composite primay keys? Thanks

**Comment by bigfoot90** [comment]
+1 for parsing Doctrine's annotaions

**Comment by vnenkpet** [comment]
+1

**Comment by rbaarsma** [comment]
+1

**Comment by lunetics** [comment]
+1

**Comment by reinfi** [comment]
+1

**Comment by jamesfade** [comment]
+1

**Comment by theofidry** [comment]
For those interested, you can create a custom provider generating your PK based on the 3 generated values:

```
Entity\Car:
  car_with_composite_key:
    brand: Ford
    model: Taurus
    year: 1999
    id: <generateCarKey($brand, $model, $year)>
```

This is also very unlikely to be implemented in v3 as the persistence layer will be removed from it.

I'm closing this issue. If there is still questions please open a new issue to avoid spamming everyone as this is a fairly old topic.
