### ISSUE TITLE
Inconsistant interface for PersisterInterface::find() when no result found

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#244]
The [`Nelmio\Alice\Persister\PersisterInterface::load()`](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/PersisterInterface.php#L30) is very unclear about the result return. It is used only in two places:
* for the doctrine bridge: [`Nelmio\Alice\Persister\Doctrine::load()`](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Persister/Doctrine.php#L48) which throws an `\UnexpectedValueException` exception when no result is found
* [`Nelmio\Alice\TestPersister`](https://github.com/nelmio/alice/blob/master/tests/Nelmio/Alice/TestPersister.php#L33) which suggest it returns null when no result is found

As a Doctrine user, I feel more right to return `null` when no  result is found but throwing an error makes sense too. But it would be better to make a choice on this.

**Comment by tshelburne** [comment]
I agree with null.

**Comment by theofidry** [comment]
Ok I'll do a PR to reflect on that then :)

**Comment by theofidry** [comment]
Follow up in #245.
