### ISSUE TITLE
Data 'pool'?

### ISSUE THREAD

**Issue by appeltaert** [nelmio/alice#250]
As an addition to https://github.com/nelmio/alice/issues/249.

Is it possible to have some sort of data pools where you have a collection of long/latitude strings, or a fixed combination of fields that form a complete address that can be assigned to multiple fields?

Only way i can think of is a [data provider](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers). Passing on the current() of the iteration to index which fields were handed out to which entity could potentially be a solution .

Is that the right way?

**Comment by theofidry** [comment]
Very old issue, but yeah using a data provider is the right way to handle such cases.
