### ISSUE TITLE
Add current() in identity() support

### ISSUE THREAD

**Issue by tshelburne** [nelmio/alice#273]
This was added in #195 for the 1.x branch, but we need it for master.

**Comment by fschaeffer** [comment]
+1 as some Symfony Bundles refer to nelmio 2.x since some time and we can't update them due to this missing feature.

Is it hard to port this to 2.x? Has the syntax / functionality changed so much, that the (small) changes made in the 1.x-branch are not portable? Otherwise I would give it a try ...

**Comment by tshelburne** [comment]
All of it should be pretty straightforward - the original 2.0 was mostly just moving code that was all in a single class into smaller, manageable chunks. I wouldn't anticipate it being hard, it's just more than I have time to contribute right now.

**Comment by Einenlum** [comment]
:+1:

**Comment by theofidry** [comment]
AFAIK has been aded now.

**Comment by BrummbQ** [comment]
@theofidry Doesn't work for me. Can you show me an example?

**Comment by theofidry** [comment]
It is mentioned [in the doc](https://github.com/nelmio/alice/blob/3bf8e6f9cabb4f7d06d0c0d8f715ceb4b41d19c9/doc/customizing-data-generation.md#default-providers) and I also see a [test for it](https://github.com/nelmio/alice/blob/3bf8e6f9cabb4f7d06d0c0d8f715ceb4b41d19c9/tests/Nelmio/Alice/Fixtures/LoaderTest.php#L737-L753).

But I didn't try to use to be fair so I may be wrong.
