### ISSUE TITLE
Cannot define unique constraint on multiple properties / constructor.

### ISSUE THREAD

**Issue by tomazahlin** [nelmio/alice#275]
For example I have this entity:

```yaml
Project\Bundle\UserBundle\Entity\Sport:
    sport_{1..500}:
        __construct: [@user_*, < constant('sports') >]
```

But the user is not allowed to have the same sport in the database twice. I tried using the (unique) constraint like this __construct (unique): ..., but it does not work. I get this exception which makes no sense:

```
[RuntimeException]
  You must specify a __construct method with its arguments in object 'sport_1' since class 'Singles\Bundle\UserBundle\Entity\Sport' has mandatory constructor arguments
```

Can I get some help how to solve this? The application code works and I don't feel like it is the right way to modify application code in order to populate the fixtures.

**Comment by tomazahlin** [comment]
Due to no support and poor flexibility, I have removed this bundle from my project. I now use Doctrine Fixtures Bundle, with which I can cover all possibilities. I think everyone should take this in consideration when using Alice - don't get me wrong, Alice is nice, but still in early development imho. When you have more complex database to fill in, it becomes impossible to do so with Alice. Regards.

**Comment by Seldaek** [comment]
Don't get me wrong, but stuff doesn't usually get done unless someone that
needs it chips in the time to do it. Alice is made to be a simple and way
easier replacement of doctrine fixtures. Sure that can't cover all use
cases without some amount of work, and I think that's ok.

Everything can't do everything.

**Comment by theofidry** [comment]
>Don't get me wrong, but stuff doesn't usually get done unless someone that
needs it chips in the time to do it. Alice is made to be a simple and way
easier replacement of doctrine fixtures. Sure that can't cover all use
cases without some amount of work, and I think that's ok.

I cant' express any better my feelings, although there *is* some nice features that should be added.

FIY @tomazahlin you can also return PHP files so what you can achieve with DoctrineFixturesBundle can be achieved with Alice. That being said, with Symfony there's a bundle for everything, and yeah, there's one for Alice! It's called [HautelookAliceBundle](https://github.com/hautelook/AliceBundle) that might prove to be an  good alternative, and far more active than DoctrineFixturesBundle ;)

**Comment by theofidry** [comment]
Closing in favour of #387
