### ISSUE TITLE
Add possibility to inject Collection instance as $objects field at Loader constructor

### ISSUE THREAD

**Issue by velosipedist** [nelmio/alice#285]
Now objects just assigned to `$objects` field [here](https://github.com/nelmio/alice/blob/e4b48d08ac935650747a2f3041c3577a4bed443d/src/Nelmio/Alice/Fixtures/Loader.php#L91) and then injected to processor and populator.

The problem i trying to solve is to make objects collection able to find Yii 1 objects with magic properties (any [CComponent](https://github.com/yiisoft/yii/blob/master/framework/base/CComponent.php#L107) descendants). Bundled Collection checks for field or getter, and throws exception on fail.

The easiest solution i found is to substitute that collection object with descendant class redefining `find()` method.

I also suspect this issue is good enough occasion to consider utilizing some kind of DI container, for easy Alice tuning at future.

**Comment by theofidry** [comment]
I tagged thinking this could be a thing to watch for in 3.x, however objects can be injected when loading a file or data (both in 2.x and 3.x) and I'm not sure to really see the use case of having something more.

As it's a fairly old issue, I prefer to leave it as that. If you or someone still feel about it, please open a new issue to have a fresh discussion on that topic.
