### ISSUE TITLE
Custom stack produces error

### ISSUE THREAD

**Issue by mikejw** [nelmio/alice#288]
I'm trying to use alice within a custom MVC stack (all open source code) and I'm having issues when attempting to introduce foreign keys/references.

This is the fixture code:

ESuite\FakeEntity:
  detail{1..10}:
    name: <firstName()>
    age: <randomDigit()>
    stamp: 'MYSQLTIME'
    empty: <randomDigit()>
    foo: 'DEFAULT'

ESuite\FakeRelatedEntity:
  detail{1..10}:
    fake_id: @fakeentity<current()>
    name: <firstName()>

When the second block is uncommented I'm getting this error:

UnexpectedValueException: Could not determine how to assign age to a ESuite\FakeEntity object (in Nelmio/Alice/Instances/Populator/Populator.php).

Can anyone shed some light on why the original fixture generation breaks upon trying to introduce references.  I appreciate that I may not be setting up the correct "middleware" properly (the object manager etc) to understand how to tun fake_id into the foreign key yet. i.e. through mysql insert id.

The code can be checked out here:

https://github.com/mikejw/empathy - using the 'dbtests' branch and running the tests with:

cd ./t/
./run_tests.sh

**Comment by tshelburne** [comment]
Without digging into your code, I can suggest quickly that you are probably looking at a [custom populator](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Instances/Populator/Methods/MethodInterface.php). There are a few base-level assumptions that Alice makes about how you might populate properties on your objects, but there are often instances where the defaults don't cover every situation.

A populator is little more than a strategy to set a property according to the value set in the fixture file. If you [register a new populator method](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Fixtures/Loader.php#L239) with the loader before loading your fixtures, it will be given preference over the defaults.

**Comment by mikejw** [comment]
Nice one, thanks. I'll take a look.

**Comment by mikejw** [comment]
Will the populator need to extend the default populator as well as implement that interface.  If so then I will need to pass it a collection.  But I'm not sure what that's supposed to be initialised with..

**Comment by mikejw** [comment]
This seems to be working.  I can now see the entity being assigned each property value however the persist method on my object manager (which is now implementing the PersisterInterface) doesn't appear to get called.

**Comment by tshelburne** [comment]
Yea, that's one of the things we are trying to improve for v3.0 (completely unspec'd). When you are using the `Loader` directly, persistence isn't called automatically. The library took a big turn at the release of 2.0, and there are some vestigial parts that are a bit confusing. You basically will need to loop through your objects and persist them manually - at least, that's the way I handle it in the project I use Alice for.

**Comment by mikejw** [comment]
Thanks @tshelburne this seems to producing a more robust approach. However I'm now getting the error Instance fakeentity1 is not defined.  Do I need to manually keep track of previously loaded objects within the populator somehow so I can marry up the related objects?

**Comment by tshelburne** [comment]
Can you copy in more details? Not seeing `fakeentity1` anywhere in the code above.

**Comment by mikejw** [comment]
fakeentity is where I'm referencing the original persisted objects as per the documentation for relations. (In the second block of fixture code.) 

See https://github.com/mikejw/empathy/blob/dbtests/t/fixtures/fixtures3.yml

**Comment by tshelburne** [comment]
Ah - you are creating entities named `detail1`-10 - you need to set it to `fakeentity{1-10}`

**Comment by mikejw** [comment]
Aha.. makes sense!  Thanks man.

**Comment by tshelburne** [comment]
No problem! Closing, let me know if anything else.

**Comment by mikejw** [comment]
the only thing I'm wondering now is how to create a mechanism that ensures each block of fixtures is persisted individually to ensure the ids for each record are available for the relations to use later but I imagine this is an issue that needs it's own implementation thought out for the custom persister?

**Comment by mikejw** [comment]
..unless I switch to using guids

**Comment by tshelburne** [comment]
Yea, that basically entirely depends on your persistence mechanism. If you are using an ORM, generally those things are taken care of.

**Comment by mikejw** [comment]
I managed to do that with my own simple ORM using the following few lines of code (inside the persister)

<code>

            $props = $object->getProperties();
            foreach ($props as $p) {
                if (is_object($object->$p)) {
                    $object->$p = $object->$p->id;
                }
            }
</code>

**Comment by mikejw** [comment]
Now I want to try it with RedBean ORM  :)
