### ISSUE TITLE
Possible to override model instantiation?

### ISSUE THREAD

**Issue by mikejw** [nelmio/alice#289]
Is it possible to use an alias for the start of each fixture block (that is handled by some code that instantiates a model) instead of referencing a model class directly?

**Comment by theofidry** [comment]
You mean somehow declaring somewhere `\My\Long\Namespace\Dummy` has an alias `dummy` and then you could do:

```yaml
dummy:
  d{0..100}:
    # ...
```

? If so I would better not. It would only create confusion IMO for no real gain.
