### ISSUE TITLE
Password generator can generate password matched with Reference processor method

### ISSUE THREAD

**Issue by lehovec** [nelmio/alice#294]
I generated users with \<password()\> generator. One user gain password @vHTJVryk63d. This password matched with Reference processor method regular expression in canProcess method and it throws error:
```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Instance vHTJVryk63d is not defined' in /my-project/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Collection.php:133
```
Please edit password generator for generate password that cannot be matched with Reference regex.

**Comment by theofidry** [comment]
Closing as is a duplicate of #176
