### ISSUE TITLE
Couldn't generate random unique value for "value" in 128 tries.

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#300]
I am defining this fixture:

    Clanmovil\PlatformBundle\Entity\Alias:
        alias_{1..500}:
            name (unique): Alias_<numberBetween(1, 500)>
            description: <text(150)>
            active: <boolean(31)>
            createdAt: <dateTimeThisYear()>
            updatedAt: <dateTimeThisYear()>

And I am getting this error at console:

> [RuntimeException]
>   Couldn't generate random unique value for Clanmovil\PlatformBundle\Entity\Alias: name in 128 tries.

I did a little research through this error on sources at bundle but isn't clear to me what the issue could be. What is wrong here? How do I act when I found a issue like this one?

If this help this is how the entity looks like:

    namespace Clanmovil\PlatformBundle\Entity;

    use Doctrine\ORM\Mapping as ORM;
    use Clanmovil\PlatformBundle\Model\IdentifierAutogeneratedTrait;
    use Symfony\Component\Validator\Constraints as Assert;
    use Gedmo\Timestampable\Traits\TimestampableEntity;

    /**
     * @ORM\Entity
     * @ORM\Table(name="cm_alias",
     *      uniqueConstraints={@ORM\UniqueConstraint(name="name", columns={"name"})},
            indexes={@ORM\Index(name="fulltext_idx",
                columns={"name"},
                flags={"fulltext"})})
     * )
     */
    class Alias
    {
        use IdentifierAutogeneratedTrait;
        use TimestampableEntity;

        /**
         * @var string
         * @ORM\Column(type="string", length=150)
         * @Assert\NotBlank()
         */
        protected $name;

        /**
         * @var string
         * @ORM\Column(type="text", nullable=true)
         */
        protected $description;

        /**
         * @var bool
         * @ORM\Column(type="boolean")
         */
        protected $active = true;

        /**
         * @ORM\ManyToMany(targetEntity="Command", mappedBy="command_alias", cascade={"persist"})
         */
        protected $alias_command;

        /**
         * Set name.
         *
         * @param string $name
         * @return Alias
         */
        public function setName($name)
        {
            $this->name = $name;

            return $this;
        }

        /**
         * Get name.
         *
         * @return string
         */
        public function getName()
        {
            return $this->name;
        }

        /**
         * Set description.
         *
         * @param string $description
         *
         * @return Alias
         */
        public function setDescription($description)
        {
            $this->description = $description;

            return $this;
        }

        /**
         * Get description.
         *
         * @return string
         */
        public function getDescription()
        {
            return $this->description;
        }

        /**
         * Set active.
         *
         * @param bool $active
         *
         * @return Category
         */
        public function setActive($active)
        {
            $this->active = $active;

            return $this;
        }

        /**
         * Get active.
         *
         * @return bool
         */
        public function getActive()
        {
            return $this->active;
        }

        /**
         * Get command for alias
         *
         * @return string
         */
        public function getAliasCommand()
        {
            return $this->alias_command;
        }

        public function __toString()
        {
            return $this->name;
        }

    }

**Comment by tshelburne** [comment]
You are creating 500 entities, and requiring a unique value between 1 and 500 for the name. That unique value is being generated randomly. So everything is fine for the first X entities created, but eventually the pool of remaining numbers to randomly select from is too small to reliably get one in 128 tries. For example, if you have created 499 entities successfully, the chance you will hit the one remaining number successfully in 128 tries is very low.

Closing because this isn't a problem with the library, you just need to either a) set `name: <current()>` or b) use a much larger sampling pool (I personally use 10000).
