### ISSUE TITLE
Wrong interface in Fixtures::__construct() $persister parameter

### ISSUE THREAD

**Issue by ma-si** [nelmio/alice#302]
Catchable fatal error: Argument 1 passed to Nelmio\Alice\Fixtures::__construct() must be an instance of Nelmio\Alice\PersisterInterface, instance of Doctrine\ORM\EntityManager given

Constructor parameter implements PersisterInterface but in a load() is a switch PersisterInterface / ObjectManager

**Comment by knugen** [comment]
You can pass in `new Doctrine($entityManager)` if you want to instantiate the Fixtures object directly, but yes I agree that they should be consistent.

**Comment by theofidry** [comment]
Would be great to be consistent but sometimes not introducing a BC break is more important :/ @ma-si are you still having problems with it?

**Comment by theofidry** [comment]
Closing as it's an old issue and this can't be fixed in v2 as it would introduce a BC break.
