### ISSUE TITLE
Un-named records in different entities throws 'unable to assign property' error

### ISSUE THREAD

**Issue by kyaw-myo-thein** [nelmio/alice#306]
I think the bug is best explained by example.

``` yml
Entity\Employee:
  - 
    name: John    
Entity\Role:
  - 
    title: Supervisor  
```

The yml file throws error saying 'Could not determine how to assign ```name``` to a ```Entity\Employee``` object. Found in v2.1.0.

**Debugging Info** 
I found out that the first object without name (i.e. with dash for ```Employee```) is overwritten by latter object without name (i.e. with dash for ```Role```) due to using index 0 in array in [here](https://github.com/nelmio/alice/blob/d0973384dfb7516cb116f36a14dbbea592b9757f/src/Nelmio/Alice/Fixtures/Loader.php#L283). So, when we retrieve object for ```Employee``` with index 0, ```Role``` object is mistakenly returned in [here](https://github.com/nelmio/alice/blob/d0973384dfb7516cb116f36a14dbbea592b9757f/src/Nelmio/Alice/Instances/Populator/Populator.php#L70)

**Workaround**
I've been naming each object to avoid objects being overwritten as below. 

example.yml
``` yml
Entity\Employee:
  employee_john: 
    name: John    
Entity\Role:
  role_supervisor:
    title: Supervisor  
```

**Comment by tshelburne** [comment]
@kyaw-myo-thein The intention is basically to *always* use named entities - I honestly wasn't even aware you could run the library without naming them. 

@Seldaek  IMO this isn't a problem with the library, just a misuse. Thoughts?

**Comment by kyaw-myo-thein** [comment]
I'll close the ticket because using object without name is never intended in the first place. 

@tshelburne thanks for your feedback.
