### ISSUE TITLE
Q: Assign ROLE to group on Nelmio Alice fixtures

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#311]
I am using Nelmio Alice with [hautelook/AliceBundle][3] and I am trying to configure a fixtures for FOSUser [Group entity][1] but I have a doubt regarding this. See my definition below:

    PlatformAdminBundle\Entity\Group:
        group{Admin,Chat,Executive,Report}:
            __construct: [<current()>]

The fixture above works as should be. But Each group has its own `role` as shown below: 

    `Admin => ROLE_SUPERADMIN`
    `Chat => ROLE_CHAT`
    `Executive => ROLE_EXECUTIVE`
    `Report => ROLE_REPORT`

 How do I assign each role to its group? Any advice?

 [1]: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Model/Group.php
 [3]: https://github.com/hautelook/AliceBundle

**Comment by tshelburne** [comment]
I would recommend creating a template for the group entity, and then having a fixture for each of the defined types with only the role set. Alternatively, you could set up your own Faker function or handle the objects manually after generation, and persist manually.

**Comment by reypm** [comment]
@tshelburne  I like the second choice more than the first one but hasn't idea how the faker should be could you give me a little example? Just for see what is on your mind? Thanks in advance

**Comment by tshelburne** [comment]
Check out [the doc on custom faker generation](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md) - I'm not entirely sure how it would work on the surface, but I definitely think that's the place to start looking. There are several entrypoints into the library if you start going the custom route, so it may be that you need a custom processor or something instead.

**Comment by reypm** [comment]
@tshelburne I am not asking about Faker Generation since I know how to do it and register as a service. What I am talking is about the logic for what you said on the second idea, that's my doubt.

**Comment by tshelburne** [comment]
Ah, I meant something along the lines of the following:

```php
// load objects from a yaml file
$loader = new \Nelmio\Alice\Fixtures\Loader();
$groups = $loader->load(__DIR__.'/groups.yml');
foreach ($groups as $name => $group) {
  $group->role = // logic to turn $name into the role constant;
}

$persister = new \Nelmio\Alice\Persister\Doctrine($objectManager);
$persister->persist($groups);
```

For the record, unless you have a ton of different kinds of roles, I would shy away from this approach - the explicit one might be a bit more verbose, but it's much more clear what is happening.

**Comment by reypm** [comment]
@tshelburne so you said better goes through template way rather than this way? Is that what you said?

**Comment by theofidry** [comment]
@reypm give me five I've got an example for ya

**Comment by reypm** [comment]
@theofidry thanks, I am waiting no proble

**Comment by tshelburne** [comment]
@reypm I personally would go with the template fixtures approach, but @theofidry might have a great idea :)

**Comment by theofidry** [comment]
On Symfony roles are accessible via `%security.role_hierarchy.roles%` (in YAML). The only issues is that you get the array with the whole hierarchy which may not be what you want.

I've got [this utility class](https://github.com/in6pio/Incipio/blob/master/src/ApiBundle/Utils/UserRoles.php) that flattens those roles. Then you can have a simple [faker provider](https://github.com/in6pio/Incipio/blob/master/src/ApiBundle/DataFixtures/Faker/Provider/UserProvider.php#L47-L50) for it.

It's an old project so there is definitely rooms for improvement (or at least I would completely rewrite it), but it may be a good start for you.

**Comment by theofidry** [comment]
@tshelburne yeah nothing much, just using a custom faker provider for getting the roles. A bit of extra code to get the actual roles used in the app for Symfony but that's it ;)

**Comment by reypm** [comment]
@theofidry @tshelburne Great, I will work on this and let you know how it goes, if I get this done I will close the issue as fixed, thanks for your support

**Comment by theofidry** [comment]
@reypm closing the issue as it's an old one and a solution has been provided. If you still have a problem don't hesitate to open a new issue.
