### ISSUE TITLE
Autoload related fixtures

### ISSUE THREAD

**Issue by yakimun** [nelmio/alice#316]
Would be great to be able automatically load fixture files for which references are exists in the current fixture file. This feature is available now?

**Comment by alexislefebvre** [comment]
Did you try [DependentFixtureInterface](https://github.com/doctrine/data-fixtures#dependentfixtureinterface)?

**Comment by theofidry** [comment]
@Yakimun AFAIR it works now.

**Comment by theofidry** [comment]
It definitely works if you are using the `Fixtures` facade*. We are using the same pattern in [HautelookAliceBundle](https://github.com/hautelook/AliceBundle).
