### ISSUE TITLE
Add ProcessorInterface::process method

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#318]
The idea of `ProcessorInterface::process` method is to override if needed the entity persistence system.

Concrete case: I have a Entity that have to be saved by the manager (Launching multiple operations).

Actually, I have to do this:

```php
namespace PowerDNSBundle\DataFixtures\Processor;

use AppBundle\Manager\DnsManager;
use Nelmio\Alice\ProcessorInterface;
use PowerDNSBundle\Entity\PowerDNSDomain;

class PowerDNSDomainProcessor implements ProcessorInterface
{
    /**
     * @var DnsManager
     */
    private $dnsManager;

    /**
     * @param DnsManager $dnsManager
     */
    public function __construct(DnsManager $dnsManager)
    {
        $this->dnsManager = $dnsManager;
    }

    /**
     * {@inheritdoc}
     */
    public function preProcess($object)
    {
    }

    /**
     * {@inheritdoc}
     */
    public function postProcess($object)
    {
        if (!$object instanceof PowerDNSDomain) {
            return;
        }

        $this->dnsManager->saveDomain($object, null, true);
    }
}
```

This works, but will do a SQL insert twice.

Having a `process` method would solve this.

What do you think?

**Comment by tshelburne** [comment]
I'm hesitant to do this because we are actively looking to remove persistence from Alice, and this would encourage further dependence on that. My personal approach would be to use the more nuanced `Loader` class directly (as documented [here](https://github.com/nelmio/alice/blob/master/doc/getting-started.md#detailed-usage)) and then write your persistence logic specifically.

@theofidry Thoughts?

**Comment by theofidry** [comment]
We have:

- pre-persist (via Processors)
- persist (via Loaders)
- post-persist (via Processors)

So IMO it's just a matter of having the proper persister in the loader in this case. As I guess your `DnsManager` is supposed to persist only `PowerDNSDomain` entities, I would do a decorator to decorates the regular persister used and this manager to call the `DnsManager` when necessary.

@Soullivaneuh would that fit your needs?

**Comment by theofidry** [comment]
ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
> `DnsManager` is supposed to persist only `PowerDNSDomain` entities

Not only. It also persists `PowerDNSRecord` entities.

When you create a domain, you have to setup some basic entries like `NS` and `SOA`. The manager do that thing.

**Comment by theofidry** [comment]
But the logic is the same: alice have to use a "persister" to persist the entities. The persister takes each object and persist them.

By default the persister is the Doctrine bridge, which relies on the `ObjectManager`, but it would be possible to inject a custom one instead.

**Comment by theofidry** [comment]
ping @Soullivaneuh

**Comment by theofidry** [comment]
Closing as I don't think we should add any more step to it and is not relevant in v3. Ping me if I missed something though.
