### ISSUE TITLE
Doctrine, persist method, solving unique id... not only refresh, too merge! (add feature?)

### ISSUE THREAD

**Issue by hidabe** [nelmio/alice#320]
Hello all

I need update data from fixtures, but i can't delete database.

I need use uniqueId, and update information for each row.

So, i have any like:
```
    quad_1:
        id: 1
        quadNumber: 10
```

I can add this row one time, but if i try add it again...
it show: uniqueId error.

I have changed line 38 Nelmio\Alice\Persister\Doctrine, in refresh method,
```
$this->om->refresh($object);
```
by
```
$this->om->merge($object);
```

And it work fine,

What you think about it?

Thanks!

**Comment by theofidry** [comment]
@tshelburne I don't think this would cause any BC and will indeed solve the use case where you assign IDs at the domain level (not letting the auto-increment of the database) and you don't want to purge your data between two loading.

That being said @hidabe, your "I can't delete database." is making me very uneasy.

**Comment by reinfi** [comment]
wouldn't it be possible to use a pre processor to do this? From my point of view fixtures aren't made for update statements.

**Comment by theofidry** [comment]
>wouldn't it be possible to use a pre processor to do this?

I hardly see how as it's at the persistence level (how we persist them), not a pre/post persist operation

>From my point of view fixtures aren't made for update statements.

@reinfi agree. Actually @hidabe I think this should be done in HautelookAliceBundle alone, as this bundle provides you a `--append` option. Alice does not and provide a helper to load/persist the fixtures for convenience, but it's code is the fixture loading, not the persistence. Such option should be handled in libraries wrapping Alice, not Alice itself.

Feel free to do a PR for that :)

**Comment by hidabe** [comment]
I know.

@reinfi It is right, fixtures are doing only insert, but, if i have id, what is the problem with do update? 

@theofidry ok, i have solved and testing this problem in nelmio/alice, changing: refresh by merge, it work, insert and update. I dont know how do it from alicebundle, and if it is possible.

I will try about it

any idea?

regards!

**Comment by theofidry** [comment]
@hidabe actually fixing this issue in alice wouldn't solve your problem if you are using AliceBundle, as AliceBundle use it's custom loader (it relies on alice for loading the YAML/PHP - fixtures files) for persisting them. Alice is meant to load fixtures, persisting them is an extra provided for convenience.

You should check https://github.com/hautelook/AliceBundle/blob/1.x/src/Alice/DataFixtures/Loader.php for adding that to AliceBundle :)

**Comment by tshelburne** [comment]
Yea, I definitely don't want to end up in a "lifecycle support" place with Alice - it's really not intended for managing your database at all (as a point of fact, we are looking at moving database integration to an entirely separate package). Alice's responsibility should stop at generating data the first time, and you can write custom scripts (or use a separate tool) for handling that data down the line.

**Comment by hidabe** [comment]
I know @tshelburne but TODAY, Alice is storing data with: 
```
$this->om->refresh($object);
```
You could replace it by:
```
$this->om->merge($object);
```

and same feature will work, and you will do update support.

I thing it, but, i will work trying do it from AliceBundle, yes,

Thanks!, Regards!

**Comment by theofidry** [comment]
@hidabe the point is, you are the first requiring it and even if you fix it in Alice it still won't work in AliceBundle. Alice has two loaders: one to load the fixtures file, the other one use the first one and persist the loaded fixtures.

AliceBundle just use the first loader, the second one is custom.

**Comment by theofidry** [comment]
As discussed, this is unlikely to be changed in Alice as things relative to the persistence are out of its scope.
