### ISSUE TITLE
[Question] Operation (Addition/Substraction) possible with a Variable?

### ISSUE THREAD

**Issue by c33s** [nelmio/alice#322]
from https://github.com/nelmio/alice/blob/master/doc/fixtures-refactoring.md#variables i know that i can use variables in my fixtures. just perfect for good data.

currently i try to populate a event database with events having a different duration. to also have populate the archive, i want the start date beeing from one year in the past to one year in the future. the events should have a duration between 1 and 5 days.

of course the following does not work, because the `+5 day` offset is from `now()` and not from `$startDate`
```
startDate: <dateTimeBetween('-1 year', '+1 year')>
endDate: <dateTimeBetween($startDate, '+5 days')>
```
is it somehow possible to archive this? somehow like that:
```
startDate: <dateTimeBetween('-1 year', '+1 year')>
endDate: <dateTimeBetween($startDate, '$startDate +5 days')>
```

edit: correted typo (first parameter of start date +1 year -> -1 year)

**Comment by reinfi** [comment]
I think you could just achieve this with an own provider.
A way could be:
`endDate: <dateTimeBetween($startDate, '+370 days')>`
But this only helps you because you set the first date to an exact value of now plus 1 year.

**Comment by c33s** [comment]
@reinfi i edited my issue, had a wrong first parameter in the example

**Comment by reinfi** [comment]
@c33s untested but why not using:

`<dateTimeInInterval($startDate,'+5 days')> `

**Comment by c33s** [comment]
@reinfi works perfect, thanks :)
needed to install  fzaninotto/faker from dev-master
