### ISSUE TITLE
[Ternary operator] Operator added within string

### ISSUE THREAD

**Issue by WebDevCodr** [nelmio/alice#325]
Seems like operator "50%?" is not parsed as operator when using something like this at YAML:

`profession: 50%? <randomElement(<{professions}>)>`

The resulting value in db is "50%? Bäcker(in)"

**Comment by reinfi** [comment]
i think you need to put it between quotation marks.

`profession "50%? <randomElement(<{professions}>)"`

**Comment by k-przybyszewski** [comment]
`profession: 50%? @professions*`

This will work for you

**Comment by WebDevCodr** [comment]
@reinfi sry, but same result with quotation marks

@k-przybyszewski this has a strange impact on fixtures for other tables "Couldn't generate random unique value for AppBundle\Entity\User: username in 128 tries." Tried it also with quotation marks.

**Comment by tshelburne** [comment]
@WebDevCodr How many fixtures with names of the form `professions*` do you have? That message generally means your pool of options is too small for the number of new fixtures you're generating.

**Comment by WebDevCodr** [comment]
There are just a few professions, but the strange thing is that it says no unique username could be generated, when i add "50%? @professions*" to a field at another entity fixture...

`
parameters:
  professions: ['Metzger(in)', 'Bäcker(in)', 'Verkäufer(in)']

AppBundle\Entity\Group:
  group_person:
    __construct: [User]
    roles: ['ROLE_USER']

AppBundle\Entity\User:
  user_person_{1..10}:
    username (unique): 'model-<current()>'
    email: <email()>
    enabled: 1
    plainPassword: <lexify>
    groups: ['@group_person']

AppBundle\Entity\Person:
  person_{1..10}:
    verified: <boolean()>
    firstName: <firstName()>
    lastName: <lastName()>
    email: '@user_model_<current()>->email'
    streetName: <streetName()>
    streetNumber: <buildingNumber()>
    city: <city()>
    postCode: <postcode()>
    country: <country()>
    dateOfBirth: <dateTimeBetween('-30 years', '-18 years')>
    callNumber: <phoneNumber()>
    profession: "50%? @professions*"
    user: '@user_person_<current()>'
`

**Comment by tshelburne** [comment]
Oh - yea, you're right, that's not correct. Will have to look into it.

**Comment by theofidry** [comment]
This issue has been addressed in 3.x, closing as this will not be fixed in 2.x unless someone is willing to provide a patch for it.
