### ISSUE TITLE
[v3] Rework Populator

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#328]
While reviewing the populator, if I got things right, most of it is simply creating populated objects from the set of property/value got from the `Fixture`. But instead of doing it ourself, maybe we could make use of [Symfony Serializer](https://symfony.com/doc/current/components/serializer.html) instead? Pretty sure it would already handle most of our use case and it would always be possible to add customer denormalizers to handle most custom work.

If we do so, I think that would remove a fair bit of code from alice, which is always nice. Besides I think it would be more performant as well.

@tshelburne WDYT?

**Comment by tshelburne** [comment]
I think this makes sense - the Symfony Serializer is also much more likely to get bug fixes / etc. Generally I try to reduce the number of dependencies, but this feels like a smart one.

**Comment by tshelburne** [comment]
My only question - does Serializer rely on annotated classes? We don't want to introduce anything that suddenly takes us back to "you must use Symfony" territory.

**Comment by theofidry** [comment]
>does Serializer rely on annotated classes?

Could you give an example? I'm not sure to have the same definition of annotated classes :P

>We don't want to introduce anything that suddenly takes us back to "you must use Symfony" territory.

Never, I don't want alice to become a Symfony bundle, that would be awful.

**Comment by tshelburne** [comment]
I mean does Serializer look to the class for Doctrine-style ORM annotations or anything like that.

**Comment by theofidry** [comment]
Nope, it uses reflection by default and if needed we can register custom denormalizers.

**Comment by theofidry** [comment]
Closing as will deal with it in #265
