### ISSUE TITLE
[v2] Deprecate range

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#329]
As of now, the [current regex](https://github.com/nelmio/alice/blob/3bf8e6f9cabb4f7d06d0c0d8f715ceb4b41d19c9/src/Nelmio/Alice/Fixtures/Builder/Methods/RangeName.php#L25) (`#\{([0-9]+)\.\.(\.?)([0-9]+)\}#i`) allows both `user{1..10}` and `user{1...10}`. This makes it error prone which can be nice.

However, I think this can confuse the user as well (does it work well? Is it by design I as can't see anything in the doc about that?) and also if we support that I see no reason to not support `user{0......10}` for example.

Instead what about removing this behaviour in v3 and deprecating it in v2?

**Comment by tshelburne** [comment]
This makes sense to me.
