### ISSUE TITLE
[v3] new branch

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#332]
Would it be possible to create a new branch `2.x` for v2 and put as the default branch to keep `master` for v3 only? (requires to merge #331 first)

Also would be nice if I could get write access too to set up a few things like Scrunitizer, restarting Travis builds or tagging issues. No plan to do rogue merge though ;)

/cc @tshelburne @Seldaek

**Comment by Seldaek** [comment]
I gave you commit access, please be reasonable ;)
