### ISSUE TITLE
Incorrect number with ranged fixtures

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#358]
If I have:

```yaml
User:
  user_{2...0}:
    # ...
```

It will generate... 4 users.

First this problem affects the deprecated range usage (using more than two dots, cf. #329). This also raise the question of using negative numbers in range. This was kind of possible before, but likely to fail when using the generated name in references. But as `-` is likely to be an issue in a reference, I'm for completely disabling this possibility.

**Comment by reinfi** [comment]
should be disabled.
