### ISSUE TITLE
References with variables doesn't work

### ISSUE THREAD

**Issue by Pym** [nelmio/alice#37]
Hello,

I can't figure out how to make variables work with reference. Actually, it doesn't even seem to be possible.

This is an example of what I'm trying to achieve:

    Nelmio\Entity\Group:
        group1:
            name: Admins
            owner: @user*
            name: $owner->name

Since $owner variable should return a reference to a random user, how can I reuse that variable to get a property of a specific object?

Is there any solution to do that with Alice?

**Comment by theofidry** [comment]
Closing as has been fixed. Feel free to open a fresh issue if you still have a problem.
