### ISSUE TITLE
[v3] Expression Language (DSL)

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#377]
The Expression Language will be the component responsible for evaluating the string values such as `<numberBetween(0, 3)>x @phone_*`.

List of possible values:

### Parameters

`'<{X}>'` where `X` is evaluated and can be anything.

Escaped expression: `'<<{X}>>'` (will return the string `'<{X}>'`.

### Functions

`'<function(X)>'` where `X` is evaluated and can be anything.

`function` can be a Faker or a PHP function.

Escaped expression: `'<<function(X)>>'` (will return the string `'<function(X)>'`.

### Identity

`'<(X)>'` shortcut for `<identity(X)>`

Returns `X` evaluated as a PHP element, e.g. `2 + $nbr` (provided `$nbr === `2`) will result in `4`.

Escaped expression: `'<<(X)>>'` (will return the string `'<(X)>'`.

**From now on, the 3 elements above will be referred as the pattern `'<X>'`.**

### Arrays

Regular arrays: `[X, Y, ... Z]`.
Each element of the array is evaluated and can be anything.

String arrays: `'Xx Y'`

- `X` must be either a positive integer or a function/param, e.g. `10` or `<numberBetween(10,20)>`
- `Y` must be a non-empty string
- This expression cannot be surrounded, i.e. `'foo 10x bar'` is invalid and `'10x foo bar'` match the above pattern with `X='10'` and `Y='foo bar'`.

String array `'[X, Y, ... Z]'`

Similar to the regular array, the difference is that the annotation is a string one, useful for being able to use the previous pattern with arrays: `'10x [@user*->name, @group->name]'`.

The expression cannot be surrounded either, otherwise will be interpreted as a plain string (this does not mean that an element could not be evaluated, but it certainly won't return the expected result.

Escaped expression: `'[[X]]'` (will return the string `'[X]'`.

### Optional

`D%? X: Y` where `D` must be an element of `]0;100[` and `X`, `Y` are evaluated

- If `Y` is `null`, the condition is written `D%? X` instead.
- `X` must be an non-empty string and must not contain the `:`
- `Y` must be a non-empty string and must not contain a space as it is used as a delimiter to determine the end of `Y`. So `20%? foo: bar baz` will be matched with `(D, X, Y)=('20', 'foo', 'bar')` (`'baz'` is not part of `Y`).

There is no escape sequence for this one.

### References

`@ref` where `ref` is evaluated as a reference.

`ref` must be first resolved like any value to get a string from it. Once done, the resulting value can be used to find a reference matching that mask.

Examples:

- `@user{1..2}` => `@user1` or `@user2`
- `@user*`
- `@user_{alice, bob}` => `@user_alice` or `@user_bob`
- `@user<numberBetween(1,20)>` => `@userX`,
- `@user<current()>`

There is obvious limits to this annotation: we cannot use the optional pattern with it, e.g. `'@user50%? foo'` but they are such edge cases and really complicated, I am not willing to support them. In other words, `ref` is limited to:

- characters allowed by references
- `*` character (for wildcards)
- `{}`, digits and `.` (for lists)
- `'<X>'` pattern

Escaped expression: `'@@ref'` will return `'@ref'`

### Property reference

`@ref->prop` where `@ref` is evaluated (like described in the References section) (but not `prop`).

`prop` refers to a property of the object pointed by `@ref` and is accessed via a property accessor (which will determined which getter to use if a getter is required or get it directly if it is a public property). For the sake of simplicity, it is assumed that properties are plain english and as such should only be composed of letters or underscores `_`.

@tshelburne for that one I'm willing to add support for calling a function e.g. `@user1->getName()`, WDYT?

As `prop` is not resolved, having `@user1->name<current()>` will be equivalent to `Alice<current()>` if `@user1->name` results in `'Alice'`.

**Comment by theofidry** [comment]
@tshelburne I udpated the issue, take your time to review it, but it's a fairly important piece and as is high level it should not be much of a problem even if you did not follow the change of code of v3 in details.

**Comment by tshelburne** [comment]
All of this looks good - not sure what the very last sentence is about. Is that relevant to the function call on `ref`?

**Comment by theofidry** [comment]
@tshelburne yeah it's relative to `@ref`. I was saying that if you have `
@user<numberBetween(1,20)>`, it will give the fixture of reference`@user5` for example. But if you do `@user1->name<numberBetween(1,20)>` will result in trying to get the `name<numberBetween(1,20)>` property of the fixture of reference `@user1` (and as a result fail), i.e. the function call won't be evaluated.

**Comment by tshelburne** [comment]
Ah, gotcha - that makes sense to me. That feels like a) it opens a complexity can of worms, and b) enables features that are so specific, devs should be required to write their own logic around it. You might want to throw or something?

**Comment by theofidry** [comment]
>You might want to throw or something?

Not sure to understand that bit

**Comment by tshelburne** [comment]
`throw` an error if you encounter that syntax.

**Comment by theofidry** [comment]
Whenever it's possible yeah it would great. I'm don't want to guarantee that because I fear this would require too monstrous regexes, but that would be great.

**Comment by aistis-** [comment]
Hello! Is `@user1->getName()` already supported?

**Comment by theofidry** [comment]
@aistis- yes it should :)

**Comment by aistis-** [comment]
I get an error in beta3:
```
[Nelmio\Alice\Throwable\Exception\Generator\Resolver\ResolverNotFoundException]  
  No resolver found to resolve value "@product_1->getSku()". 
```

But it worked as `@product_1->sku` on private property.

**Comment by theofidry** [comment]
Could you open a dedicated issue for it? If possible with the version used as well
