### ISSUE TITLE
[Question] Resolve array values

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#378]
@tshelburne sorry to annoy you with another thing again, but I'm having trouble to understand this one:

```yaml
Nelmio\Entity\User:
    user:
        username (unique): '<numberBetween()>'
        favoriteNumber (unique): ['<numberBetween()>', '<numberBetween()>']
```

From what I can see, this means that:

1. `favoriteNumber` value is unique at the class level, i.e. if we check that value for each user instance, none will have the same value
2. the value picked is picked from an array of possibilities

My question is: how do you tell the difference between a property that takes an array as a value (like `owners`, and one for which an array means a array of possible values (like the example above)?

**Comment by theofidry** [comment]
ping @tshelburne

**Comment by tshelburne** [comment]
Sorry, this one got lost in the fray when I was clearing out notifications.

If we consider the "possible values" feature important enough to have as part of the Alice library (this isn't obvious to me, but I'm open), I think it requires new syntax of some kind. I would naturally expect `favoriteNumber` to be a unique tuple based on the syntax above. We could probably just create a new function:

```yaml
Nelmio\Entity\User:
    user:
        username (unique): '<numberBetween()>'
        favoriteNumberTuple (unique): ['<numberBetween()>', '<numberBetween()>']
        favoriteNumberFromOptions (unique): <options([...])>
```

Thoughts?

**Comment by theofidry** [comment]
I like the `options` idea 👍

**Comment by tshelburne** [comment]
I would suggest a more clear name, but I think it would work.

**Comment by theofidry** [comment]
Actually can already be done with Faker `randomElement` I think :P
