### ISSUE TITLE
To specify the exact date?

### ISSUE THREAD

**Issue by 7-ON** [nelmio/alice#380]
Symfony 3.0.6
fitures: < DateTime('08.08.1985') >  in db: 1978-07-05 

Prompt me that it is necessary to specify the date in the database and fiksturaz was the same.

**Comment by theofidry** [comment]
Dates are properly generated, that said in your case `DateTime` is not a function but a class, hence `<DateTime()>` will not work.

Instead I recommend you to take a look at [Faker dates & times functions](https://github.com/fzaninotto/Faker#fakerproviderdatetime) to achieve what you want.
