### ISSUE TITLE
References access

### ISSUE THREAD

**Issue by spolischook** [nelmio/alice#392]
Is there any way to add new reference to alice? Now I have to set array References with setReferences in Loader but can't add just one reference in runtime without reload all of references. Maybe you can open access to ```$objects``` property in Loader?

**Comment by theofidry** [comment]
I don't really want to open `$objects` in alice core, there is already a getter/setter which is more than enough. If you need to inject a reference only for 1 load but not others, you can already do it (even though a bit cumbersome).

For more extended and custom usages, you can always create your own loaded inheriting from alice one, `$object` is protected so you have access to it.

Note that in v3 the loader will be stateless so any external reference will need to be injected in the loading method.

**Comment by theofidry** [comment]
That said I don't know what your use case is, if you feel like I missed something feel free to give me more details :)

**Comment by spolischook** [comment]
Ok so what I see for now it's:
```php
$this->objects         = new Collection;
```
in constructor of Nelmio\Alice\Fixtures\Loader and I have only ability to replace all references by ```setReferences``` method.
It would be great to have ability add reference by method in Loader, e.g.:
```php
/**
     * @param string $key
     * @param object $object
     */
    public function addReference($key, $object)
    {
        $this->objects->set($key, $object);
    }
```

**Comment by theofidry** [comment]
But you don't "add", because in that case `$objects` is not a list but a hashmap, i.e. if the key already exists you are overriding the value, not adding it.

It's a bit more verbose but you can already do it:

```php
$references = $loader->getReferences();
$references->set($key, $object);

$loader->setReferences($references);
```

Granted it's not very nice, but as this won't be in v3 and is potentially confusing (you're not adding but setting), I would prefer not change that.

**Comment by spolischook** [comment]
This code 
```php
$loader->setReferences($references);
```

is too expensive, because it will foreach all references again and again.
So maybe,  decouple Nelmio\Alice\Instances\Collection (maybe ReferenceRepository is more best name) from Loader, and inject it? Then I can use it separately.

**Comment by theofidry** [comment]
>So maybe, decouple Nelmio\Alice\Instances\Collection

But that will end up being a BC break, which is not allowed for v2, and this problem won't happen in v3. So in any case I think the best solution for you is to override Alice loader through inheritance.

**Comment by spolischook** [comment]
> I think the best solution for you is to override Alice loader through inheritance

yep, I'll do. And what will happen in v3 that it's resolve my problem with references?

**Comment by theofidry** [comment]
You will have to inject the references in the load, cf. [LoaderInterface](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/LoaderInterface.php#L32) and the [default loader](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Loader/SimpleLoader.php) will not hold the objects. That said it will still be possible to have a loader keeping the references by decorating the native one and implementing the loader interface.

If you wish to know more about what will change in v3 check #265.

**Comment by spolischook** [comment]
It would be nice upgrade! Wish you the best.
