### ISSUE TITLE
Cannot pass build-in function result to custom provider

### ISSUE THREAD

**Issue by piotrkochan** [nelmio/alice#410]
As in the title.

    <customProvider(numberBetween(1, 100))>

Does not work

    Fatal error: Call to undefined function numberBetween() in /home/..../vendor/nelmio/alice/src/Nelmio/Alice/Instances/Processor/Methods/Faker.php(183) : eval()'d code on line 1

**Comment by theofidry** [comment]
I fear that's the same problem as https://github.com/nelmio/alice/issues/360 :/

**Comment by theofidry** [comment]
Closing as it's a duplicate.
