### ISSUE TITLE
Rendering JSON fixtures

### ISSUE THREAD

**Issue by jumale** [nelmio/alice#419]
Hi guys,
By this ticket I just want to share my experience regarding your library.
I was looking for a way how to render JSON fixtures using your library. I couldn't find an official solution for that and I realized that initially the library works only with classes.
So I have found [my own solution](https://gist.github.com/jumale/bc41adcded703f3fcc4fbb30adc2297b) (I think it's quite elegant) and I'm happy to share it with you. If you want, you can copy/paste it and add it to your docs, so that other people can reuse it.
Also if you have any suggestions about the logic - I'm open for discussions.

**Comment by theofidry** [comment]
Indeed it's quite interesting. I don't like at all the autoloading part, but from the look of it, as the classname is not part of the final result doesn't include those, we could skip it, i.e. you declare everything as `ArrayFixture`.

I am not for adding an option for outputting a JSON string instead of an array of fixtures, but having a simple model for easing this is acceptable. If you are willing to, I would gladly accept a PR for adding this feature :)

**Comment by jumale** [comment]
@theofidry first I tried to use just this model with the same class `ArrayFixture` for both groups and users. But in this case I got only users list in the result, but the groups were missing. It looks like the class name should be a unique name for each defined "entity", otherwise the library overrides fixtures.
That's why I had to add that auto-loading logic, to be able to define unique class names for each separated "entity"

**Comment by theofidry** [comment]
It doesn't merge the class declarations, i.e. if you have two blocks declared with `ArrayFixture`, there only one that will be kept (and which one is kept is up to Symfony YAML Parser so I'm not sure of the result). So you have to change:

```yaml
```

**Comment by jumale** [comment]
Ahhh, ok! Then the autoloading is not needed, definitely

**Comment by theofidry** [comment]
Looking at this again, I don't think we need to change anything in alice core.

If you need your whole output to be in JSON, you can easily transform the collection of objects resulting from the loading via a `json_encode` or the Symfony Serializer. As for needing it within your graph yourself, i.e. having an property that is an entity encoded into a JSON, this can be achieved by a custom faker as well:

```yaml
Dummy:
    user{1..10}:
        jsonProp: '<(json_encode(@foo*))>'
```
