### ISSUE TITLE
Add a provider for a safe usage of password

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#428]
As reported in https://github.com/nelmio/alice/issues/176 and https://github.com/hautelook/AliceBundle/issues/240, Faker password provider may use the character `@` which leads alice to think that there's a reference.

A fix would be to provide a way to escape any string, which could be done in v3 only and should be discussed in #377, another easier way is to create a custom faker provider which removes this special character.

/cc @Simperfit

**Comment by theofidry** [comment]
@Simperfit could you check that on 3.x? I don't think this should be an issue anymore

**Comment by Simperfit** [comment]
Yes will do
Le ven. 20 oct. 2017 à 20:52, Théo FIDRY <notifications@github.com> a
écrit :
