### ISSUE TITLE
[Instantiator] Deprecate inaccessible constructors

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#441]
The current instantiator works even if the constructor is private or protected. I personally feel like this is hacky as you are not instantiating the objects as they should normally, i.e. potentially create an object in a weird state. Besides, it's by far the most complex case.

Doing it is a legit use case IMO, but I don't think this should be in the core and much less enabled by default. If the user wants to do it, he should explicitly do so.

@tshelburne any opinion on this?

**Comment by tshelburne** [comment]
Makes sense to me.
