### ISSUE TITLE
Deprecation of `$fake`

### ISSUE THREAD

**Issue by thedamnedrhino** [nelmio/alice#490]
In the [Docs](https://github.com/nelmio/alice/blob/2.x/doc/customizing-data-generation.md) it states that using the `$fake` closure is deprecated. So how is it possible to nest Faker Calls?

**Comment by theofidry** [comment]
Just use data providers instead. The reason why this has been deprecated is because there is a lot of cases with other more advanced features provided where this would not work well.

**Comment by thedamnedrhino** [comment]
Creating [custom Data Providers](https://github.com/nelmio/alice/blob/2.x/doc/customizing-data-generation.md#custom-faker-data-providers) for a simple Nested call seems a little overkill for me. Are nested providers going to be implemented in the near Future?

**Comment by theofidry** [comment]
To some extend. There is some cases where the lexer and parser can't handle
in v3 but it should cover most of the use cases. It's not my main focus for
v3 to be honest, but the system in v3 will at least allow to enhance it
later on if someone is ready to work on it.

**Comment by theofidry** [comment]
It is worth noting that in v3 nested calls are supported, e.g. `<foo(<bar())>` will work perfectly fine, mitigating greatly this issue.
