### ISSUE TITLE
4th resolution step

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#513]
[From the documentation](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#reuse-generated-data-using-objects-value):

> Sometimes you require value objects that are not persisted by an ORM, but are just stored on other objects. You can use the (local) flag on the class or the instance name to mark them as non-persistable. They will be available as references to use in other objects, but will not be returned by the LoaderInterface::load call.

So from my understanding, the `local` flag was used to handle embeddables. However now:
- We are removing the persistence layer in 3.x so there is no need for that anymore
- in 2.x provided you are using Doctrine 2.5+, the handling of embeddables is done differently (by checking the classes via Doctrine itself)

The only use case I can see still is if you want to remove a fixture from the result set (it's all the local flag does). This bring an interesting question the design of the library for 3.x. Right now the process is:
1. Generate a comprehensible set of data (create `Fixture` objects, tokenize values like `<($foo)>` in order to easily be able to evaluate them later
2. "Resolve" the set:
   - Resolve the parameters
   - Resolve the fixture flags, this is at this step that we handle the template flags for example, to create proper fixtures definition
3. Generate the objects described by the fixtures

Supporting a feature like the local flags, means being able to alter the set of data after the objects generation, i.e. having a 4th step. Right now this step doesn't exist, but this could be interesting. The drawback is slightly more complexity and a performance cost (you have yet another iteration on the whole set).

I have no strong opinion on this 4th step feature and even the local flag to be honest. What about you @tshelburne?

**Comment by tshelburne** [comment]
Since the local flag isn't particularly useful now, I don't see any reason to take this step at this point in time. If you feel like there's some knowledge that would be difficult to return to later, if or when we needed to add a 4th step, I would memorialize it in either documentation or in a ticket to be discussed in the community. No reason to complicate things now.

**Comment by theofidry** [comment]
Let's keep this issue in the backlog then and consider to add it only if we see a use case. We still have time before a stable release.

**Comment by theofidry** [comment]
I actually think it's useless: you can already do that by decorating the object generator.
