### ISSUE TITLE
Usage of the `@` character

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#516]
In v2, you can freely use the `@` character in a string: `example@email.com`. However this is not conform to the [DSL spec](https://github.com/nelmio/alice/issues/377) as it should be escaped instead (`example\@email.com`). The lazy way would be to deprecate it in v3 and change nothing in v3 (i.e. will break as won't be able to find the fixture `@email.com`. However this is a common usage and I think we can make an exception for this one even if it ask for a bit of extra work. @tshelburne WDYT?

**Comment by theofidry** [comment]
>do you mean you feel like you can support it without the escaping?

Yeah in the case where `@` is preceded by a non space string like `a@`.

>Maybe a missing reference shouldn't throw an error, but instead should throw a warning and attempt to set the value to the string literal

If we were to do that we would need to apply the same for variables. But I think throwing an exception makes it easier to spot than a warning.

**Comment by tshelburne** [comment]
I'm fine with that - if it becomes a pain point for users, we can revisit.

**Comment by karser** [comment]
How to use emails in 3.x? https://github.com/nelmio/alice/issues/568

**Comment by theofidry** [comment]
@karser I updated the issue description (it's `\@` not `@@`), but I have yet to add the ability to automatically escape the `@` character in a string.

**Comment by karser** [comment]
thanks @theofidry, this seems to be working

**Comment by cadavre** [comment]
I have another case where escaping `@` doesn't work at all:

```
message: |
            <identity("Hi! some\@mail.com Bye!")>
```

Gives me, in database:

```
Hi! some$_instances['mail.com'] Bye!
```

**Comment by theofidry** [comment]
@cadavre do you mind opening a new issue for it? I would prefer that rather than digging out that old issue :)
