### ISSUE TITLE
Add support for steps with ranges

### ISSUE THREAD

**Issue by aledeg** [nelmio/alice#539]
It could be neat to use the range with steps. For instance, to create 5 different users:

``` yaml
User:
  User{1..10..2}:
    ...
```

It could be neat to use the range in reverse. For instance:

``` yaml
User:
  User{10..1}:
    ...
```

Those feature would be really handy with templates. The first one to get cyclic data. The second one to save current values in reverse.

**Comment by theofidry** [comment]
Regarding the first one I find the syntax a bit confusing, maybe:

```yaml
User:
  User{1..10, 2}:
    #...
```

As for the later one this syntax is already allowed, but as the order does not matter it makes no difference to have `User1` first or `User10`.

**Comment by aledeg** [comment]
>Regarding the first one I find the syntax a bit confusing

This is the [bash increment brace expansion feature syntax](http://wiki.bash-hackers.org/syntax/expansion/brace#increment). But I am ok with any syntax.
If I can find some time, I'll try to send a PR.

>As for the later one this syntax is already allowed, but as the order does not matter it makes no difference to have User1 first or User10.

I agree that on the data level it makes no differences but on the database level it makes a difference. The natural order of the database will send me the first inserted record. In my example, I was hoping that the first record would User10, but it was User1.

I made the following workaround for my test case:
```yaml
User:
    User{10}:
        ...
    User{1}:
        ...
```
This way, User10 is inserted before User9 which is inserted before User8 which is... but you get the idea.
With the braces around the number, I still can use ```<current()>``` in my object fields.

**Comment by theofidry** [comment]
>I agree that on the data level it makes no differences but on the database level it makes a difference. The natural order of the database will send me the first inserted record. In my example, I was hoping that the first record would User10, but it was User1.

I'm not sure to understand the problem, if the order is important, then it should be re-ordered. It is extremely difficult to guarantee the order and there is several issues:

- how do you deal with injected objects, should they come first or after?
- the generation order is not the same as the declaration order, some objects requires other objects to be instantiated first
- there is several extensibility points, e.g. to add custom flags, where you can alter the order of fixtures

A solution is to order all the fixtures according to a certain criteria, but as this criteria is likely to be user specific and has a performance impact, I would rather not try to solve this in alice.

**Comment by theofidry** [comment]
Edit regarding my last message:

- I'm cool with [this syntax](https://github.com/nelmio/alice/issues/539#issuecomment-244927575)
- If a specific order is required, this should be done after loading the fixtures, either as a hook inside the loader, by decorating the loader or whatever. As the persistence is done *after* anyway, you're free to do whatever you want before the objects are persisted.

**Comment by reinfi** [comment]
I added a pull request for the step feature.

For the order this should not done by alice, this is business logic how you need your data to be sorted. So I fully agree with theofidry.
