### ISSUE TITLE
Reference escaping

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#543]
Right now the ExpressionLanguage escapes `@` by doubling it i.e. `@@` and the same for `$`. It's already possible to escape in v2  (`\@`) and should be the same for variables, so the doubling `@@` and `$$` should be changed to `\@` and `\$` to avoid an unneeded BC break.

**Comment by theofidry** [comment]
The full list if escaped values right now:

- arrows: `<<` => `<` and `>>` => `>` as a result:
  - parameters: `<<{param}>>` => `<{param}>`
  - functions: `<<foo()>>` => `<foo()>`
- array: `[[X]]` => `[X]`
- reference: `@@` => `@`
- variable: `$$` => `$`

Looking at it as a whole this notation makes more sense to me and I'm less sure on how to apply the `\` for the other, @tshelburne WDYT?

**Comment by tshelburne** [comment]
I agree with your first statement, that the escape character should be `\`, in all cases. Admittedly, there's something nice in the doubled chars for the "surrounding" stuff, but everyone is used to the backslash escape in strings. I vote keep it simple and expected.

**Comment by theofidry** [comment]
I'm fine with keeping the `\`, but I just don't know how it should be applied for the other things :/

**Comment by tshelburne** [comment]
I must be missing something - shouldn't it work for all circumstances?
