### ISSUE TITLE
Uniqueness enforced in constructor parameters

### ISSUE THREAD

**Issue by PWalkow** [nelmio/alice#545]
Currently I have an entity provided by the entry in *.yml file:
```
Awesome\Document\Example:
  example_{1..5}:
    __construct:
      - <domain()>
```

As you can see the constructor is requiring string to be specified as an argument. I've tried plenty of ways but none seems to work. How I can enforce it to be unique value for each of the example entities? There is no example of it in the docs.

**Comment by theofidry** [comment]
[This will be supported in v3](https://github.com/nelmio/alice/pull/544/files#diff-1338146ac74b0c166970df57bfa778beR207) but you won't get it work in 2.x and I don't think I'll spend time on back porting this feature either.

As of now the v3 kind of works, I'm in the middle of solving some edge cases but the first beta should come out soon (early or in the middle of next week).

**Comment by PWalkow** [comment]
Thanks, I'll try to update version to v3. Hopefully there will be no big issues with that.

**Comment by theofidry** [comment]
I recommend you to wait for the first beta release for that but otherwise I
hope the upgrade will go smoothly :)
