### ISSUE TITLE
Composite Key generation

### ISSUE THREAD

**Issue by hiefman** [nelmio/alice#547]
Correct me if I'm wrong, but as far as I understand this is not possible at the moment to populate a table having composite keys. Image the following table:

```
CREATE TABLE `node_tag` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `node_id` int(11) DEFAULT NULL,
  `tag_key` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `tag_value` longtext COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `node_tag_idx` (`node_id`,`tag_key`),
  KEY `IDX_HSUAJIEJDJAO` (`node_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

```

For testing purposes I need a small set of predefined tag_keys (an array with ~20 - 30 items) which shall be assigned to a node (~0 - size of tag array per node).

I would need a generator which takes care of the uniqueness of the combination of "node_id" and "tag_key".

Marking the "node_id" unique would result in having only one "node_tag" per "node". Marking the "tag_key" unique would result in a runtime exception when having more nodes than "tag_keys".

As for my scenario I need to emulate having just a few "node_tags" but a 1:N relationship with nodes I couldn't find a way to get around this. Any ideas? If not, I would suggest this as a feature request as having attribute value tables is not that uncommon.

Greetings

Dennis

**Comment by theofidry** [comment]
There is nothing built in to handle that, but it's still perfectly doable by using [custom providers](https://github.com/nelmio/alice/blob/2.x/doc/customizing-data-generation.md#custom-faker-data-providers. You can pass to it the list of available keys and the ID got to return a random key. If you need uniqueness, you can make store the generated values in your provider to ensure the random value picked will result in unique combination.

Note however that you may have some issues with `node_id` depending of your entities behind (it can work with Doctrine if you are setting relationships correctly and not just passing the ID value).

**Comment by hiefman** [comment]
Ah great, I'll have a look on that. Thx alot!

**Comment by hiefman** [comment]
`console h:d:f:l -vvv` raises the follwoing stack trace:

```
  [Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]
  Loading files limit of 5 reached. Could not load the following files:
  C:\[...]Bundle\DataFixtures\ORM\node_tags.yml:
   
- Property node is not defined for instance self

Exception trace:
 () at C:\[...]\vendor\hautelook\alice-bundle\src\Alice\DataFixtures\Loader.php:97
 Hautelook\AliceBundle\Alice\DataFixtures\Loader->load() at C:\[...]\vendor\hautelook\alice-bundle\src\Doctrine\DataFixtures\Executor\ExecutorTrait.php:41
 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\ORMExecutor->Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\{closure}() at n/a:n/a call_user_func() at C:\[...]\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php:233
 Doctrine\ORM\EntityManager->transactional() at C:\[...]\vendor\hautelook\alice-bundle\src\Doctrine\DataFixtures\Executor\ExecutorTrait.php:45
 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\ORMExecutor->executeExecutor() at C:\[...]\vendor\hautelook\alice-bundle\src\Doctrine\DataFixtures\Executor\ORMExecutor.php:72 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\ORMExecutor->execute() at
C:\[...]\vendor\hautelook\alice-bundle\src\Doctrine\DataFixtures\Executor\FixturesExecutor.php:44
 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\FixturesExecutor->execute() at C:\[...]\vendor\hautelook\alice-bundle\src\Doctrine\Command\LoadDataFixturesCommand.php:221
 Hautelook\AliceBundle\Doctrine\Command\LoadDataFixturesCommand->execute() at C:\[...]\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:256
 Symfony\Component\Console\Command\Command->run() at C:\[...]\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:834
 Symfony\Component\Console\Application->doRunCommand() at C:\[...]\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:186
 Symfony\Component\Console\Application->doRun() at C:\workspaces\idea\[...]\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\[...]\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:117
 Symfony\Component\Console\Application->run() at C:\[...]\bin\console:29
```
`
<uniqueTagForNode('@node_<numberBetween(1, 100)>')>` results in 
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected 'node_' (T_STRING), expecting ',' or ')'
```

**Comment by theofidry** [comment]
Ah I see, it's highly possible that this is a parsing error indeed. I'll try to look into it, but it's very likely that I can't do much about it: alice 2.x doesn't have a proper lexer so it is very hard to have some syntax right (issue addressed in 3.x).

This however should work:

```yaml
MyBundle\Entity\NodeTag:
    node_tag_{1..500}:
        node: '@node_<numberBetween(1, 100)>'
        tagKey: <uniqueTagForNode($node)>
        tagValue: <words(3, true)> 
```

**Comment by theofidry** [comment]
No easy fix unfortunately. The solution in 2.x is to use faker providers in the meantime or the suggested solution above.
