### ISSUE TITLE
Wildcard Matching

### ISSUE THREAD

**Issue by mdavis1982** [nelmio/alice#56]
Whilst I understand that the following is the correct behaviour, it's actually really confusing.

I had:

```yaml
Entity\Team:
    team{1..10}:
        name: <firstName()>

Entity\TeamMember:
    teamMember{1..100}:
        name: <firstName()>
        team: @team*
```

This tries to pass a `TeamMember` instance to the `setTeam()` accessor of `TeamMember` rather than a `Team` instance. I presume the wildcard is matching the `teamMember` key before `team1` etc. Changing this to:

```yaml
Entity\Team:
    team{1..10}:
        name: <firstName()>

Entity\TeamMember:
    member{1..100}:
        name: <firstName()>
        team: @team*
```

Fixes the issue.

But I think it should be made clear or have a wildcard operator that only operates on numbers to allow the original version to work.

**Comment by petegore** [comment]
Got the same issue today using "@board*" which could refer to "Board" ; "BoardGrid" or "BoardUniverse". I rename my Boards to "board_{1..100}" to solve it.

**Comment by reinfi** [comment]
got the same issue, and solved it with an underscore at the end of every instance.

**Comment by theofidry** [comment]
I think it's far too late now to change this behaviour as it's a very used feature. Even for v3 it would be too much of a userland BC. That said, we could have another version of the wildcard matching to exclude the declared class...

I'm closing this issue anyway as it's not really a focus now. If people are still interested and have a suggestion, feel free to open a new issue and avoid to spam everyone for such an old issue.
