### ISSUE TITLE
v3 - HTML code in fixtures

### ISSUE THREAD

**Issue by mcjwb** [nelmio/alice#569]
Hi,
Is there a way to allow HTML in fixtures (or disable the lexer for certain fixtures)?
On my first attempt I got the error:
`PHP Fatal error:  Uncaught Nelmio\Alice\Exception\FixtureBuilder\ExpressionLanguage\LexException: Could not lex the value...`
Then on a simplified test case I got the error:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid token "&lt;div&gt;test&lt;/div&gt;" found. in /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php:100
Stack trace:
# 0 /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php(76): Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\SubPatternsLexer->lexFragment(Object(Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\ReferenceLexer), '&lt;div&gt;test&lt;/div&gt;')
# 1 /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/FunctionLexer.php(52): Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\SubPatternsLexer->lex('&lt;div&gt;test&lt;/div&gt;')
# 2 /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/LexerRegistry.php(45): Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\FunctionLexer->lex('&lt;div&gt;test&lt;/div&gt;')
# 3 /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Parser/SimpleParser.php(50): Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\Lexer in /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php on line 100
> 
> Fatal error: Uncaught InvalidArgumentException: Invalid token "&lt;div&gt;test&lt;/div&gt;" found. in /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php on line 100
> InvalidArgumentException: Invalid token "&lt;div&gt;test&lt;/div&gt;" found. in /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php on line 100
> Call Stack:
>     0.0004     369992   1. {main}() myFile.php:0
>     3.2295   11068000   2. Fidry\AliceDataFixtures\Loader\SimpleFileLoader->load() myFile.php:42
>    69.4117   23879752   3. Nelmio\Alice\Loader\NativeLoader->loadFile() /var/www/project/vendor/theofidry/alice-data-fixtures/src/Loader/SimpleFileLoader.php:48
>    69.4117   23879752   4. Nelmio\Alice\Loader\SimpleFileLoader->loadFile() /var/www/project/vendor/nelmio/alice/src/Loader/NativeLoader.php:217
>    69.4418   26515240   5. Nelmio\Alice\Loader\SimpleDataLoader->loadData() /var/www/project/vendor/nelmio/alice/src/Loader/SimpleFileLoader.php:48
>    69.4418   26515240   6. Nelmio\Alice\FixtureBuilder\SimpleBuilder->build() /var/www/project/vendor/nelmio/alice/src/Loader/SimpleDataLoader.php:46
>    69.4418   26515240   7. Nelmio\Alice\FixtureBuilder\Denormalizer\SimpleDenormalizer->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/SimpleBuilder.php:39
>    69.4418   26515728   8. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SimpleFixtureBagDenormalizer->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/SimpleDenormalizer.php:46
>    69.4418   26515864   9. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\FixtureDenormalizerRegistry->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SimpleFixtureBagDenormalizer.php:63
>    69.4418   26515864  10. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\Chainable\SimpleDenormalizer->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/FixtureDenormalizerRegistry.php:67
>    69.4418   26516264  11. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\SimpleSpecificationsDenormalizer->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/Chainable/SimpleDenormalizer.php:81
>    69.4418   26516376  12. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\SimpleSpecificationsDenormalizer->denormalizeProperty() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/SimpleSpecificationsDenormalizer.php:73
>    69.4418   26516456  13. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\Property\SimplePropertyDenormalizer->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/SimpleSpecificationsDenormalizer.php:103
>    69.4418   26516456  14. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\Value\UniqueValueDenormalizer->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/Property/SimplePropertyDenormalizer.php:40
>    69.4419   26516456  15. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\Value\SimpleValueDenormalizer->denormalize() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/Value/UniqueValueDenormalizer.php:43
>    69.4419   26516456  16. Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\Value\SimpleValueDenormalizer->parseValue() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/Value/SimpleValueDenormalizer.php:44
>    69.4419   26516456  17. Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Parser\FunctionFixtureReferenceParser->parse() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/Value/SimpleValueDenormalizer.php:68
>    69.4419   26516456  18. Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Parser\StringMergerParser->parse() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Parser/FunctionFixtureReferenceParser.php:43
>    69.4419   26516456  19. Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Parser\SimpleParser->parse() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Parser/StringMergerParser.php:40
>    69.4419   26516456  20. Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\LexerRegistry->lex() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Parser/SimpleParser.php:50
>    69.4420   26547672  21. Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\FunctionLexer->lex() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/LexerRegistry.php:45
>    69.4420   26547712  22. Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\SubPatternsLexer->lex() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/FunctionLexer.php:52
>    69.4420   26547808  23. Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\SubPatternsLexer->lexFragment() /var/www/project/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php:76
```

Thanks,
Joe

**Comment by theofidry** [comment]
Yes, unless I missed something, your HTML is a simple string, so you could have a simple [Faker provider](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers) with an `escape` function that could return the string unchanged, e.g.:

```php
class CustomProvider
{
  public function escape(string $string)
  {
    return $string;
  }
}
```

Your functions are parsed by [FunctionTokenParser](https://github.com/nelmio/alice/blob/master/src/FixtureBuilder/ExpressionLanguage/Parser/TokenParser/Chainable/FunctionTokenParser.php). As you can see in it, it's doing special things to figure out how to get the arguments and if they need to be parsed or not. You probably could have your own token parser decorating this one and if the function name is `escape`, then skip the parsing bit.

However I release this is not very easy not convenient and it's probably one of the most useful custom point of extension. IMO we could probably split the current `FunctionTokenParser` by having an `ArgumentParserInterface`. It adds a bit of complexity again, but it's the easiest way I see to make it more or less painless for the user to have more freedom on how to parse the arguments.

Another solution is to give up this special extension point (i.e. not complicating the abstraction layer to make it easier) and instead have an `escape` function natively in Alice (which I would like to have tbh. It would solve both #516 and #428).

WDYT @tshelburne?

**Comment by tshelburne** [comment]
I think native `escape` makes a lot of sense.

**Comment by theofidry** [comment]
@tshelburne with or without a proper extension point?

**Comment by tshelburne** [comment]
I don't think we need to offer the extension yet - `escape` is common enough that it should be in the library, and we can keep the interface simple until it's really needed. Did you have other use-cases in mind for custom parsing? That seems like a pretty deep dependency.

**Comment by theofidry** [comment]
Maybe extending the identity parsing. Not convinced though

**Comment by mcjwb** [comment]
Thanks for getting back to me so soon.
It seems to me that a native escape function would be a good idea, I'd guess it'd have a reasonably common use case.
I'll give the custom faker provider a go in the meantime.

**Comment by kcivey** [comment]
So is the only way to include HTML (or anything else with `<`) in fixtures to wrap every tag in the `identity` function? Instead of `<i class="fa fa-cog"></i>`, write `<identity('<i class="fa fa-cog"></i>')>`?

**Comment by theofidry** [comment]
@kcivey I actually didn't get the chance to try, but it should work.

**Comment by kcivey** [comment]
Yes, using `identity` works, but it seems horribly messy. Without it I get the "Could not lex the value" error when it runs into a `<`.

**Comment by theofidry** [comment]
Maybe the error message can be worked a bit, but I think it should stay an
error right of the bat.

What do you mean by messy?

**Comment by kcivey** [comment]
I thought the idea in #9 was to parse only things that looked like `<foo()>` as expressions, so that normal XML and HTML could be included in property values. As it is, it seems like a block of HTML has to have `<identity('` added at the start and `')>` at the end, and all single quotes in it have to be converted to `&apos;`. Alternatively, each tag in the text can be wrapped in `<identity('` and `')>`.

**Comment by theofidry** [comment]
#9 is quite old and a lot of new features have been added since then, but I'll look if there's a better way to use HTML

**Comment by theofidry** [comment]
I scrapped my head around it and I see only two solutions:

- have a special syntax to escape a full string, but it's gonna be ugly as you have the risk of having the escaped string containing the ending delimiter for the escape, so it won't escape properly the string
- escape manually everything (a bit tedious)
- have a faker provider function to generate your html (by far the easiest way)

**Comment by Eimantas123** [comment]
So still no way to leave string as it is without parsing it? I got a lot of symbols <]./ ant etc. in html, and I do not want to leave everything as it is. I get those:
Could not evaluate the expression "array (  
    0 => 'text',                           
  )".                                         
  because of []

**Comment by malutanpetronel** [comment]
text: >
            <identity('
            <p>Infiintare, modificare sau radiere firme.</p>
            ')> not working...

**Comment by theofidry** [comment]
@malutanpetronel as mentioned in https://github.com/nelmio/alice/issues/569#issuecomment-299711055 just go with a faker provider generating your HTML. Please do not stop commenting on issues that are 6 years old thanks

**Comment by malutanpetronel** [comment]
In fact I am always generating one of my sites starting from fixtures. It makes more sense for me to have it organized in yaml all the blog articles or products I have... until the HTML looks not able to make it work with:
Some_Blog_entry:
  title: whatever
  text:
            <identity('
            Some ul title
            <ul>
              <li>1</li>
               <li>2</li>
            </ul>
            ')>
            
Faker provider does not seems a solution and it should define the keys which stores the html I want to return for each entity defined ... ? I am wrong?
