### ISSUE TITLE
How can I have an auto increment id or field in yml file? 

### ISSUE THREAD

**Issue by napestershine** [nelmio/alice#574]

**Comment by theofidry** [comment]
You have several options:

- let your ORM do it when you are persisting your entities (2.x or 3.x it won't change, the only difference is that the ORM integration is no longer done in alice 3.x but you have libraries like https://github.com/theofidry/AliceDataFixtures to do it instead)
- create the ID at instantiation time: alice uses (and you can change it) your constructor so you can do it there
- have a custom Faker provider to do it yourself
