### ISSUE TITLE
Expected value of type "AdminBundle\Entity\Category" for association field "AdminBundle\Entity\Product#$category", got "integer" instead

### ISSUE THREAD

**Issue by napestershine** [nelmio/alice#575]
I am using nelmio alice bundle for doctrine fixtures
I have category and product entity
and I have generated 10 category with it
it's successful
now I want to generate random product data
but mapping of many to one from category to product is showing error
[Doctrine\ORM\ORMInvalidArgumentException] 
Expected value of type "AdminBundle\Entity\Category" for association field "AdminBundle\Entity\Product#$category", got "integer" instead.

here is gist
https://gist.github.com/napestershine/6ab83cf276ec63dd9a7c31d47359ee13

**Comment by theofidry** [comment]
The error looks pretty straightforward to me, you are setting an integer to `Product#category` [here](https://gist.github.com/napestershine/6ab83cf276ec63dd9a7c31d47359ee13#file-fixtures-yml-L16) where I guess you expect a Category instead instead, so you could use `@category*` for example (depends on your objects behind).

**Comment by theofidry** [comment]
@napestershine did that solve your issue?

**Comment by napestershine** [comment]
@theofidry  yes thanks :)
