### ISSUE TITLE
Prepare stable release

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#630]
Two betas are out now! There is still more changes to come which would call for other beta releases, but I would like to finish things as soon as possible. Once this is done, I believe we can let the project breath a few month before releasing the stable release.

@tshelburne I think pretty much everything has an issue now. Would you mind having a look at the issues and the doc and spot things that may be missing for the stable release, upgrade bath, doc issues... No urgency so this can wait a bit, but I would like to have a good check by someone else after so much changes.

**Comment by tshelburne** [comment]
At first glance, it all looks good to me. The good thing about those details is that they are low-hanging fruit for first-time contributors, so anything they want to fix or update can be welcomed immediately.

I might clean up some of the language for the upgrade path prior to release - let me know when that is getting close. I'm in the midst of a big feature build with work, so I might need to put it off for a bit.

**Comment by theofidry** [comment]
>I might clean up some of the language for the upgrade path prior to release

I'll try to work a lot of the doc in the coming days, so a check on the language would be welcome after that :P

I also would love if as the guy behind the second version, would be able to point out a few hardship on the upgrade path. But I guess this could require to actually try to upgrade a project from 2.x to 3.x which might take too much of your time though.

**Comment by tshelburne** [comment]
Sounds good. I've only ever done one project with Alice (PHP is rare for me), and I no longer have access to that code. I can reach out to my former client and suggest they check it out, though I'm doubtful they would have the resources to handle it right now.

Let me know when you feel the docs are "settled" and I'll just do a cleanup pass for minor grammatical stuff. I think the intention throughout is very clear.

**Comment by theofidry** [comment]
@tshelburne I've updated the doc. I would like you to do a quick check but otherwise I think we can do a release for both `3.0.0-beta.2` and `2.2.3`.

**Comment by tshelburne** [comment]
@theofidry I will review this weekend and push up a revision PR. Works?

**Comment by theofidry** [comment]
Perfect for me :) I'll find some time in 2-3 week to finish the
requirements for the stable release, mainly try Hoacompiler for the
lexer/parser (most of the issues are coming from this part) and the cache
layer which looks pretty good performance wise.
