### ISSUE TITLE
NotClonableTrait removed

### ISSUE THREAD

**Issue by pverdu** [nelmio/alice#631]
Since today we have a problem running composer install with the theofidry/alice-data-fixtures package. The following error is displayed when clearing Symfony's cache:

```
[RuntimeException]                                                           
  An error occurred when executing the "'cache:clear --no-warmup'" command:    
  Fatal error: Trait 'Nelmio\Alice\NotClonableTrait' not found in /vendor/theofidry/alice-data-fixtures/src/Load  
  er/MultiPassLoader.php on line 34                                            
  PHP Fatal error:  Trait 'Nelmio\Alice\NotClonableTrait' not found in /vendor/theofidry/alice-data-fixtures/src  
  /Loader/MultiPassLoader.php on line 34
```

What's the reason for the NotClonableTrait being removed? Any idea how i can fix this other then using v3.0.0-beta.1 ?

**Comment by theofidry** [comment]
Ah damn yes I need to update `theofidry/alice-data-fixtures` and `hautelook/alice-bundle`.

I updated the name in the `dev-master`, those two libraries are using the old name. I recommend you to simply update `nelmio/alice` to `@beta` instead of `@dev` in the meantime

**Comment by pverdu** [comment]
Thanks for the fast response. We will use @beta for now 👍

**Comment by theofidry** [comment]
If that solved the issue, don't forget to close the issue ;) Meanwhile I've updated the doc to use the beta instead of the dev version, it's definitely more stable that way.

**Comment by pverdu** [comment]
Great, thanks!

**Comment by pverdu** [comment]
This problem is back again. Even when using the @ beta tag. Did you solve the issue in ```theofidry/alice-data-fixtures``` and ```hautelook/alice-bundle``` like you mentioned on Nov 17th?

**Comment by theofidry** [comment]
Could you past me those versions? The problem should have occurred on `dev-master` only but I released a new tag yesterday. I've released a new tag for both `theofidry/alice-data-fixtures` and `hautelook/alice-bundle` which should have solved the problem

**Comment by pverdu** [comment]
I'm experiencing the issue with these versions:
```
"nelmio/alice": "3.0.0-beta.2",
"hautelook/alice-bundle": "2.0.0-beta-2",
"theofidry/alice-data-fixtures": "1.0.0-beta.3"
```

**Comment by theofidry** [comment]
can you try to update them all?

**Comment by pverdu** [comment]
I've used ```@beta``` on all of them. But that's when the problem occurred. 
I tried going back to the versions lke my previous comment.

**Comment by theofidry** [comment]
you need to update all of them at the same time, they are all outdated by 1 version. Otherwise reverting and staying on your lock deps should also be ok

**Comment by pverdu** [comment]
I'll check it out. Thanks

**Comment by pverdu** [comment]
Fixed! Thanks again

**Comment by theofidry** [comment]
Glad to help :)
