### ISSUE TITLE
<ipv4()>

### ISSUE THREAD

**Issue by nlemoine** [nelmio/alice#647]
Some Faker data types generate errors:

```
Fatal error: Uncaught Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\MalformedFunctionException: The value "<ipv4()>" contains an unclosed function. in /path/to/vendor/nelmio/alice/src/Throwable/Exception/FixtureBuilder/ExpressionLanguage/ExpressionLanguageExceptionFactory.php:59
```

**Comment by nlemoine** [comment]
`<ipv6()>` as well.

**Comment by theofidry** [comment]
I think this is related to #543

**Comment by nlemoine** [comment]
The issue you mentionned is closed, I'm assuming it is fixed but I'm still having the issue. Am I missing something?

```php
$objectSet = $loader->loadData([
    \Test\Entity\User::class => [
        'user{1..10}' => [
            'username' => '<username()>',
            'fullname' => '<firstName()> <lastName()>',
            'birthDate' => '<date()>',
            'ip' => '<ipv4()>',
        ],
    ],
]);
```

I still get the same error.

**Comment by theofidry** [comment]
Sorry https://github.com/nelmio/alice/issues/569: basically having a function where the content is escaped automatically.

**Comment by nlemoine** [comment]
Sorry, I still don't get it and believe it's not related. 

`<ipv4()>`, `<ipv6()>`, `< localIpv4()>` are providers from [fzaninotto/Faker](https://github.com/fzaninotto/Faker#fakerproviderinternet), right? So they should be available in Alice too? 

Actually, I think I figured out what's going wrong. I removed the digit at the end of the function name in Faker. Something like:
```php
    \Test\Entity\User::class => [
        'user{1..10}' => [
            'ip' => '<ipv()>',
        ],
    ],
```

And it works perfectly fine, I get an IPv4 address in my generating objects.

**Comment by theofidry** [comment]
>Actually, I think I figured out what's going wrong. I removed the digit at the end of the function 

Oh I see, indeed it's completely different then

**Comment by nlemoine** [comment]
👍 Thanks!

**Comment by theofidry** [comment]
You're welcome :)
