### ISSUE TITLE
how can I load yml file ?

### ISSUE THREAD

**Issue by mehmetsoylucom** [nelmio/alice#662]
How can I load YML file for last version of this bundle in Symfony3+ ?

**Comment by theofidry** [comment]
@mehmetsoylucom I'm not sure to follow, aren't [the examples](https://github.com/nelmio/alice#example) enough? If you are asking for the service name (it's true that it should be added to the doc), it's `nelmio_alice.file_loader` cf. https://github.com/nelmio/alice/blob/master/src/Bridge/Symfony/Resources/config/loader.xml.

**Comment by mehmetsoylucom** [comment]
My mistake, I'd check the old versions tutorial videos sorry. Thanks for your time.
