### ISSUE TITLE
Call referenced object method does not resolving

### ISSUE THREAD

**Issue by aistis-** [nelmio/alice#668]
I am trying to call a method from a referenced object

```
Entity/Random:
    random_1:
        sku: '@product_1->getSku()'
```

But I get an error in beta 3:

```
[Nelmio\Alice\Throwable\Exception\Generator\Resolver\ResolverNotFoundException]  
  No resolver found to resolve value "@product_1->getSku()". 
```

But it works `@product_1->sku` on private property.

**Comment by theofidry** [comment]
@aistis- can you give the which beta version is being used as well? (there is 3 beta releases) If you're not sure, the version hash will do

**Comment by aistis-** [comment]
```
"version": "v3.0.0-beta.3",
"reference": "3e53619db2590bfa72552e724cad1613a6c5c9c0"
```

**Comment by theofidry** [comment]
Thanks, I'll try to have a look shortly

**Comment by alekitto** [comment]
The expression is correctly parsed, but seems that a `FixtureMethodCallValue` is missing

**Comment by theofidry** [comment]
I'm surprised it's missing but that's how it looks.

**Comment by aistis-** [comment]
Is it something I should hook up manually?

**Comment by alekitto** [comment]
Workin' on it... I will submit a PR shortly

**Comment by theofidry** [comment]
@aistis- it should work on `3.x@dev` now :)

**Comment by aistis-** [comment]
Thank you!
