### ISSUE TITLE
Optional property with colon in YAML

### ISSUE THREAD

**Issue by clemf** [nelmio/alice#677]
I'm trying to use the optional notation with a percentage and default in a YAML fixture. The problem is that I can't use a colon in YAML, and I keep getting this error:

```
[Doctrine\ORM\ORMInvalidArgumentException]
  Expected value of type "Application\Entity" for association field "Application\Entity#$prop", got "string" instead.
```

If I do the optional syntax without default, it works fine:
```yaml
Application\Entity:
  prop: 10%? '@ref1'
```

If I try to add the default reference to the end of that with a colon, I get errors no matter what:
```yaml
Application\Entity:
  prop: 10%? '@ref1': '@ref2'
```

**Comment by theofidry** [comment]
Hi @clemf, could you tell me which version you are using please?

**Comment by clemf** [comment]
Hi @theofidry, I'm using version 2.2.2

**Comment by theofidry** [comment]
Can you try without the quotes? If this doesn't work, unless someone is willing to look into it I don't think this is gonna be fixed in 2.x. I'm only actively maintaining 3.x and I don't really have enough resources to fix much in 2.x :disappointed:

**Comment by clemf** [comment]
Is 3.x stable? I don't mind upgrading if it fixes this problem.

**Comment by theofidry** [comment]
Not yet. The API is rather stable, but there is still some internals not fixed yet. I guess the quotes trick didn't work? Alternatively, you could leverage a custom Faker provider, not the best thing ever but at least it would work.

**Comment by clemf** [comment]
I've tried every variation I could think of, using no quotes doesn't work because the symfony yaml parser dies on the 'at' symbol. I may make my own provider, thank you for the help.

**Comment by theofidry** [comment]
Did you try to quote the whole thing? Sf YAML parser should definitely not die on the `@` in this scenario

**Comment by clemf** [comment]
Ok I just tried quoting the whole string and it worked:
```
status: '85%? @visitComplete : @visitIncomplete'
```

I'm a little confused because I know I tried this before but obviously something else must have been going on. Thanks again for the help, I appreciate the work you put into this!

**Comment by theofidry** [comment]
Yeah, this happens when you have:

```
stdClass:
  dummy:
    foo: @bar # correct value should have been `'@bar'`
```

But that's a YAML thing, not much of alice there :)
