### ISSUE TITLE
Supported multiple arguments with nested calls

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#701]
What's supported:

- `<f(<g()>)>`
- `<f(<g()>, 'a')>`
- `<f(<g('a')>)>`

What's not:

- `<f(<g('b', 'e')>, 'd')>`

/cc @dantleech

**Comment by theofidry** [comment]
Note that I don't think this should be a blocker for the 3.0.0 release. But I think it's easier to solve the problem by tackling #601.

**Comment by marinoska** [comment]
Hi @theofidry I see it comes from the same code as #775 645 as parsing arguments relies on this regexp:
preg_match_all('/\[[^[]+\]|[^,\s]+/', $argumentsString, $argumentsList);
And I have no idea how to extract arguments correctly from such pattern as
<f(<g(<b()>, e)>, d, <c()>)>
using only regexps.
I can fix it looping over the symbols in the argument string but you might have already had such a method implemented in the alice code, don't you?

**Comment by theofidry** [comment]
I partially tackled that one by tokenizing functions (that's what the `FUNCTION_START__function__` was about: https://github.com/nelmio/alice/blob/master/tests/FixtureBuilder/ExpressionLanguage/Lexer/LexerIntegrationTest.php#L456).

That's clearly not enough and your fix may have helped. But as you said it's a problem were regexes are bad at. A cleaner solution would be #601 and #712. I believe @Hywan started some bits, but that's a significant piece of work for sure.

**Comment by theofidry** [comment]
I'll be closing this as IMO the real fix is #601.
