### ISSUE TITLE
Random selector should use numbers only

### ISSUE THREAD

**Issue by sourcerer-mike** [nelmio/alice#709]
Imagine this yml:

```
AbcBundle\Entity\CustomerId:
  customer_id_{1..9}:
    username: <username()>

AbcBundle\Entity\Customer:
  customer_{1..9}:
    username: '@customer_id_<current()>->username'
    uuid: '@customer_id_<current()>'
    email: <safeEmail()>
```

Because UUID, DDD and value objects ;-)
Now another entity comes around:

```
AbcBundle\Entity\Wallet:
  customer: <@customer_*>
```

This fails as the star `*` will randomly choose for "customer_1..9" or "customer_id_1..9" .
Yes I could rename them or use `<numberBetween(1,9)>` but this issue suggest another operator like `%` that is not that eager and only concerns about numbers. So `%` shrinks it down to "customer_1..9" which works for the Wallet-Entity.

**Comment by theofidry** [comment]
>This fails as the star * will randomly choose for "customer_1..9" or "customer_id_1..9" .
Yes I could rename them or use <numberBetween(1,9)> but this issue suggest another operator like % that is not that eager and only concerns about numbers. So % shrinks it down to "customer_1..9" which works for the Wallet-Entity.

For now the star operator is the only one and I'm not sure about adding another one: the syntax would need to be discussed it would require not to be overly complex. So for now renaming your fixtures is the easiest way to go. Also maybe #672 would circumvent that issue.
