### ISSUE TITLE
The ReferenceEscaperLexer will not escape when there is a number before `@`.

### ISSUE THREAD

**Issue by alekslauda** [nelmio/alice#724]
Using emails like `email1@example.com` are not escaped by the ReferenceEscaperLexer.

https://github.com/nelmio/alice/blob/master/src/FixtureBuilder/ExpressionLanguage/Lexer/ReferenceEscaperLexer.php#L47

**Comment by theofidry** [comment]
@alekslauda would you mind opening a PR to fix it? I don't think this should be too hard

**Comment by theofidry** [comment]
Note that it's a known issue and can be fixed by escaping it manually: `email1\@example.com`

**Comment by theofidry** [comment]
I've just tested it on master and seems to work. Not sure if your case is more complex or if it has been fixed in the meantime. If you still encounter the problem please open a new issue with the failing email :)
