### ISSUE TITLE
Link to "Reuse generated data using objects value" is missing

### ISSUE THREAD

**Issue by sensorario** [nelmio/alice#743]
Consulting [this documentation page](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md) I've seen that the link to "Reuse generated data using objects value" is missing. Well, ... the link is not missing, but the documentation. So, ... I need to reuse generated data from a SQL DUMP and I need to read this missing documentation.

**Comment by theofidry** [comment]
Actually the link should be removed as the content became obsolete as of 3.0.0: https://github.com/nelmio/alice/commit/4134579c950108564c9c47679be87a837898c062#diff-21790792d116b910b2a565c26d80b95d
