### ISSUE TITLE
Unique Constraints on several fields

### ISSUE THREAD

**Issue by Zayon** [nelmio/alice#744]
Hi,

Is it possible to have a unique constraint on multiple fields ? 

For example 

```
Nelmio\Entity\User:
    user{1..10}:
        lastname (unique_some_id): '<lastname()>'
        firstname (unique_some_id): '<firstname()>'
```
 
So it prevent 2 users to have the same lastname AND firstname but they can have the same lastname or the same firstname

Thanks.

**Comment by theofidry** [comment]
Composite unique fields are not supported atm, but if it's for such a specific case you could implement it yourself by using a custom faker provider

**Comment by Zayon** [comment]
Thanks, I'll take a look at this, is there any doc on how to do that ?

**Comment by theofidry** [comment]
Yep, you can find some doc here: https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers (it's a similar path for 2.x as well in case you're not using 3.x)
