### ISSUE TITLE
Escaping value 

### ISSUE THREAD

**Issue by erichard** [nelmio/alice#749]
I haven't found in the doc but how can I escape specials characters like `$` or `@` ?

My use case is to pass a bcrypt hash to create some fake user. Alice except to find variable with the `$` in the hash.

**Comment by theofidry** [comment]
The backslash `\` so `\$` or `\@`. It should be in https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#expression-language-dsl, if not would you mind opening a PR to add a mention of it?

**Comment by magnetik** [comment]
I'm using alice with some strange looking strings like this : `$<$<$o$3f0wdf$>$f3fno$000ツ$>$09FSto$>`.

I've tried to escape both the `<` and `$`, but it does not seems to be enough. When using `'\$\<\$\<\$o\$3f0wdf\$>\$f3fno\$000ツ\$>\$09FSto\$>'` I have: 

```
  [Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\LexException]
  Could not lex the value ">\$f3fno\$000ツ\$>\$09FSto\$>".
```

**Comment by theofidry** [comment]
can you try `<("$<$<$o$3f0wdf$>$f3fno$000ツ$>$09FSto$>")>`? Otherwise it might be simpler to store those strings in a custom faker provider and use that instead
