### ISSUE TITLE
Mathematical operators and decimals

### ISSUE THREAD

**Issue by Ziiweb** [nelmio/alice#75]
Is it possible using mathematical operators? For example: $field1 + $field2
Is it possible generating float numbers in a range? For example:  

```
<numberBetween(150.0, 1500.0)>

 Im using this but it only generate integer numbers.

```

**Comment by nass600** [comment]
Any plan on adding such eval function? 
That could be a nice feature.

**Comment by Seldaek** [comment]
There is the identity provider now which acts as sort of an eval call: use `<identity(1 + 1)>` or the short `<(1 + 1)>`

**Comment by nass600** [comment]
That's right. Thank you @Seldaek.
Maybe I miss something in the documentation to figure out the possibility of making math operations or evaluate expressions with this provider so the name `identity` is not quite semantic for this purpose

**Comment by Seldaek** [comment]
I added some more content to https://github.com/nelmio/alice/blob/master/README.md#default-providers including eval so if people search for that hopefully they'll find it :)

**Comment by nass600** [comment]
Awesome!

Thank you
