### ISSUE TITLE
"Breaking changes between Alice 2.x and 3.0" link in documentation is broken

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#759]
"12.i Breaking changes between Alice 2.x and 3.0" is linking to [here](https://github.com/nelmio/alice/blob/master/breaking-changes-between-alice-2x-and-30) but should link to [here](https://github.com/nelmio/alice/blob/master/UPGRADE.md)

**Comment by theofidry** [comment]
Fixed, thanks
