### ISSUE TITLE
ReflectionPropertyAccessor can access protected but not private properties of an abstract class

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#762]
Title is self explanatory. I get the exception `Could not hydrate the property "latitude" of the object "TestGeographicLocation" (class: Location\TestGeographicLocation).` if trying to hyrdate private properties but it works when using protected/public properties.

I am using a Loader that extends from NativeLoader so that it uses the ReflectionPropertyAccessor:

```php
class ReflectionLoader extends NativeLoader
{
    protected function createPropertyAccessor(): PropertyAccessorInterface
    {
        return new ReflectionPropertyAccessor(parent::createPropertyAccessor());
    }
}
```

And the class looks like:

```php
abstract class GeographicLocation
{
    private $latitude;
    private $longitude;

    public function __construct($latitude, $longitude)
    {
        $this->latitude = $latitude;
        $this->longitude = $longitude;
    }
}
```

And a concrete class exmaple:

```php
class TestGeographicLocation extends GeographicLocation
{
}
```

It only happens with children of abstract classes I believe but it was working in Alice 2.x so the reflection property accessor may need updating to support this like it used to be supported, not sure.

**Comment by theofidry** [comment]
Indeed, would you mind opening a PR for it? I believe this can be fixed by changing [those lines](https://github.com/nelmio/alice/blob/master/src/PropertyAccess/ReflectionPropertyAccessor.php#L117) by checking the parent properties (recursively as several parents may be given)

**Comment by jeremy-smith-maco** [comment]
#763 ready

**Comment by theofidry** [comment]
Checking this again with a clear mind, I'm not convinced this is the solution. Accessing directly an object property is one thing, accessing a *parent* private properties another.

In your example I see two simple solutions which are way less hacky:

- Make those properties `protected` which reduces the level of encapsulation but it allows you to do what you want
- Don't rely on this property accessor and use the constructor instead:

```yaml
TestGeographicLocation:
  dummy:
    __construct:
      - '<latitude()>'
      - '<longitude()>'
```

Even though this was working in 2.x, I think there was a bit too much magic in 2.x sometimes with things that shouldn't be done. This may be one of those

**Comment by jeremy-smith-maco** [comment]
Those would both work but I still think you should be able to access parent private properties. If you're extending from a class, you should be able to specify the properties for that class in a fixture file even if the parent property is private. In some cases people may not want to run the constructor for the class and just want the values set.

I mean ultimately it's up to you but I think you should be able to just directly set parent private properties through the fixture file like in 2.x.

**Comment by jeremy-smith-maco** [comment]
Your second option didn't quite work. This is how we have it setup where `DtoObject` is just a custom DTO class we have and `$this->loader` is a class we have that ultimately runs `NativeLoader->loadFile()`:

**Fixture**
```
Namespace\DtoObject:
  Args:
    latitude: <latitude()>
    longitude: <longitude()>

Namespace\TestGeographicLocation: # extends from abstract class GeographicLocation with private properties
  TestGeographicLocation:
    __construct:
      - '@Args->latitude'
      - '@Args->longitude'
```

**Test**
```
public function testConstructor()
    {
        $fixtures = $this->loader->load('ConstructorTest.yml')->getObjects();
        $expected = $fixtures['TestGeographicLocation'];
        $latitude = $fixtures['Args']['latitude'];
        $longitude = $fixtures['Args']['longitude'];
        $geoLoc = new TestGeographicLocation($latitude, $longitude);
        $this->assertEquals($latitude, $geoLoc->latitude());
        $this->assertEquals($longitude, $geoLoc->longitude());
        $this->assertEquals($expected, $geoLoc);
    }
```

**Error**
`Failed asserting that two objects are equal.` They have different longitude/latitude values.

**Comment by theofidry** [comment]
Your test as it is should work. The point of private properties with inheritance is to guarantee you cannot touch them, touching them is opening up the door to very very weird behaviour.

If your piece of code above is failing, could you try to isolate it? This looks really suspicious, I mean it clearly shouldn't fail

**Comment by jeremy-smith-maco** [comment]
I can try and isolate it. How are users meant to test abstract classes with private properties without changing it to protected/public?

**Comment by theofidry** [comment]
You're not supposed to or rather you test their behaviour in the child class, that's the point of encapsulating it that way

**Comment by jeremy-smith-maco** [comment]
It seems like a lot more work without having the ability to set the private properties of a class. We have hundreds of classes with private properties and without having the ability to set them in our fixtures we would have a lot of extra code to construct these objects as well as set private properties through setter methods.

Even if you don't end up allowing private properties to be set we will probably use a custom property accessor that allows us to do so since it saves a lot of extra code just to get the fixtures how we require them for our tests to be run.

**Comment by theofidry** [comment]
I just don't think that's the way to go. If you have private properties in a parent class, it means you have a way to set those properties through the child class otherwise something looks fishy.

To be clear, it may be a legitimate answer for your case to set directly the private properties of a parent class. I don't think it's a good thing to do, but it may be the most cost-effective one. If that's the case, I do think however this should be a in-house solution (there is several extension points to register a custom accessor) instead of being added to the core which is very likely to lead to more abuse and wtf.

**Comment by jeremy-smith-maco** [comment]
It may well have to be an in-house solution for us. The main use for our fixtures is to have ready to go objects constructed for us to test our code with. Seems fairly redundant in those cases if we have to construct the objects and set all the properties we need which would just create a lot of extra code when we could just set the properties straight from the fixtures.

**Comment by theofidry** [comment]
Unless I missed something, as in the first example shown, you should be able to easily set the values of those private properties

**Comment by jeremy-smith-maco** [comment]
Yeah that is just a basic example.

**Comment by theofidry** [comment]
Back to this. I still don't think that's a good solution. For your specific use case, having a custom hydrator is the way to go, but having one in the core is IMO a bad idea. One reason 3.x has been refactored as heavily is because 2.x was way too permissive and was creating too many wtf. I'm not keen to do that again for 3.x.

TL:DR; Rolling your own thing for dirty stuff is ok :)

**Comment by jeremy-smith-maco** [comment]
We will be trying to avoid it now in our tests but will see if we actually need it once we re-factor our tests for Alice 3.x.
