### ISSUE TITLE
Cannot extend from a template without setting a property

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#764]
```
Some\Class:
	SomeClass (template):
		someValue: 1
		
Some\Class:
	SomeOtherClass (extends SomeClass):
		// Set no properties
```

Gives exception:

`Argument 4 passed to Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\FixtureDenormalizerRegistry::denormalize() must be of the type array, null given, called in /blah/blah/blah/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SimpleFixtureBagDenormalizer.php on line 70`

This works:

```
Some\Class:
	SomeClass (template):
		someValue: 1
		
Some\Class:
	SomeOtherClass (extends SomeClass):
		someValue: 2
```

Was previously working in 2.x.

**Comment by theofidry** [comment]
I'm even surprised it just parses as YAML, a more correct way would be:

```yaml
Some\Class:
	SomeClass (template):
		someValue: 1
		
Some\Class:
	SomeOtherClass (extends SomeClass): ~
```

For which we could update the code to allow that or deprecate that behaviour in 2.x (I'm more in favour of the later). An easy fix is:

```yaml
Some\Class:
	SomeClass (template):
		someValue: 1
		
Some\Class:
	SomeOtherClass (extends SomeClass): {}
```

**Comment by jeremy-smith-maco** [comment]
The first code block didn't work. The second one with the empty curly braces did!

**Comment by theofidry** [comment]
Yeah, I don't think we allowed that. We could either allow it in 3.x or update 2.x to add a deprecation saying `null` is no longer accepted in this case

**Comment by jeremy-smith-maco** [comment]
Deprecating it in 2.x would probably be better and people can just use the `{}` in 3.x. The tilde did not work though.

**Comment by theofidry** [comment]
`~` is equivalent of `null` in YAML :)

**Comment by jeremy-smith-maco** [comment]
Ah, so `~` would work in 2.x but `{}` is required in 3.x.

**Comment by theofidry** [comment]
Yep
