### ISSUE TITLE
Getting exception when trying to construct a Mockery object

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#768]
Exception: `Instantiated fixture was expected to be an instance of "Mockery". Got "Mockery_2_Namespace_Object" instead.`

When Mockery instantiates an object it gets a different class name which Alice thinks is incorrect because you shouldn't be able to specify one class name and instantiate a different one but in the case of Mockery it makes sense so something needs to happen with the class check when it is instantiated to allow behaviour like this for legit cases where the class does need to change.

**Comment by theofidry** [comment]
I think we should change the class check for an instance of instead. It makes more sense for proxies or factories.

@jeremy-smith-maco would you mind opening a PR for it? This one should be relatively easy

**Comment by jeremy-smith-maco** [comment]
Sure thing.

**Comment by jeremy-smith-maco** [comment]
It already does an `instanceof` check: `if (false === $instance instanceof $class)`. Mockery is failing because it requires the factory method `mock` but that method produces an instance of `Mockery\MockInterface` which is what causes the exception because it's not actually an instance of the specified class.

**Comment by theofidry** [comment]
ah, but then you are specifying the wrong class:

```yaml
Mockery\MockInterface:
    dummy_mock
        __factory: { 'Mockery::mock': [] }
```

**Comment by jeremy-smith-maco** [comment]
Yep, that is correct haha.
