### ISSUE TITLE
Column 'ancestor' cannot be null

### ISSUE THREAD

**Issue by kariolos** [nelmio/alice#773]
Hello , I am having problem setting up alice for entities with parent and childrens.

```
productCategoryParent_{1..3}:
      name: productCategory_parent_<current()>
      createdAt: <datetimeBetween('-5 days', 'now')>
      updatedAt: <datetimeBetween('-5 days', 'now')>

productCategory_{1..30}:
      name: productCategory_<current()>
      parent: '@productCategoryParent_*'
      createdAt: <datetimeBetween('-5 days', 'now')>
      updatedAt: <datetimeBetween('-5 days', 'now')>
```
When I run the fixture I get 
``SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ancestor' cannot be null``

In my orm.xml file I have this:
```
<many-to-one field="parent" target-entity="ProductCategory" inversed-by="children">
            <join-column name="parent_id" referenced-column-name="id" nullable="true" />
            <gedmo:tree-parent />
        </many-to-one>
        <one-to-many field="children" target-entity="ProductCategory" mapped-by="parent" />
```

**Comment by theofidry** [comment]
It's possible that your setters doesn't set the relationship the other way, I recommend you to take a look at the generated PHP objects to see if they are set as you expect them to be

**Comment by theofidry** [comment]
Closing for now. Feel free to open a new issue once you find something a bit more specific

**Comment by kariolos** [comment]
When I insert data through the form everything works fine,so I think the objects and mapping are fine.
The weird thing is that I have another `Entity` with `ancestors `and `descendants` and don't get that error.

Anyway use this workaround but I was curious why this is happening.

- Drop Database
- Create Database
- Update Schema
- Set the ancestor field to allow `null `on `productCategoryClosure `table
- Load Fixtures
- Set the ancestor field back to `not null`

**Comment by theofidry** [comment]
that does sound weird, but I can't tell what's the issue. Maybe try to look how the properties are actually being set and how they can be null. Also note that it changes depending on which version you are using

**Comment by kariolos** [comment]
- doctrine/doctrine-fixtures-bundle    2.3.0 
- doctrine/orm                         v2.5.6  
- fzaninotto/faker   v1.6.0
- gedmo/doctrine-extensions    v2.4.30
- hautelook/alice-bundle   v1.4.1
- nelmio/alice                         v2.3.1

**Comment by theofidry** [comment]
It may set the property directly if it cannot via the setter in 2.x, so watch out on how the property is actually set

**Comment by iBasit** [comment]
I'm getting same error. 

```
        created:            <dateTimeBetween('-12 months', 'now')>
```

**Comment by theofidry** [comment]
@iBasit I'm sorry but I cannot really help without more informations. As I said at some point the easiest way to go is to look at the generated objects to see what is wrong and eventually check how the properties are populated( see Populator in 2.x or Hydrator in 3.x)

**Comment by iBasit** [comment]
This error is coming on 3-dev version. 
 
Error is on `dateTimeBetween` parsing, when it is parsing the values,  it takes single or double quotes into the actual values.  Lets take following example:

if values are  `<dateTimeBetween('-12 months', 'now')>` it will take value `-12 months` as `'-12 months` and or `'-12 months,  now`. 

You will either get time zone error or the above error.

**Comment by theofidry** [comment]
@iBasit could you try to reproduce it by adding a test to `LoaderIntegrationTest`?

**Comment by iBasit** [comment]
https://github.com/nelmio/alice/blob/master/tests/Loader/LoaderIntegrationTest.php#L448

You can add quick test if you like, not sure why there is `strrev ` function being used on the test, seems so pointless. 

But I found the solution to this, not a proper solution, but remove space from the string, then it will work, with space it will not parse proper and throw errors.

**Comment by theofidry** [comment]
>You can add quick test if you like

Well, right now I cannot which is why I'm asking :)

>not sure why there is strrev function being used on the test, seems so pointless.

A simple test to ensure a call to a PHP native function works

**Comment by theofidry** [comment]
@kariolos I can try to have a look at it later in 3.x but for 2.x there's nothing I can do. PRs & patches are still welcome, but I'm not willing to actively work on that version anymore

**Comment by iBasit** [comment]
2.x is working fine, all my fixtures were working fine on 2.x, only 3.x needs fixing :)

**Comment by theofidry** [comment]
@iBasit @kariolos is in 2.x not 3.x so it looks a bit different
