### ISSUE TITLE
3.x — as no identity/no id values set. It cannot be added to the identity map.

### ISSUE THREAD

**Issue by iBasit** [nelmio/alice#777]
I have two entities.

user (entity 1)

- id  (primary key)
- name

detail (entity 2)

- user (primary key, which is from user entity)
- address

When running fixtures with 

    detail_{1..10}:
        user:             "@user_<current()>"

I get the following error

> [Doctrine\ORM\ORMInvalidArgumentException]                                                                       
>   The given entity of type 'AppBundle\Entity\Detail' (AppBundle\Entity\Detail@0000000007f1464d000000006748ef3  
>   e) has no identity/no id values set. It cannot be added to the identity map.    

Please note that this was working fine on `2.x`

Stackoverflow links
https://stackoverflow.com/a/30404503/75799

**Comment by theofidry** [comment]
That sounds weird. There is indeed a difference at the persistence level for Alice 3.x: it has been moved to theofidry/AliceDataFixtures, but as you can see, it doesn't do much: https://github.com/theofidry/AliceDataFixtures/blob/master/src/Loader/PersisterLoader.php#L77.

Did you use a special config option in 2.x or something?

**Comment by iBasit** [comment]
Nope, nothing special other than Custom Faker providers, which was easily switched over with new implementation. 

Not sure what to do for above error, which is very important to fix. Any suggestions?

**Comment by theofidry** [comment]
I've never seen that error before, did you find a way to reproduce it somewhere?

**Comment by iBasit** [comment]
I have reproduce the problem at https://github.com/iBasit/alice-problem.git

you can download and quickly run and check the output.  it has minimum files required. 

I hope you can help on this. Thank you

**Comment by iBasit** [comment]
Any luck how I can fix this?

**Comment by theofidry** [comment]
Soz I'm a bit busy this w/we with my moving I couldn't check yet.

**Comment by iBasit** [comment]
**Off Topic**
That must be soo much hassle arranging dates and movers van and help.  If you haven't booked any van, then try https://www.deliveryd2d.com they have good customer service, which helps a lot, they take care of everything on low cost. 

**Back on Topic**
Please take a look at it when you get a chance, our work is being held because of this deadlock. Anyway, Thank you and appreciate all your help.

**Comment by theofidry** [comment]
>Off Topic

Thanks I'll check it out :)

>Back on Topic

I'll try to have a proper look in the evening, but otherwise it will take longer. 

Is it expected that `Detail` has no id? that looks weird

**Comment by iBasit** [comment]
Thanks.

Yes detail is using parent primary key as the primary key, rather than its own. It's one to one relationship.

**Comment by iBasit** [comment]
I did have a look at the doctrine2 issue before I posted here, they head phpdoc error.

I was trying to dig in and I found the error is generated by following line
https://github.com/theofidry/AliceDataFixtures/blob/788b8364e5e7fdd527376c06863c4dce2550b456/src/Loader/PersisterLoader.php#L85

I'm not sure how to fix this issue, this issue did not exist previously on 2.x

**Comment by theofidry** [comment]
Ok I pinned down the issue.

The issue is really what is described in the [StackOverflow question](https://stackoverflow.com/questions/39567907/doctrine-prevent-double-flush-on-using-identity-through-foreign-entity). In you case what you need to do in raw PHP is:

```php
$manager->persist($user);
$manager->flush();

$manager->persist($detail);
$manager->flush();
```

Now to make it work, there is several solutions. A first one would be to create your own `PersisterLoader`:

```php
use AppBundle\Entity\Detail;
use Fidry\AliceDataFixtures\LoaderInterface;
use Fidry\AliceDataFixtures\Persistence\PersisterAwareInterface;
use Fidry\AliceDataFixtures\Persistence\PersisterInterface;
use Fidry\AliceDataFixtures\Persistence\PurgeMode;
use Fidry\AliceDataFixtures\ProcessorInterface;
use Nelmio\Alice\IsAServiceTrait;

/**
 * Loader decorating another loader to add a persistence layer.
 *
 * @author Jordi Boggiano <j.boggiano@seld.be>
 * @author Théo FIDRY <theo.fidry@gmail.com>
 *
 * @final
 */
/*final*/ class PersisterLoader implements LoaderInterface, PersisterAwareInterface
{
    use IsAServiceTrait;

    /**
     * @var LoaderInterface
     */
    private $loader;

    /**
     * @var PersisterInterface
     */
    private $persister;

    /**
     * @var ProcessorInterface[]
     */
    private $processors;

    /**
     * @param LoaderInterface      $decoratedLoader
     * @param PersisterInterface   $persister
     * @param ProcessorInterface[] $processors
     */
    public function __construct(LoaderInterface $decoratedLoader, PersisterInterface $persister, array $processors)
    {
        $this->loader = $decoratedLoader;
        $this->persister = $persister;
        $this->processors = (function (ProcessorInterface ...$processors) {
            return $processors;
        })(...$processors);
    }

    /**
     * @inheritdoc
     */
    public function withPersister(PersisterInterface $persister): self
    {
        return new self($this->loader, $persister, $this->processors);
    }

    /**
     * Pre process, persist and post process each object loaded.
     *
     * {@inheritdoc}
     */
    public function load(array $fixturesFiles, array $parameters = [], array $objects = [], PurgeMode $purgeMode = null): array
    {
        $objects = $this->loader->load($fixturesFiles, $parameters, $objects, $purgeMode);

        foreach ($objects as $id => $object) {
            if ($object instanceof Detail) {
                continue;   // Persist it at the second pass
            }

            foreach ($this->processors as $processor) {
                $processor->preProcess($id, $object);
            }
            $this->persister->persist($object);
        }
        $this->persister->flush();

        foreach ($objects as $id => $object) {
            if (!$object instanceof Detail) {
                continue;
            }

            foreach ($this->processors as $processor) {
                $processor->preProcess($id, $object);
            }
            $this->persister->persist($object);
        }
        $this->persister->flush();

        foreach ($objects as $id => $object) {
            foreach ($this->processors as $processor) {
                $processor->postProcess($id, $object);
            }
        }

        return $objects;
    }
}
```

As you can see there is two `persist()` pass. However this is not enough. Indeed the Doctrine persister `ObjectManagerPersister` does a `clear()` in the flush to mitigate some memory leaks. So that means you need to override it to not call the `clear()` call as otherwise when persisting the details, the `User` entity attached will be perceived as a new entity.

A cleaner way although a bit more hacky woud be to create your own persister and skip the `Detail` entity in the `persist()` and create a post-processor (they are executed just after the flush) to persist the details.

This IMO is a workaround however. It would be nice to tackle the issue at the core, but it requires to considerate more complex scenarios where you have a chain of 1to1 relationships for example.

**Comment by theofidry** [comment]
Also note that if it was working in 2.x, that was by cheer luck.

**Comment by iBasit** [comment]
I have tried the second solution with the above code. I got following error stating user is new entity and not the one that has already been persist/saved.

![image](https://user-images.githubusercontent.com/34341/29320932-bcbdfe96-81d0-11e7-89e0-7db1ac0817e6.png)

**Comment by theofidry** [comment]
You missed that bit:

>However this is not enough. Indeed the Doctrine persister ObjectManagerPersister does a clear() in the flush to mitigate some memory leaks. So that means you need to override it to not call the clear() call as otherwise when persisting the details, the User entity attached will be perceived as a new entity.

But I would rather recommend the second solution

**Comment by iBasit** [comment]
I have overridden the class, but on run time, it loads the overridden and then after loading all the files it loads the old `ObjectManagerPersister` in the class. 

I have committed the changes. Do you think there is still some other bug?

**Comment by theofidry** [comment]
I need to take a proper look but I can't right now. If you override the service (i.e. declare you own service with the same service ID) it should work though.

**Comment by iBasit** [comment]
I agree, If you check following service file which I committed on the the alice-problem git repo, it has same service id. it loads fine on first load, but on second load it takes the old service..

service names
https://github.com/iBasit/alice-problem/commit/ef0cf73767f64d44e721c347768303f78b5432d8#diff-1728bfc1c274f341afc1a0275fca694d

**Comment by theofidry** [comment]
What do you mean by second load? Just in case also double check you deleted the container

**Comment by iBasit** [comment]
Sorry, what I mean is when it runs `PersisterLoader` it loads the new `ObjectManagerPersister` fine, but after loading all the datafixtures `yml` files, then it loads old `ObjectManagerPersister`, which uses `persist` and `flush` method.  Not sure why its loading old `ObjectManagerPersister` after it has already loaded the new `ObjectManagerPersister`.

**Comment by theofidry** [comment]
Sorry I forgot to post my message yesterday, see https://github.com/theofidry/alice-problem/commit/14bf2e0c2b8379ee0950a4a6aba35044a9681838.

Arguably there is some design issues:

- Missing alias for persister in FidryAliceDataFixtures to easily override it
- Add a persister factory for e.g. DoctrineOrmLoader in HautelookAliceBundle

Can't do much atm, but PRs are welcome :)

**Comment by iBasit** [comment]
Thank you so much, this helped a lot.  I had an issue with purger also, but manage to fix it.

**Comment by theofidry** [comment]
Let's keep the issue open as they are some changes to be made to make it easier :)

**Comment by iBasit** [comment]
Great!  — Just heads up, if there is a relationship in sync with detail to other entities, this fix will effect them also, so one would have to persist them as well. 

My example was `user` to `affiliate` and then `affiliate sub relationships`

**Comment by theofidry** [comment]
Moved the issue to the right repository: https://github.com/theofidry/AliceDataFixtures/issues/50 :)

**Comment by Mahmoudz** [comment]
**Here's a quick solution:**

Edit the fixtures loader to skip certain keys, like this embeddable `Point`:

```yaml
Infrastructure\Persistence\Doctrine\Extension\Point:
  local__blablabla:
    __construct: [53.2164587474, -0.9746272299]
```

```php
    private function persistFixtures(array $fixtures, ObjectManager $objectManager)
    {
        $loader    = new AppNativeLoader();
        $objectSet = $loader->loadFiles($fixtures);

        foreach ($objectSet->getObjects() as $key => $object)
        {
            $this->addReference($key, $object);

            // skip keys that starts with 'local__' mainly used for embeddables
            if ($this->isLocal($key) === false)
            {
                $objectManager->persist($object);
            }
        }
        // Note: the flashing happens later when all fixtures (ORM/ODM) are persisted
    }

    private function isLocal($key) : bool
    {
        return strpos($key, 'local__') === 0;
    }
```

Here I choose `local__` but you can customise it.
