### ISSUE TITLE
Email address causes Alice to look for a fixture file

### ISSUE THREAD

**Issue by simshaun** [nelmio/alice#780]
Odd problem. I was on 3.0.0-RC.1 and tried updating to dev-master, but it still bugs out.

My fixture file is as follows, somewhat matching the [example provided in the docs](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#yaml):

```
AppBundle\Entity\User:
    user_disabled_1:
        enabled: false
        firstName: John
        lastName: Doe
        email: disabled1@example.com
        plainPassword: 123456
```

and trying to load fixtures results in:

```
[Fidry\AliceDataFixtures\Exception\MaxPassReachedException]
 Loading files limit of 15 reached. Could not load the following files:
  /var/www/cms/backend/src/PlatformBundle/Resources/fixtures/orm/user_disabled.yml:
   - Nelmio\Alice\Throwable\Exception\Generator\Resolver\FixtureNotFoundException: Could not find the fixture "example.com". in /var/www/cms/backend/vendor/nelmio/alice/src/Throwable/Exception/Generator/Resolver/FixtureNotFoundExceptionFactory.php:23
```

Setting a breakpoint and stepping through, I see that the email property is being parsed into a ListValue containing 2 values:
```
0: "disabled1"
1: Nelmio\Alice\Definition\Value\FixtureReferenceValue:
    reference: "example.com"
```

Trying to figure out why it's doing that,

1. `UniqueValueDenormalizer::denormalize` is called with `disabled1@example.com`
2. `SimpleValueDenormalizer::denormalize` is called with `disabled1@example.com`
3. `SimpleValueDenormalizer::parseValue` is called with `disabled1@example.com`
4. `FunctionFixtureReferenceParser::parse` is called with `disabled1@example.com`
5. `StringMergerParser::parse` is called with `disabled1@example.com`
6. `SimpleParser::parse` is called with `disabled1@example.com`
7. `EmptyValueLexer::lex` is called with `disabled1@example.com`
8. `ReferenceEscaperLexer::lex` is called with `disabled1@example.com`
9. `GlobalPatternsLexer::lex` is called with `disabled1@example.com`
10. `FunctionLexer::lex` is called with  `disabled1@example.com`
11. `SubPatternsLexer::lex` is called with  `disabled1@example.com`
12. !!!!! This lexer turns `disabled1@example.com` into 3 tokens: 

    ```
    0: disabled  [STRING_TYPE]
    1: 1  [STRING_TYPE]
    2: @example.com  [SIMPLE_REFERENCE_TYPE]
    ```

I think this is ultimately caused by the regex pattern in `ReferenceEscaperLexer` not matching against `disabled1@example.com`. 

The current pattern is `(\p{L})@` which matches against any letter, but does not include numbers. I think the pattern needs to be `(\p{L}|\p{N})@`.

See https://regex101.com/r/4yUIOk/1 for failing regex test.
See https://regex101.com/r/d8VSyt/1 for working regex test.

**Comment by theofidry** [comment]
regexes for emails are difficult, I think the easiest way is either to check if we have non empty a `STRING_TYPE` token immediately followed by a `SIMPLE_REFERENCE_TYPE`, we could transform the reference into a string.

Alternatively just escape it: `disabled1\@example.com`

**Comment by simshaun** [comment]
> regexes for emails are difficult, I think the easiest way is either to check if we have non empty a STRING_TYPE token immediately followed by a SIMPLE_REFERENCE_TYPE, we could transform the reference into a string.

This would be a new lexer that comes after `SubPatternsLexer`, right, or would it just be a part of the `SubPatternsLexer`?

> Alternatively just escape it: disabled1\\@example.com

I'll have to try this tomorrow. Not sure I like having to escape the @ symbol, but if it works it works.

**Comment by theofidry** [comment]
>This would be a new lexer that comes after SubPatternsLexer, right, or would it just be a part of the SubPatternsLexer?

A simpler way I think would be to decorate the lexer and modify the list of tokens accordingly. IIRC this is already done somewhere to transform all the successive `STRING_TYPE` tokens into one. I don't remember exactly where, but that's within the lexer for sure

**Comment by simshaun** [comment]
Looking at this issue again, couldn't the regex just be changed to `(.+?)@`?

The goal is to escape any @ symbol that isn't at the beginning of a string. It works against the following lines:

![image](https://user-images.githubusercontent.com/379519/30140825-2f9e73fc-9345-11e7-95f7-2fc4dd6e176f.png)

**Comment by simshaun** [comment]
Turns out the string merging is done in the `StringMergerParser` instead of a lexer.

I created a PR that does what I think you're saying. It seems kinda complicated compared to changing the regex in `ReferenceEscaperLexer` to check for numbers too, but I leave that decision up to you.
