### ISSUE TITLE
MalformedFunctionException when using two functions and text

### ISSUE THREAD

**Issue by mrmkrs** [nelmio/alice#781]
Hi,
I found some constructions where the parsing / tokenizing stuff does not work properly and throws an MalformedFunctionException.

```yaml
Some\Class:
  fullName: '<nl_NL:lastName()> test <nl_NL:firstName()>'
```

The exception:
[Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\MalformedFunctionException]
  The value ")>)> test <aliceTokenizedFunction(<nl_NL:firstName(" contains an unclosed function.

Also broken:
```yaml
Some\Class:
  fullName: 'somestring <current()> <nl_NL:firstName()>'
```
 [Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\MalformedFunctionException]
  The value "somestring <current()> <nl_NL:firstName()>" contains an unclosed function.

This does work:

```yaml
Some\Class:
  fullName: '<nl_NL:lastName()> <current()>'
```

And this does also work:
```yaml
Some\Class:
  fullName: '<nl_NL:lastName()> <current()>somestring'
```

And this does also work:
```yaml
Some\Class:
  fullName: 'somestring <nl_NL:lastName()> <current()>'
```

**Comment by theofidry** [comment]
I think it's the localised call that fucks up a bit things. But the real fix is in #601 unless you are ready to patch the current lexer & parser
