### ISSUE TITLE
Can't use multiple brackets in strings?

### ISSUE THREAD

**Issue by msypes** [nelmio/alice#782]
Similar to [another issue with percentage signs](https://github.com/nelmio/alice/issues/665), I'm getting errors trying to use strings with multiple brackets in them.
I've got `"nelmio/alice": "v3.0.0-RC.1"` 
and some fixtures with values like this: '[[1,4],[2,5]]', which throws

`[Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\LexException]  
  Could not lex the value "[[1,4],[2,5]]".`

The same file has fixtures with values like '[1,2,3,4]', and they do not seem to cause any issue.

Yes, I am trying to store some strings which can be decoded as  JSON arrays.

Thanks.

**Comment by theofidry** [comment]
I see nothing wrong with your notation so I guess it's just a mistake in the lexer that doesn't handle well nested arrays. Maybe `<([[1,4],[2,5]])>` will work better

**Comment by msypes** [comment]
Thanks, but that didn't work either. I've tried simplifying my file to test one thing at a time, and none of my strings that look like arrays are getting properly escaped:

- `'\["1-2", "3-4", "5-1", "2-3", "5-4", "1-3", "2-5", "4-1", "3-5", 4-2"]'` -> Array to string conversion error
- `'\[1,4]'` -> Array to string conversion error
- `'\[[1,4],[2,5]]'` -> Could not lex the value "\[[1,4],[2,5]]" (Additional backslashes don't help.)
 - `<([[1,4],[2,5]])>` -> Array to string conversion error
- `'<([[1,4],[2,5]])>'` -> Array to string conversion error

Again, to be clear, I don't want these interpreted as arrays. They're just strings that **look** like arrays.

**Comment by theofidry** [comment]
oh I see, I misunderstood then: `<("[[1,4],[2,5]]")>`, `<()>` is basically an eval so that should work...

I'm mildly surprised that it's failing on nested arrays but the 2nd example is more concerning

**Comment by msypes** [comment]
Thank you!
`<("[[1,4],[2,5]]")>` works.

Never mind about the `'\[1,4]'` and `'\["1-2", "3-4", "5-1", "2-3", "5-4", "1-3", "2-5", "4-1", "3-5", 4-2"]'`. Those **do** work. (It turned out I hadn't simplified things enough, and the array to string conversion errors were coming from another source.

**Comment by msypes** [comment]
Thanks for marking this as a bug. I have some additional information for you:
While `<('[{"type":"foo","number": 5,"bar":"baz"}]')>` works as far as getting an actual string into the database, the format is wrong for extracting it as a JSON array using Doctrine's `json` datatype. The string ends up in the database as `"[{\"type\":\"foo\",\"number\": 5,\"bar\":\"baz\"}]"`, _i.e._, surrounded by quotes and with the internal quotes escaped. It needs be be `[{"type":"foo","number": 5,"bar":"baz"}]`

**Comment by msypes** [comment]
Yes. **If** I apply `json_decode`. 
The `json` datatype provided by [Doctrine](http://docs.doctrine-project.org/projects/doctrine-dbal-en/latest/reference/types.html#json) is supposed to return the array without the need for `json_decode`. At least if I _correct_ the escaped string to what I posted above, Doctrine returns it as an array.

**Comment by theofidry** [comment]
[From what I see](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/JsonArrayType.php#L44) it _does_ a `json_decode`.

**Comment by msypes** [comment]
If had to guess, it's the surrounding quotes that are messing things up, requiring me to do my own `json_decode`.
I have been able to readjust my fixture data to function as I want/expect, so I'm OK. I'm just providing this for your information, and for anyone else who hits upon similar difficulties.

**Comment by theofidry** [comment]
I've look into this again and I can't find a simple fix. Or rather it does work for me, `"[{\"type\":\"foo\",\"number\": 5,\"bar\":\"baz\"}]"` is a valid JSON string which alternative format is `'[{"type":"foo","number": 5,"bar":"baz"}]'`.

So if someone still have an issue with a similar case please feel free to open a new issue with the failing data :)
