### ISSUE TITLE
Could not determine access type for property in TRAIT

### ISSUE THREAD

**Issue by danielspk** [nelmio/alice#805]
Hello, my entity uses trait to declare properties. I get the following error: [Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException] - Could not determine access type for property "XXX" in class "XXX".

**Comment by theofidry** [comment]
Hi, unfortunately I cannot help with more information but this is much more likely to be about the Symfony Property Access component. Please double check that the issue is really caused by the usage of a trait and if that's the case I recommend you to open an issue on the Symfony repository with a reproducible case.

**Comment by danielspk** [comment]
I use Doctrine ORM without Symfony.

Example:
`
trait CodeTrait
{
  /** @Column(type="string", length=15) */
  private $code;
}

class CivilState
{
  use CodeTrait;

  /**
   * @Id @Column(type="integer")
   * @GeneratedValue
   */
  private $id;

  //.. other properties and methods
}
`

The *code* property is not accessible by the Alice library.

**Comment by theofidry** [comment]
Hi,

I did not mean that you were using Symfony, but alice _is_ using the Symfony Property Access component to access to properties.

Accessing to a private property has been deprecated in 2.x and is removed (by default) in 3.x. It is still possible to do it [cf. this entry](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#custom-accessor).

I'm re-opening the issue as there is two things to do here:

- @danielspk could you please check if when using the latest version of 2.x you had a deprecation message regarding the access to that private property?
- Add this as an entry in a FAQ

**Comment by danielspk** [comment]
Hi,

I use version 2.3.1, i do not see any deprecated messages.

Caution: In version 3 other private properties (inside class) work well, only fails with the private properties contained within a trait.

**Comment by dunglas** [comment]
It's not related to the trait, the PropertyAccess component do not support private properties without accessor methods (it's intended). You need to add a setter.

**Comment by theofidry** [comment]
@danielspk I've just tested your case and it does work with the hydrator mentioned in the doc in my previous comment. It doesn't work out of the box in 3.x as it was creating too many wtf situations and as pointed earlier, it is still possible to do it.

Regarding the deprecations, you _should_ see something. #816 and an existing test are ensuring it works. If you don't see it you may be missing the PHPUnit bridge.
