### ISSUE TITLE
Clearing cache on dev env throws exception with v2.3.2

### ISSUE THREAD

**Issue by curtchn** [nelmio/alice#823]
`Fatal error: Class 'Nelmio\Alice\Fixtures\Loader' not found in [ProjectLocation]\vendor\hautelook\alice-bundle\src\Alice\DataFixtures\Fixtures\Loader.php on line 22`
`PHP Fatal error:  Class 'Nelmio\Alice\Fixtures\Loader' not found in [ProjectLocation]\vendor\hautelook\alice-bundle\src\Alice\DataFixtures\Fixtures\Loader.php on line 22`

No exception occuring at 2.3.1

**Comment by theofidry** [comment]
Should be fixed, I did a mistake when releasing 2.3.2, it was based on master instead of 2.x 😕

**Comment by curtchn** [comment]
2.3.3 fixes issue. Can be closed. Thanks :+1:
