### ISSUE TITLE
Native Yaml constant support

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#827]
I open this one because #680 was closed by the author.

As said in https://github.com/nelmio/alice/issues/680#issuecomment-282786124, this annotation should work:

```
<(AppBundle\Enum\CampaignType::GOOGLE_ADWORDS)>
```

Still, I think we should deprecate this in favor to the standard notation in order to avoid duplication and confusion.

Ref: http://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files

WDYT?

I supposed you only accept features on the current 3.x stable?

**Comment by theofidry** [comment]
I don't think the above should be deprecated as there is nothing wrong with it and no special parsing involved (trying to detect those cases would be more of a pain than anything). However we could indeed promote the other way in the doc as a preferred way.

>I supposed you only accept features on the current 3.x stable

I don't really mind actually, there is still plenty of people using 2.x. My only requirements are:

- the CI must be updated accordingly if needed and the tests must pass
- if is a new feature, it must be ported to 3.x as well

**Comment by Soullivaneuh** [comment]
> I don't think the above should be deprecated as there is nothing wrong with it and no special parsing involved (trying to detect those cases would be more of a pain than anything).

I can understand. I suppose the `<()>` notation is simply PHP interpretation?

> However we could indeed promote the other way in the doc as a preferred way.

Looks reasonable.

> I don't really mind actually, there is still plenty of people using 2.x. My only requirements are...

Well, in this case I think this can be done on 2.x and back-ported with ease as the integration looks like just the `Yaml::PARSE_CONSTANT` option usage.

I'll take a look when I'll got some time, thanks.

**Comment by theofidry** [comment]
>I can understand. I suppose the <()> notation is simply PHP interpretation?

Yep, we simply detect that function and we do an `eval()` and its content without trying to interpret what's do there
