### ISSUE TITLE
Virtual package for persistence layer

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#830]
Not sure about this, but according to your upgrade guide:

> Removing the persistence layer. This work should be handled in Alice extensions such as AliceDataFixtures

Would not be better to write persistence interfaces and make virtual package?

Or maybe this is not possible because the persistence layer is not necessary to use the alice package?

Regards.

**Comment by theofidry** [comment]
This could be possible, the reason I did not do so:

- I really wanted to keep the persistence stuff out of nelmio/alice as it brings a lot of infrastructural complexity. As small as AliceDataFixtures is, it's already a huge pain to deal with although it is 100x much better than HautelookAliceBundle 1.x.
- Having the persistence interfaces in nelmio/alice would make it harder to update AliceDataFixtures when necessary. Also alice is more and more used without the persistence layer so I also like the idea of removing the omnipresence of the persistence layer
- I don't have full control of nelmio & hautelook, as such I can't easily move everything under a new org (plus that would require an appropriate branding and I have no idea for neither the name or the logo)

So whilst this could be doable, it was simpler the other way :)

**Comment by Soullivaneuh** [comment]
Quite understandable. Feel free to keep this issue open as an idea for later or close it if you think it would not be made.

**Comment by theofidry** [comment]
Nope closing. I'm not against the idea per se but I don't really have enough time to do such changes :/

That can change if someone finds a good branding for an actual organisation in which case it would make sense to move everything under it. But without it would just be moving a weird collection of packages together without a real identity.
