### ISSUE TITLE
2.1.5 release for Symfony 3.3 deprecations

### ISSUE THREAD

**Issue by mcfedr** [nelmio/alice#832]
I cannot make a pull request as there is no where to merge into

The point is it has the fix for Singularize deprecation, but need it in 2.1 where php 5.5 is still allowed https://github.com/nelmio/alice/pull/407

I know, I know, what I am doing with 5.5, unfortunately I have yet to get rid of it... I understand if you reject this, but this single commit as a patch for 2.1.5 would be great... (I promise I'm working on upgrade to 7.1 asap :) )

https://github.com/nelmio/alice/compare/2.1.4...mcfedr:2.1.x

**Comment by theofidry** [comment]
Yes I'm not really sure I want to create a new branch to maintain for that :)

I know how it is to develop on legacy project, but I think an easier solution here is to for the project and use that fork instead [see VCS repositories](https://getcomposer.org/doc/05-repositories.md) which allows you to do any dirty thing you need to get done before being to upgrade without having the downside of public OSS work. You can then freely work on the upgrade to catch up.

**Comment by mcfedr** [comment]
Thats fine, I have already stuck it in my project using the fork, but thought I'd share it just in case.
