### ISSUE TITLE
Locale value is not used on faker generator creation

### ISSUE THREAD

**Issue by babeou** [nelmio/alice#835]
On NativeLoader the createFakerGenerator method doesn't care of "locale" custom value.
It takes en_EN by default

**Comment by theofidry** [comment]
Indeed the local should be passed [here](https://github.com/nelmio/alice/blob/master/src/Loader/NativeLoader.php#L564). So we could add a protected constant `LOCALE = 'en_EN'` in `NativeLoader` and the use that default constant when instantiating the Faker generator
