### ISSUE TITLE
Chained function (faker or native) does not work

### ISSUE THREAD

**Issue by Divi** [nelmio/alice#842]
Hello, if I use this [example](https://github.com/nelmio/alice/blob/v3.0.1/doc/advanced-guide.md#functions) :

```yaml
nestedFunctionValue: '<strtolower(<(implode(" ", ["HELLO", "WORLD", \<foo()>]))>)> \<bar()>'
```

I got this error : 

```
[Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\MalformedFunctionException]     
  The value "<(implode(__ARG_TOKEN__7215ee9c7d9dc229d2921a40e899ec5f" contains an unclosed function. 
```

Version : v3.1.2

**Comment by theofidry** [comment]
I think this example was a bit too wild, in practice the lexer is not good enough and there is still limitations...

**Comment by Divi** [comment]
My first try was using native function `ucfirst()` with Faker `words()` function and native `rand()`, like `<ucfirst(words(rand(1, 3)))>` but I couldn't manage to do it.

**Comment by theofidry** [comment]
This one looks simple enough to make it work, but the alternative in the meantime is to leverage faker providers

**Comment by theofidry** [comment]
I've had a quick look but didn't find a satisfying solution. I'll close however as to me it's part of #601. The current in-house system is to have something somewhat working, but switching to a proper lexer/parser like HoaCompiler with a defined grammar is the way to go to avoid those issues.
