### ISSUE TITLE
Include system should avoid duplicate inclusion

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#845]
If you have this `server.yml` fixture file:

```yaml
include:
  - os.yml
  - backup_model.yml

AppBundle\Entity\Server:
# ...
```

And you load these fixture files:

```
__DIR__.'/../../../fixtures/orm/os.yml',
__DIR__.'/../../../fixtures/orm/backup_model.yml',
__DIR__.'/../../../fixtures/orm/server.yml',
```

You will have duplicate entries error because the `os` and `backup_model` files are loaded twice.

It should be avoided. Or at least, an `include_once` directive should be proposed.

**Comment by theofidry** [comment]
You're right. I don't think this can be changed as I believe that was the behaviour since 2.x so I would be up for a new `include_once` option 👍

**Comment by Soullivaneuh** [comment]
Is this feature acceptable on 2.x or not?

**Comment by theofidry** [comment]
I don't mind features on 2.x, but they must be ported in 3.x as well
