### ISSUE TITLE
Inconsistent behavior of optional operator with empty strings

### ISSUE THREAD

**Issue by ju1ius** [nelmio/alice#849]
Probably related to #601 ?

## Current behavior
Using the following fixture file:
```yaml
AppBundle\Entity\Foo:
  title: '50%? <sentence()> : ""'
```
Results in the string `""` being insterted in the database.

Using the following fixture file:
```yaml
AppBundle\Entity\Foo:
  title: "50%? <sentence()> : ''"
```
Results in an empty string being inserted in the database.

## Expected behavior

Both fixture files should result in an empty string being inserted in the database.

## Dependencies
```json
{
    "require-dev": {
        "doctrine/data-fixtures": "^1.3",
        "hautelook/alice-bundle": "^2.0",
        "nelmio/alice": "^3.1",
        "theofidry/alice-data-fixtures": "^1.0"
    },
}
```

**Comment by theofidry** [comment]
Actually maybe this one is different as I guess if you want a `""` or `''` as a string input the expression should be `\"\"` and `\'\'`

**Comment by theofidry** [comment]
Actually looking at this again, this is a legit case. Indeed there is no way to understand that `""` should be interpreted as an empty string as your expression is strictly equivalent to say "50% changes of having `'<sentences()>'` (which will be interpreted) or having `'""'` which is a plain string. If you want the result to be evaluated in an empty string i think that's the case where a custom Faker provider is required.

**Comment by dribtech** [comment]
Actually there is no need to custom Faker. Since PHP functions can be used as providers, this works reliable:
`addressNote: '20%? <sentence()>: <strval("")>'`
Of course instead of `""` you can use anything that will evaluate into empty string by `strval`.
