### ISSUE TITLE
Managing Embeddables - No suitable fixture denormalizer found

### ISSUE THREAD

**Issue by petegore** [nelmio/alice#856]
Hi,

Reading some issue there, I noticed that the `(local)` flag had been removed month ago.

But I didn't find how to manage **embeddables** right now ? When I juste remove the local flag (expecting Alice to understand by communicating with Doctrine) I got the following error : 

```
No suitable fixture denormalizer found to handle the fixture with the reference "<my embeddable>"
```

Is that due the embeddable itself, or does it come from something else in my fixtures ?

Thanks !

**Comment by theofidry** [comment]
Hello,

Indeed as from alice 3.x there is no notion of persistence, it no longer makes sense to have a `(local)` flag which was used to point if an object should be persisted or not.

So this embeddables handling has been delegated to FidryAliceDataFixtures with the persistence layer. It is handled directly in the Doctrine Persister which won't persist those, you can see it [here](https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php#L59)

**Comment by petegore** [comment]
Hi theo, thanks for you answer.
So in other word : you decided to evolve nelmio/alice in a way that doesn't support all Doctrine features, am I right ? (sorry for my english sometimes a little uncertain !)

Is there a reason for that ? Do you consider that embeddables are something that developer should avoid using ? I'm curious ! Maybe I could use another way !

**Comment by jvasseur** [comment]
@petegore this means nelmio/alice has nothing to do with Doctrine anymore, all it does is converting fixture files into objects and let other libraries (FidryAliceDataFixtures for example) handle saving those objects into the persistence layer.

**Comment by theofidry** [comment]
Exactly as @jvasseur said.

Taking care of the persistence layer, i.e. making sure those fixtures can be saved in a database with Doctrine or another is a very complex issue. I didn't want to cripple this library with this kind of problem as alice is complex enough as it is. Doing this in a separate library makes more sense, this is why I created `theofidry/alice-data-fixtures`.

As for the usage of embeddables, I have no issue with it :)

**Comment by petegore** [comment]
Okay I understand better what I missed.
I was pretty sure that Alice was created for Doctrine at the beginning. Because when you create your fixtures, you can automatically insert them using `doctrine:fixtures:load`. My bad.

I'll have a look at `theofidry/alice-data-fixtures` thanks a lot 😃
