### ISSUE TITLE
Generation of fixtures with two function separated with underscore fails

### ISSUE THREAD

**Issue by rvadym** [nelmio/alice#861]
**Tag:** `v3.1.3`

Fixture example:

```
App\Entity\City:
    city_{1..20}:
        name: <city()> <current()>
        slug: <city()>_<current()>
```

This part `name: <city()> <current()>` works perfectly, but following part `slug: <city()>_<current()>` fails with error 
![fail](https://user-images.githubusercontent.com/701083/36351674-c0f6c2a2-14ad-11e8-8e0f-06721f53c1f9.png)

**Comment by rvadym** [comment]
**Possible fix:**

Replace regex in [this line](https://github.com/nelmio/alice/blob/v3.1.3/src/FixtureBuilder/ExpressionLanguage/Parser/TokenParser/Chainable/TolerantFunctionTokenParser.php#L36)
from
`const REGEX = '/(\)>)(\ *)</';` 
to
 `const REGEX = '/(\)>)([\ \_]*)</';`

![screen shot 2018-02-18 at 2 36 17 pm](https://user-images.githubusercontent.com/701083/36352426-2a9e2a8c-14b9-11e8-8ac4-5d8c0d129963.jpg)

**Comment by theofidry** [comment]
Thanks for the detailed bug report!

Could you try to submit a PR with the fix? :) To run the tests to see if that works you can use the `make test` command

**Comment by rvadym** [comment]
@theofidry Sure, will do it ASAP. Thanks!
