### ISSUE TITLE
Make debugging easier

### ISSUE THREAD

**Issue by stof** [nelmio/alice#871]
When an error occurs, it is quite hard to understand where it comes from.

I get an error like that:

```
  [Nelmio\Alice\Throwable\Exception\Generator\Resolver\FixtureNotFoundException]  
  Could not find the fixture "challenge_1A".    
```

But I have not idea where this `challenge_1A` reference comes from in my fixtures (AFAICT, I have no such reference).

**Comment by theofidry** [comment]
I completely agree and I attempted several things to have a more comprehensible error message. But not a single time it proved to be useful and I had to take a look at the stack trace as of why.

One of the issue is that you can't tell at all from which file the fixtures are coming from: this information is lost and you could very well have duplicates across the files (but if the keys match then you actually have any duplicate in your fixtures).

That said maybe we could manage to include for which fixture ID + property it failed when a failure occurs.

**Comment by stof** [comment]
having the fixture id and property would already help, yes.

**Comment by dkarlovi** [comment]
Similar issue:

```
    Given the database fixture file "@PrivilegeBundle:privilege-matrix.yml" is loaded # App\Behat\DatabaseContext::theDatabaseFixtureFileIsLoaded()
      Could not resolve value during the generation process. (Nelmio\Alice\Throwable\Exception\Generator\Resolver\UnresolvableValueDuringGenerationException)
```

Couldn't resolve **what** value?

**Comment by theofidry** [comment]
@dkarlovi It's hard to know as you may have multiple pass for the value being resolved so if I bail out saying value X, that value may be the result of something else itself not the original one.

Maybe it would be possible to mention the original value, I don't remember if I attempted this.

**Comment by stof** [comment]
the error in such case is available in the previous exception. But Behat does not display the message of the previous exception.

Here is how my own example actually looked like:

```
In UnresolvableValueDuringGenerationExceptionFactory.php line 25:

  Could not resolve value during the generation process.  


In FixtureNotFoundExceptionFactory.php line 23:

  Could not find the fixture "challenge_1A".  

```

**Comment by dkarlovi** [comment]
@stof that's an easy fix then, just incorporate previous exception's error here?

**Comment by theofidry** [comment]
Yeah but look at that example, you could have: `Could not resolve value during the generation process: Could not find the fixture "challenge_1A".`, you still wouldn't know from where `challenge_1A` is coming from and that might be the result of a processed value.

**Comment by dkarlovi** [comment]
Yes, but if the original issue is fixed, both exceptions benefit, no?

**Comment by theofidry** [comment]
You mean if we include the fixture ID + property? Yeah that might be enough then

**Comment by stof** [comment]
@theofidry including the fixture ID and property in the error message would help a lot, yes. This would allow finding the location easily in the fixture files.

**Comment by theofidry** [comment]
I agree, although keep in mind that fixture ID can be dynamic. I.e. if you get `dummy_1` in the log and look for it in your fixture files, you might not find it because it can be the result of `dummy_{1..10}`

**Comment by stof** [comment]
well, it will still give me some indication (and if I know my fixtures, I can probably identify that this id matches some of my lists/range).

Next improvements after that could be to build a command allowing to locate sources for a given id: give a fixture id, and it would load the different fixture files to find places generating this id (so a special loading mode, caring only about ids), to give you the original location and the original id/list
