### ISSUE TITLE
Usage without Doctrine persistance?

### ISSUE THREAD

**Issue by hiromik** [nelmio/alice#877]
Hello,

Is it possible to use the yaml loading part with relations without persisting it in the database?
I want to use a yaml file for mocking purpose (app doesn't have or need database) with the power of Alice's relationships etc but I just want to retrieve the hydrated entities.

Thanks

**Comment by theofidry** [comment]
Yes, just use Alice 3.x :)

**Comment by hiromik** [comment]
Thanks for the reply, my bad, should have checked : 
```
$loader = new Nelmio\Alice\Loader\NativeLoader();
$objectSet = $loader->loadFile(__DIR__.'/fixtures.yml');
```
In the meantime I went to use https://github.com/schmittjoh/JMSSerializerBundle since it's already required in my project, so I just create my .json file and deserialize using `@Type` annotation :)

**Comment by theofidry** [comment]
Closing then :)
