### ISSUE TITLE
Self with condition - Alice 3.X

### ISSUE THREAD

**Issue by OneT0uch** [nelmio/alice#881]
Hello,

Is it possible to use @self with a condition like : 

```
isA: '<boolean(90)>'
b: '@self->isA ? <numberBetween(1, 200)>'
```
b should be a number between  1 and 200 only if isA is true.

Maybe refer to this issue : https://github.com/nelmio/alice/issues/281
Thank's

**Comment by theofidry** [comment]
Hi. Actually no optional values right now only support a percentage, see [this doc entry](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#optional).

I'm not against adding this feature though, so PRs are welcome :)
