### ISSUE TITLE
Use <current()> when construct a DateTime object

### ISSUE THREAD

**Issue by rchomat** [nelmio/alice#893]
Hi,

I try to set a DateTime object into one of my entity. Because I need to create several of this entity, I wanted to use the current function to format my date.
Here is an example of what I tried
```
AppBundle\Entity\Order:
    order_{1..2}:
        user: '@customer1'
        createdAt: '<(new \DateTime("next tuesday +<current()>-1 weeks"))>'
```

Is there a way to do something like this ?

Thank you for your help :)

**Comment by theofidry** [comment]
Hi,

Although in theory possible, I think this is bout to be brittle until #712 is out so I would recommend you to use a [custom faker provider](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers) instead :)
