### ISSUE TITLE
Fixture list syntax is not BC with Alice 2

### ISSUE THREAD

**Issue by stof** [nelmio/alice#909]
In Alice 2, the separator for fixture lists was a comma followed by an optional space. In 3.x, the space is now required. This makes migration painful when fixtures were written without the space (the error message is totally understandable in this case btw).

Since the time I tried it, this has been documented in the upgrade guide, but it would still be great if the error message could be improved then.

**Comment by theofidry** [comment]
I think this could be done in #871. I'll just keep the issue open to make sure to double check when we implement a solution for #871.
