### ISSUE TITLE
Trimming in the template syntax does not work the same anymore in 3.x

### ISSUE THREAD

**Issue by stof** [nelmio/alice#911]
Alice 2.x was trimming the string inside `(extends foobar )` to extend only `foobar`. In 3.x, the space is included in the reference name.

**Comment by reinfi** [comment]
Can't reproduce this. What's your usecase where this causes an error?

Code uses already a trim function:
https://github.com/nelmio/alice/blob/c61f1a782207a675c4cfd2840a6892a1be2a348b/src/FixtureBuilder/Denormalizer/FlagParser/ElementFlagParser.php#L53

**Comment by theofidry** [comment]
ping @stof

**Comment by stof** [comment]
sorry, I messed up the description. the issue was not about spaces after the name, but about extra spaces before the name: `(extends  foobar)` (notice the 2 spaces after `extends`)
