### ISSUE TITLE
Question - Persist and reference a first set of entities/objects

### ISSUE THREAD

**Issue by stphane** [nelmio/alice#914]
Alice has given away the persistance layer in 3.x. Now, migrating from 2.2 to 3.0.x, …  

I need to persist some few fixtures first (so their `id` get popullated) and then reference those entities ids from another bunch of fixture files.

I guess I may have to loop and load multiple fixture files sets separately but I have no idea how the object references will subsist in such scenario.  How can this be achieved ?

My setup currently doesn't work but causes the following error to prompt:
> Invalid value given for the property "fooDbId" of the object "bar1"
  (class: Doctrine\Model\Bar).

My _FixturesLoader.php_:

    // …
    use Nelmio\Alice\Loader\NativeLoader as AliceLoader;
    // …
    $loader = new AliceLoader();
    $entities = $loader
        ->loadFiles(
            [
                __DIR__.'/foo.yml',
                /* ↓ Some more fixture files ↓ */,
               # Here comes "bar" which references persisted foo entities id
               # through its "fooDbId" property using expresion '@foo1->id'
                __DIR__.'/bar.yml'
            ],
            ['locale' => 'en_EN']
        )
        ->getObjects();

    foreach ($entitites as $entity) {
        $manager->persist($entity)
    }

    $manager->flush();

_bar.yml_ :

    Doctrine\Model\Bar:
        bar1:
            fooDbId: '@foo1->id'
            # ↓ More properties ↓
    
**Thank you**

**Comment by theofidry** [comment]
If you generate an ID for all of those fixtures it's gonna be fine with https://github.com/theofidry/AliceDataFixtures, otherwise you'll have to write your own loader instead to override the existing one.

If you need more help on this I recommend you to pock the #alice-fixtures channel from the [Symfony Slack](https://symfony.com/slack-invite). I'm not being uncompromising about it but I would prefer to keep the issue for actual issues as opposed to questions :)

**Comment by stphane** [comment]
@theofidry thank you for your time. I do not generate id myself, ids are generated while the underlying object gets persisted to database. I moved the question to Stackoverflow, sorry for the inconvenience.

**Comment by theofidry** [comment]
If you give the link I can share it in the slack eventually :)

**Comment by stphane** [comment]
Thank you very much! [Here is the thread](https://stackoverflow.com/questions/49648923/alice-fixtures-persist-and-reference-a-first-set-of-entities-objects)
