### ISSUE TITLE
settype documentation issue?

### ISSUE THREAD

**Issue by ostrolucky** [nelmio/alice#916]
[docs](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#cast) recommend to cast, we should use `settype`. Here are the problems:

- Example lists arguments of this function reversed
- It returns boolean
- It requires value to be passed by reference. I think you solved this issue somehow on your side, but it's confusing anyway.

Instead, user should be directed to functions like `intval()` etc

**Comment by theofidry** [comment]
It's true with have those casting functions so we should go with that instead indeed 👍

**Comment by ostrolucky** [comment]
Thank you @reinfi
