### ISSUE TITLE
Faker file and file PHP native function

### ISSUE THREAD

**Issue by nlemoine** [nelmio/alice#920]
I'm trying to use Faker [`file` formatter](https://github.com/fzaninotto/Faker#fakerproviderfile) but Alice is trying to execute native PHP [`file`](http://php.net/manual/en/function.file.php) function.

Is that a bug? Any workaround?

**Comment by theofidry** [comment]
There is no way Alice can guess which one to use so you have to tell Alice about it in those case. See [the related doc entry](https://github.com/nelmio/alice/blob/master/doc/getting-started.md#symfony).  The configuration linked is for Symfony but you should be able to configure it as well with the `NativeLoader`

**Comment by nlemoine** [comment]
Just had a quick look to to the `NativeLoader`. I think I'll stick to my cheap fallback solution (creating a custom provider that aliases the Faker `file` method). 

Thanks for your feedback.

**Comment by theofidry** [comment]
But if you use a custom provider you'll need to register it in `NativeLoader` anyway no? Btw the line is https://github.com/nelmio/alice/blob/master/src/Loader/NativeLoader.php#L571
