### ISSUE TITLE
Faker call combination doc

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#930]
I'm trying to cast the result of a faker:

```yaml
AppBundle\Entity\Package:
    package_{1..50}:
        __construct:
            - '@server_*'
            - '@packagemodel_*'
            - <strval(randomFloat(2, 1, 42.5))>
```

Currently not working, taking `randomFloat(2` as a parameter.

This is understandable, but I can't fin anything on the documentation for this quite simple need.

I'm might be blind afterall, am I right? ;-)

**Comment by theofidry** [comment]
No it should work, it's likely to be a lexing issue

**Comment by theofidry** [comment]
Never mind, the syntax should be `<strval(<randomFloat(2, 1, 42.5)>)>` not `<strval(randomFloat(2, 1, 42.5))>` :)
