### ISSUE TITLE
Disable some listeners on fixture loading

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#931]
I have some entity listener, triggering another events when some entities are persisted to activated mail sending and stuff.

Obviously, they are called on fixtures loading.

I would like to be able to deactivate some of them each time a fixture is loaded.

I'm not sure if is the responsibility of nelmio/alice directly, but maybe some event triggering of this library would help to achieve this need?

Also, maybe it's an issue for alice data-fixtures.

WDYT?

**Comment by theofidry** [comment]
I'm not sure how triggering an event would help not to trigger another one.

It's likely to be very specific to one's use case. Maybe an easy way for you would be to either manually disable it in a loader (you can decorate loader used with your own) to disable it, or disable it in a specific environment which is the environment you load the fixtures in.

>Also, maybe it's an issue for alice data-fixtures.

More likely yeah :)

**Comment by Soullivaneuh** [comment]
I'm not sure to understand your propositions.

Any chance you have an project sample link to give?

**Comment by theofidry** [comment]
My suggestion is creating a new loader class and decorating AliceDataFixtures autoloader (as Symfony service decoration).

In it you could somehow try to disable the appropriate Doctrine listeners, but I'm not sure how you can do that it's just an idea I'm throwing.

The alternative is for example loading the fixtures in `dev` or `test` environment and not register those listeners in those environments

**Comment by Brewal** [comment]
I manage to do it using [Processors](https://github.com/theofidry/AliceDataFixtures#processors)

Here in my case, I disable a listener that generates thumbnails from an `Image` entity : 

```php
<?php

namespace App\DataFixtures\Processor;

use App\Doctrine\Listener\ImageListener;
use App\Entity\Common\Image;
use Doctrine\ORM\EntityManagerInterface;
use Fidry\AliceDataFixtures\ProcessorInterface;

final class ImageProcessor implements ProcessorInterface
{
    private const LISTENERS_TO_DISABLE = [
        ImageListener::class
    ];

    private $manager;

    public function __construct(EntityManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    /**
     * @inheritdoc
     */
    public function preProcess(string $fixtureId, $object): void
    {
        if (!$object instanceof Image) {
            return;
        }

        $metadata = $this->manager->getMetadataFactory()->getMetadataFor(Image::class);

        foreach ($metadata->entityListeners as $event => $listeners) {
            foreach ($listeners as $key => $listener) {
                if (in_array($listener['class'], self::LISTENERS_TO_DISABLE)) {
                    unset($listeners[$key]);
                }
            }

            $metadata->entityListeners[$event] = $listeners;
        }

        $this->manager->getMetadataFactory()->setMetadataFor(Image::class, $metadata);
    }

    /**
     * @inheritdoc
     */
    public function postProcess(string $fixtureId, $object): void
    {
        // do nothing
    }
}
```

I tried to use `$em->getConfiguration()->getEntityListenerResolver()->clear(ImageListener::class)` without success... Thus this nasty solution inspired by [this SO post](https://stackoverflow.com/a/53503471/2168947)
