### ISSUE TITLE
unique constraint on self-referencing m:n entities causes stack trace

### ISSUE THREAD

**Issue by BigBadBassMan** [nelmio/alice#936]
Hi there,

I'm using alice 3.4 with symfony 4 and hautelook/alice-bundle 2.0, so this seems to be recent:

I have several m:n relations like this (pseudo code, the goal is to have relations to several otherObj from one MyObj, but no duplicate entries in the relation table):

```
class MyObj {
    /**
     *
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="OtherObj", inversedBy="relatedMys")
     * @ORM\JoinTable(name="my_other_obj",
     *      joinColumns={
     *          @ORM\JoinColumn(name="myObj", referencedColumnName="id")
     *      },
     *      inverseJoinColumns={
     *          @ORM\JoinColumn(name="otherObj", referencedColumnName="id", unique="true")
     *      }
     * )
     */
    private $relatedOthers;
}
```
'
when defining fixtures like this (with around 50 otherObj fixtures accordingly):
```
Namespace\MyObj:
    myobs{1..300}:
        relatedOthers (unique):  '<numberBetween(1, 10)>x @otherObj*
````

alice fails with a stack trace and the message: "Nesting level too deep - recursive dependency?"

dropping the unique constraint is no option, it is enforced by the database, and alice often seems to randomly choose duplicate values for a single related array, although there are plenty to choose from.

So the question is: am I doing something wrong, or is there some other way of achieving this? Lowering the numbers does not change a thing. Also defining static arrays of say 2 random related otherObj gives the same error.

**Comment by theofidry** [comment]
It’s also possible. The best way would be to debug it, there is a
UniqueValueResolver or Pool which you can check

**Comment by theofidry** [comment]
Ah I see, thanks for digging into this.

I'm a bit conflicted because I'm afraid there's cases where you expect comparison by _values_, i.e. you provide a pool of objects and you want to compare their values not their references but it will bail out on incomparable objects like you have

**Comment by BigBadBassMan** [comment]
Thats why you're chief of staff ;-)

I cannot judge, if there are such cases, and if they are many.
Does your test suite cover this with the current comparison operator? It should bail on changing the operator, if some fundamentals break, somewhere.
(Maybe I can assist in extending the tests to includy my specific problem...)

I would really like to see this fix included.

**Comment by theofidry** [comment]
>Thats why you're chief of staff ;-)

It's not like I have been appointed for it :) I just happened to want some changes pushed and manage to get them 😄 

>Does your test suite cover this with the current comparison operator? It should bail on changing the operator, if some fundamentals break, somewhere.

I honestly do not know. If you can open a PR for it would be great, the tests will say if it's covered or not and if not we can try to include this fix and see if it causes issues to other people or not. It's a case were deciding or not if it's a real BC is defined by the users
