### ISSUE TITLE
NativeLoader->LoadFiles load data in reverse order

### ISSUE THREAD

**Issue by sami-bel** [nelmio/alice#941]
We add numbers at start of the filenames to ensure that the loading order is as expected.

Upgrading from 1.5.*@dev to v3.1.3 introduce some bigs changes.

Files data are added in database in reverse order...

To fix it, we have modified this script on line 38: `vendor\nelmio\alice\src\Parser\IncludeProcessor\IncludeDataMerger.php`

Before: 
```php
? array_merge($includeData[$class], $fixtures)            
````

After:
```php
 ? array_merge($fixtures, $includeData[$class])
````

**Comment by theofidry** [comment]
>Upgrading from 1.5.*@dev to v3.1.3 introduce some bigs changes.

Indeed...

>Files data are added in database in reverse order

What you are describing is a bit different: it's about the files imported by your fixture files. I can't remember if that was deliberate (for a peculiar feature or BC with 2.x) or a mistake. The best way to find out is to try the change and see if the tests break

**Comment by vtexier** [comment]
I finally had the time to run the tests with @sami-bel:

With the fix proposed to load the files in order, the tests run by `php -d zend.enable_gc=0 bin/phpunit` failed:

Among the failed, we notice that the test expects an inverse order (!!???), but get a good order from a user perspective: 

  ```php
Array &0 (
     'Nelmio\Alice\Model\User' => Array &1 (
-        'user_file3' => Array &2 ()
-        'user_file2' => Array &3 ()
-        'user_file1' => Array &4 ()
-        'user_main' => Array &5 ()
+        'user_main' => Array &2 ()
+        'user_file1' => Array &3 ()
+        'user_file2' => Array &4 ()
+        'user_file3' => Array &5 ()
     )
 )
```

I see that you gonna fix it, and we thank you for that.

Alice is a great tool !

**Comment by theofidry** [comment]
You might want to take a look at #945 for some details regarding the order, there was a bug there
