### ISSUE TITLE
Invalid postcode for Austria

### ISSUE THREAD

**Issue by tniemann** [nelmio/alice#942]
Hi,

i used fixtures for addresses in different countries. But the provided post code for Austria has in some cases a leading zero like 0476 which is not valid. Austrian post codes does start with 1-9 and not with 0. Is there a fix for that?

Regards
Thomas

**Comment by theofidry** [comment]
Hi Thomas,

Unfortunately Alice is not quite aware of this kind of data. You will have to look at [Faker](https://github.com/fzaninotto/Faker) which is the library used underneath for that and double check the different versions as maybe it has already been fixed.

Best,
