### ISSUE TITLE
Add my own provider with the Symfony bridge

### ISSUE THREAD

**Issue by pifaace** [nelmio/alice#974]
Hi,

I'm wondering, 
I'm trying to add my own provider data using NelmioAliceBundle.

I followed this part of the doc : 
https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers

My provider is tagged with nelmio_alice.faker.generator but the Generator doesn't add it to its providers array.
So I get a message error like **Unknown formatter "jobAbbreviation"**

 I tried on Symfony 2.8 and 4.2.

I notice that the method create from the class Faker\Factory get a new instance of Generator : 

```php
public static function create($locale = self::DEFAULT_LOCALE)
    {
        $generator = new Generator();
        foreach (static::$defaultProviders as $provider) {
            $providerClassName = self::getProviderClassname($provider, $locale);
            $generator->addProvider(new $providerClassName($generator));
        }

        return $generator;
    }
```

And so doesn't use the service container instance.

Is that normal ? 
 
Thanks for you help.

**Comment by theofidry** [comment]
A faker instance is created [there](https://github.com/nelmio/alice/blob/master/src/Bridge/Symfony/Resources/config/faker.xml#L19-L30  as `nelmio_alice.faker.generator` or `Faker\Generator` (for autowiring support) and the providers are registered [here](https://github.com/nelmio/alice/blob/master/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterFakerProvidersPass.php#L39-L44).

So it should work as expected, if it doesn't you'll need to debug those two pieces and see what's going on.

**Comment by pifaace** [comment]
Ok so I put a xdebug breaking point [there](https://github.com/nelmio/alice/blob/master/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterFakerProvidersPass.php#L39-L44)
It is triggered and the variable $providers found my provider but still the same error message

**Comment by theofidry** [comment]
It might be worth checking what instance of the Faker generator you are using

**Comment by pifaace** [comment]
Here, what I understood :
at first the compiler pass get the fakerGenerator by its name [there](https://github.com/nelmio/alice/blob/master/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterFakerProvidersPass.php#L39)

Then, it get the tagged services into  $providers and saves them to 
```php
$fakerGenerator->addMethodCall()
```
ok so far.
But the next step is a little bit weird in my opinion. 
The **addProvider** method is called from Factory class
```php
public static function create($locale = self::DEFAULT_LOCALE)
    {
        $generator = new Generator();
        foreach (static::$defaultProviders as $provider) {
            $providerClassName = self::getProviderClassname($provider, $locale);
            $generator->addProvider(new $providerClassName($generator));
        }

        return $generator;
    }
```

My question is, why do you do a new instance of Generator() instead of get it from symfony container ?

**Comment by theofidry** [comment]
>My question is, why do you do a new instance of Generator() instead of get it from symfony container ?

What do you mean?

**Comment by pifaace** [comment]
In the create methode you instantiate a new Generator() instead of 
```php
$generator = $container->get('nelmio_alice.faker.generator')
```
I don't understand why

**Comment by theofidry** [comment]
>In the create methode you instantiate a new Generator() instead of

But which create method?

**Comment by theofidry** [comment]
>I notice that the method create from the class Faker\Factory get a new instance of Generator :

Unless I misunderstood that sentence: this is the base Faker factory, it's a third-party library I have no control on. A generator instance is created with that factory and injected to the container as `'nelmio_alice.faker.generator'` and then it's configured.

**Comment by pifaace** [comment]
Yeah I just go that its not a part of your library lol.
I continue my investigation, I saw on this method https://github.com/nelmio/alice/blob/master/src/Loader/NativeLoader.php#L581
that you get a instance of generator and then add your AliceProvider manually.
Is that the solution that I should do ? Because if a extend your NativeLoader and add manually my providers like this : 

```php
class AppNativeLoader extends NativeLoader
{
    protected function createFakerGenerator(): Generator
    {
        $generator = parent::createFakerGenerator();
        $generator->addProvider(new PersonProvider($generator));
        $generator->addProvider(new DeliverablesProvider($generator));
        $generator->addProvider(new OrderableProvider($generator));
        $generator->addProvider(new TypeAttributesProvider($generator));

        return $generator;
    }
}
```

it works

**Comment by theofidry** [comment]
`NativeLoader` is for allowing the library to be used without a DIC. Although there is a Symfony bundle, it's a library and is usable outside of Symfony.

So you either get your Faker generator instance from the container in which case it should already be configured, or you bypass it completely and use the NativeLoader but in which case you need to manually add the providers like you did

**Comment by pifaace** [comment]
Ok I see ! So in this case : 
> So you either get your Faker generator instance from the container in which case it should already be configured

you said that I don't need the `NativeLoader` ? Sorry for my misunderstanding this is not clear in the documentation

**Comment by theofidry** [comment]
If you have Symfony, you can retrieve the generator from the container, generator which is easily configurable since it's a service.

Now if you don't have Symfony, or if you want to use Alice in a place where the application is not booted, e.g. a unit test, you can make use of the NativeLoader instead (but then you need to make sure it's configured as desired)

**Comment by pifaace** [comment]
okey thanks a lot for your explanations ! I close the issue
