### ISSUE TITLE
Documentation: invalid YAML syntax for static factory

### ISSUE THREAD

**Issue by debach** [nelmio/alice#986]
I'm using `"symfony/yaml": "4.2.*"` and `hautelook/alice-bundle": "^2.4"`. The [documentation on static factory methods](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#using-a-factory--a-named-constructor) suggests the following syntax:

    # fixtures.yaml
    Nelmio\Entity\User:
        user1:
            __factory: { Nelmio\User\UserFactory::create: ['<username()>'] }

This throws

    Nelmio\Alice\Throwable\Exception\Parser\UnparsableFileException:
    The file "fixture.yaml" does not contain valid YAML.

    Caused by

    Symfony\Component\Yaml\Exception\ParseException: Colons must be followed 
    by a space or an indication character (i.e. " ", ",", "[", "]", "{", "}") at line 3 
    (near "__factory: { Nelmio\User\UserFactory::create: [] }").

My fix is to put single quotes around the factory name, like so:

    # fixtures.yaml
    Nelmio\Entity\User:
        user1:
            __factory: { 'Nelmio\User\UserFactory::create': ['<username()>'] }

**Comment by theofidry** [comment]
Putting single quotes is indeed the way to go, the documentation is wrong there. Could you please provide a PR with a fix for it?
