### ISSUE TITLE
Multiple non-persisted new entities were found through the given association graph

### ISSUE THREAD

**Issue by gponty** [nelmio/alice#990]
Hi,
Why i have this message when i load fixtures :
"Multiple non-persisted new entities were found through the given association graph"
(seems the (unique) who dont work)

```
My fixtures :
App\Entity\User:
  user_{1..10}:
    email (unique): <email()>
    password: 

App\Entity\Categorie:
  categoriePere_{0..4}:
    nomCategorie: Banque
    categoriePere: null
    user (unique): '@user*'
```

And last question :
How i can check objects generated by alice ?

Thank you !

**Comment by theofidry** [comment]
Hi,

Regarding your error, can you check that you are using 3.5.0+ which includes https://github.com/nelmio/alice/commit/ffa4ce81a3be6c7c8fb12a7f192eeed4686e8e2f? Alternatively could you try to create a reproducer? (which I guess should be on https://github.com/theofidry/AliceDataFixtures rather).

>How i can check objects generated by alice ?

They should be returned by the loader

**Comment by gponty** [comment]
ty, I use hautelook/alice-bundle
i will try to create a reproducer, ty.
