### ISSUE TITLE
It is posible to generate fixtures based on an entity in the database?

### ISSUE THREAD

**Issue by HarasimowiczKamil** [nelmio/alice#996]
It is posible to generate fixtures based on an entity in the database? This would help to map real cases for large entities. Someone may have already written the command to this one? I was looking but I found nothing :cry:

**Comment by theofidry** [comment]
I believe https://github.com/trappar/AliceGenerator is what you are looking for

**Comment by HarasimowiczKamil** [comment]
Cool, that's what I meant. Thanks a lot!
